### ISSUE TITLE
Accessibility on the DS - approach

### ISSUE THREAD

**Issue by ioanacontu** [cds-snc/design-gc-conception#100]

**Comment by duboisp** [comment]
Is it about the tool we are using to develop the DS or is it about the tool we are going to create or both?

**Comment by mcman12** [comment]
Ioana to share the deck she will present to AAACT to generate the discussions with the group on our approach

**Comment by mcman12** [comment]
Pierre shared the current work of the a11y task force is doing on a new IA for a11y toolkit documentation: https://miro.com/welcomeonboard/cWFQNlBpZ1VQOXNORUJXdXpEVEhZbEpocGgyQ21tZ2dHc3ZLeXBMV1hRdldibHhxMlUzREZVbXVFeUhvY0NVUnwzMDc0NDU3MzY0MDIwMTU5NDIy?invite_link_id=577982854973

**Comment by ioanacontu** [comment]
Shared deck here: https://docs.google.com/presentation/d/1Reb4E12QC_abLl8j34qFGTIOK656ykFvJtsEziZ197E/edit#slide=id.g4cea57f733_0_0
