### ISSUE TITLE
Provide a faster way to get to Github repo

### ISSUE THREAD

**Issue by adriannelee** [cds-snc/design-gc-conception#1000]
When looking for more details on the code, participants wanted a more direct access to the Github. Currently, you have to navigate to a component to find the Github link to that component, then navigate to the Readme. 

### Related research
[Developer onboarding 06/2024 - DoveTail](https://cds-snc.dovetail.com/insights/Provide-a-faster-way-to-get-to-Github-repo-4SNw5yiN25pTPJCWEK2Dj9)

- [x] Add more prominent call to action on contact page for GitHub support form
- [x] Add link to GitHub component repo from [Components overview page](https://design-system.alpha.canada.ca/en/components/) 
- [x] Publish changes

**Comment by SmartMouthWords** [comment]
Contact page has more direct and prominent direction to the GH support page
 <img width="1003" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0lZQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--20d012eb175b50f593c82d8a3505bd1e16599e79/Screenshot%202024-07-29%20at%203.00.01%E2%80%AFPM.png" alt="Screenshot 2024-07-29 at 3.00.01 PM.png" />

**Comment by MatildePerrusclet** [comment]
Perhaps adding a link to Github on the component page above the fold. 
One link could be an anchor to the section below "Browse components"
A second link could be "GCDS components in Github" or the "Github" link used in other parts of the website. <img width="1828" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGxOQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0331b7fc22b3f25c996d12f6910da1fc79fe80fd/Screenshot%202024-08-12%20at%2011.08.09%E2%80%AFAM.png" alt="Screenshot 2024-08-12 at 11.08.09 AM.png" />

**Comment by SmartMouthWords** [comment]
@MatildePerrusclet and I added some changes to components page overview. New text for component pages  when they have tags.

**Comment by SmartMouthWords** [comment]
@adorayi Proposing "required" to replace "core" as the tag name. What were you thinking for "experimental"?

**Comment by SmartMouthWords** [comment]
Changes needed: 

- [ ] Move the "Components tags" section below the list of components
- [ ] Move the sentence "We're sharing..." below the "Browse components" section
- [ ] Add Github and Figma links
- [ ] Change badge text
- [ ] Add description for required components to each component page with a required component

**Comment by SmartMouthWords** [comment]
Last week requested a developer publish the updates
 <img width="345" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM3NWQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--825babdcc516cd4d8ffcaf0c75fba5489d1af3c2/Screenshot%202024-10-01%20at%201.55.45%E2%80%AFPM.png" alt="Screenshot 2024-10-01 at 1.55.45 PM.png" />

**Comment by daine** [comment]
@SmartMouthWords do you know where I can find the description for required components? I'm hoping to find it so I can put it in each required component. Do you know a place where you think it should be too? TIA!

Here is the PR: https://github.com/cds-snc/gcds-docs/pull/429

**To test:**
- French components overview page: https://pr-429.d35vdwuoev573o.amplifyapp.com/fr/composants/
- English components overview page: https://pr-429.djtlis5vpn8jd.amplifyapp.com/en/components/

**Comment by SmartMouthWords** [comment]
<img width="1448" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKzhrQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a30d7a789c78d2e0c8dbeafbe433515ba0b38ccc/Screenshot%202024-10-04%20at%202.05.34%E2%80%AFPM.png" alt="Screenshot 2024-10-04 at 2.05.34 PM.png" />

"Le chemin de navigation est un composant obligatoire pour les pages Canada.ca."

**Comment by SmartMouthWords** [comment]
@daine I found mistake on the overview page. The description of required was still using the old term "core". Sorry for the oversight<img width="1788" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1FrQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f223c1bc8a12c70c085902293bc8c3ac7ebea06c/Screenshot%202024-10-04%20at%202.09.54%E2%80%AFPM.png" alt="Screenshot 2024-10-04 at 2.09.54 PM.png" />

**Comment by daine** [comment]
I added the required description text on all the required components. Please review if the french wording is correct, and recommend a fix if it's possible.

I also updated the text under "Component tags" from Core to Canada.ca required. Curious if we're switching it too in the french text.

**Comment by daine** [comment]
We are going to use "Requis sur Canada.ca" as per this comment
https://github.com/cds-snc/gcds-docs/pull/430#issuecomment-2417512006

**Comment by daine** [comment]
@SmartMouthWords I think this ticket is done. What are we doing about the original task that has this:
 - _Add a secondary button to the installation page in the next steps section_

**Comment by SmartMouthWords** [comment]
I'm not sure why we left that piece out. 

We don't use a button to get to Github anywhere else on the site. A link could be an option. @daine  Where is the best place to direct developers in GitHub once they've followed the installation instructions? And does step 3 still make sense in the last sentence? I wonder if the developer would have the project opened already if they'd just added the installation code.    

 <img width="1306" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMnRnQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2351d709d89f53f48a20b485e59af5b6a9301e85/Screenshot%202024-10-21%20at%204.49.51%E2%80%AFPM.png" alt="Screenshot 2024-10-21 at 4.49.51 PM.png" />

**Comment by daine** [comment]
@SmartMouthWords the [main components repo](https://github.com/cds-snc/gcds-components) should be the best place because it would accompany the context of browsing components. That being said though, when they click on "Browse components" here, it will take them to our components documentation page, which has the links to github and figma right at the top (as was done in this ticket). Would it be redundant to have it here too? If not, we can add a text link to accompany the Browse components button here.

**Comment by SmartMouthWords** [comment]
will look at installation page in that redesign
