### ISSUE TITLE
Review references to patterns and French translation of "Configuration"

### ISSUE THREAD

**Issue by adriannelee** [cds-snc/design-gc-conception#1005]
A francophone participant looking for instructions on installing GCDS thought the instructions were unavailable because the "Configuration" section of the homepage said that it was currently unavailable.

### Relevant research
[Developer onboarding 06/2024 - DoveTail](https://cds-snc.dovetail.com/data/6lWtplxKmem5m4vtWzJlU2#:v:h=2zdIJHUS0KdYkFhnToBono&s=1)

A new French term is required for "patterns". Previously "modèles" or "patrons" were used. Could one of these work? "Configurations" has other connotations and the meaning was unclear to research participants. 

Find suitable translations for references to patterns throughout the site. Replace the "pattern" section on the site homepage with "page templates" since patterns are not coming soon.
  
- [x] Consult linguistic services
- [x] Propose translations  
- [x] Document decision
- [x] Redesign "pattern" section on homepage to replace with "page templates" 
- [x] Visual design of image for page templates 
- [x] Publish fixes./changes

**Comment by adorayi** [comment]
Review guidance and FR Figma library for references that should be changed.

**Comment by SmartMouthWords** [comment]
Decision to be documented in the [French terms decision log](https://docs.google.com/document/d/1LDbkjLruh5GmZDAGY5eyC-dsYEAAykt8VcViabhw2ck/edit#heading=h.ci2ql2fjjb1m)

**Comment by SmartMouthWords** [comment]
Consulted @EliseKa who recommends "patron" and/or "patron réutilisable" instead of "configuration" as a translation for patterns. Discussed the issue with Chelsey from DTO and Pierre from Principal Publisher and they're both interested in aligning their translation to match whatever we land on.

**Comment by SmartMouthWords** [comment]
Instances of "pattern" on GC Design System site:
- "pattern language" on the [About page](https://design-system.alpha.canada.ca/en/about-us/)  
- "repeated patterns" on [Spacing Tokens](https://design-system.alpha.canada.ca/en/styles/spacing/) and the [Typography Tokens](https://design-system.alpha.canada.ca/en/styles/typography/) pages
- "pattern" on the [Get Involved page](https://design-system.alpha.canada.ca/en/get-involved/) and on the [homepage](https://design-system.alpha.canada.ca/en/)
<img width="1705" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM3ZmQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--75bf5cbbdaff8e34ad88f69ab9dfd9ec3bf7f8da/Screenshot%202024-07-15%20at%205.08.49%E2%80%AFPM.png" alt="Screenshot 2024-07-15 at 5.08.49 PM.png" />

**Comment by SmartMouthWords** [comment]
- Changed the landing page to replace patterns with templates. 
- No change required to the translations of pattern on the token page which references patterns in general, no UI/UX patterns
-  New French term for pattern is "blocs réutilisables". Replaced on [Get Involved page.](https://systeme-design.alpha.canada.ca/fr/simpliquer/)  
<img width="1988" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdy8xQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cf2084d7584a52faf642c2cb764478c903139d43/Screenshot%202024-07-19%20at%2010.33.11%E2%80%AFAM.png" alt="Screenshot 2024-07-19 at 10.33.11 AM.png" />

**Comment by SmartMouthWords** [comment]
Updates done, documented and pushed to production. @realdylanzheng agreed to design a page templates image that will need to be added the homepage when ready next week 🎉

**Comment by SmartMouthWords** [comment]
Received image/icon for template from @realdylanzheng  and @ethanWallace published today
