### ISSUE TITLE
'Contact Us' doesn't seem like it's for technical questions

### ISSUE THREAD

**Issue by adriannelee** [cds-snc/design-gc-conception#1007]
Because the contact us form mentions demos, it didn't seem like the right place to submit more technical questions for a developer.

<img width="719" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0tiQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7ddb91909870bbbb5f4009da7ab5a5a18e9d0c6e/image.png" alt="image.png" />

### Related research
[Developer onboarding 06/2024 - DoveTail](https://cds-snc.dovetail.com/insights/Contact-Us-doesn-t-seem-like-it-s-for-technical-questions-3WTZHL1Bhcwa2Ah1stwkOf)

- [x] Clarify form uses
- [x] Emphasize GitHub form and note benefits and need for account
- [x] Improve clarity of calls to action and user centricity of content
- [x] Review of French by linguistic services

**Comment by SmartMouthWords** [comment]
This was by design in the last update to address a business need. Right now the main channel for technical questions is GitHub. If there's a user need to have this channel available for tech questions, we can address.

**Comment by realdylanzheng** [comment]
@SmartMouthWords there is a GitHub link on the contact page, which arguably is perceived to be an equal contact platform as the form, what is the reason for not stating the purpose of GitHub as a platform for technical topics - since the purpose of form is clearly implied by the checkbox options? Thanks

**Comment by SmartMouthWords** [comment]
Updated EN and FR pages to address user feedback from testing and some of the feedback I received from Jeana around clearer calls to action and standardizing contact flows across Platform products: 
- Removed text not relevant to main task
- Adjusted some text to be user-centred
- Make GitHub support form more prominent and noted need for GitHub account 
- Clarified contact form is for feedback and support questions  

PR #[389](https://github.com/cds-snc/gcds-docs/pull/389)

**Comment by SmartMouthWords** [comment]
<img width="1141" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWIyQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c106c1af50b497d5323d8e7df6290d7ba355cfa0/Screenshot%202024-07-19%20at%202.34.07%E2%80%AFPM.png" alt="Screenshot 2024-07-19 at 2.34.07 PM.png" />
