### ISSUE TITLE
Website: Minor changes

### ISSUE THREAD

**Issue by adorayi** [cds-snc/design-gc-conception#1008]
From feedback received from the community, the following minor changes are proposed as they have minimal impact to the product:
1. Remove the "Welcome to your design system" section. 
2. Reword the installation option "I'm a lost designer..." to "Take me to the Figma Design Library"

**Comment by adorayi** [comment]
Need FR content @adorayi

**Comment by SmartMouthWords** [comment]
#1 is done: replaced offending text with "Start using GC Design System".  
<img width="1225" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBelAyQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--21ae42aea726f09cadc6256dbff23b2ff9297b74/Screenshot%202024-07-19%20at%202.48.10%E2%80%AFPM.png" alt="Screenshot 2024-07-19 at 2.48.10 PM.png" />

**Comment by adorayi** [comment]
@MatildePerrusclet please provide a translation for the phrase in #2 above Take me to the Figma Design Library"
