### ISSUE TITLE
Card: Update Code guidance for new version of card

### ISSUE THREAD

**Issue by ethanWallace** [cds-snc/design-gc-conception#1015]
**Summary:**
The code guidance of the `gcds-card` component needs to be updated to match the new properties of the newest version of the card.

- [x] Add new section about new/changed attributes
- [x] Translate new guidance
- [ ] Publish new guidance when new card component has been published

[Current card guidance document](https://docs.google.com/document/d/12ESkEF2pafMN-XoUWznvkOB2EyBxasOxvyVxTMZAZsY/edit?usp=sharing)

**Comment by melaniebmn** [comment]
Sent to translation on July 24th, 2024

**Comment by RavinaSamaroo** [comment]
Translation is complete and reviewed by Matilde. Ready to be published!

**Comment by melaniebmn** [comment]
@MatildePerrusclet Do you think you could take a look at the anatomy alt text description in EN and FR? The current alt text description we have is using the word "image" which ideally should be avoided and it also doesn't seem as descriptive as our other alt text descriptions.

**Comment by melaniebmn** [comment]
Update: The new guidance for the card update is good to go for the release next week. I will move the ticket to "Done" after the release is done.
