### ISSUE TITLE
Create breaking change release messaging for updated Card and Stepper components

### ISSUE THREAD

**Issue by adorayi** [cds-snc/design-gc-conception#1021]
As the card component is being updated with breaking changes, a release message to inform users will be required

## ✅ Definition of Done / Outcomes
- [x] Release messaging written and reviewed by engagement and devs
- [x] Message is reviewed by technical team
- [x] Message has been translated
- [x] Message has been sent out

## 📜  Acceptance criteria:

- [x] Message is drafted covering what is changing, why, and how it will affect users
- [x] Message is available in EN and FR
- [x] Messages have been sent

More info:
We're releasing [updates to the Card component (see Changes from V1 to V2)](https://docs.google.com/document/d/13y5OWeCeh8Ii85es_1OIw14yQyrgI1TiU1-x8WbLNBw/edit) which includes some breaking changes. We need to remind our users to use a pinned version if they do not have the capacity to implement the changes immediately.

**Comment by daine** [comment]
Work on this is on pause pending decision from @abdul regarding the changes on the Card and Stepper slots (giving users option to add HTML formatting but also potentially opening up the component to be misused)

**Comment by SmartMouthWords** [comment]
Reviewed the card and stepper message and proposed changes for plain language and to increase clarity. I've added the document to the Writer safelist and done a review using the tool. You can always re-rerun it if you make any more changes. Note: you need to accept suggestions/track changes for Writer to work properly.

**Comment by daine** [comment]
Meeting with Amy this week for a final review (as well brainstorming on creating a template for them) before sending these documents off for translation

**Comment by daine** [comment]
Amy approved the documents last Friday, I sent them to translation through the slack channel today.

**Comment by EliseKa** [comment]
Translation completed, documents shared in Slack channel and here: 
-[Card and Stepper breaking change messaging](https://docs.google.com/document/d/1p3eFHlWDeescZcCnMHioAT7M2oOtr3r7NQ-Nyl805ic/edit#heading=h.1fob9te)
-[React Canary release messaging](https://docs.google.com/document/d/1XoYWYF2XLs8bK0JIuQiVVu9Fk7Rrut-bERa_pmvCgHM/edit)

**Comment by daine** [comment]
The messages were sent through the mailing list on August 12th, this ticket can now be closed.
