### ISSUE TITLE
Incident Async Banner

### ISSUE THREAD

**Issue by ClementineHahn** [cds-snc/design-gc-conception#1023]
#Context
The incident was called out after a user flagged a different state between different touch point of the design system product for the banner component. 

We'll need to investigate how our delivery process led to this in order to not repeat this outcome to the best of our abilities

- Channel : incident-2024-07-03-async-figma-and-code-for-banner-component
- Incident documentation : https://docs.google.com/document/d/1IMlqRAraCMU6e_AziPKg2m6d71xadt67g04DIb77tF0/edit#heading=h.gjdgxs 

# Acceptance criteria
- [x] Complete the incident documentation with description of event, impact and chronology
- [x] Schedule and run a retro to understand the incident
- [x] Identify action item needed from the incident retro and add the needed on into the backlog
- [x] Close the incident

**Comment by adorayi** [comment]
Follow up with @adorayi and @ClementineHahn. Also consider new incident for side nav out of sync.

**Comment by ClementineHahn** [comment]
The banner component was removed from our we documentation. This is not an active incident anymore <img width="578" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeU9SQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--12b8386474db8fa52f2d8ccd43a182b733612bb5/Screenshot%202024-08-27%20at%208.09.34%E2%80%AFPM.png" alt="Screenshot 2024-08-27 at 8.09.34 PM.png" />
