### ISSUE TITLE
Update stepper guidance on documentation site

### ISSUE THREAD

**Issue by adorayi** [cds-snc/design-gc-conception#1025]
Update stepper guidance on documentation site to use the new guidance for the stepper v2.

**Comment by adorayi** [comment]
Duplicate

**Comment by melaniebmn** [comment]
@adorayi @RavinaSamaroo repurposing this ticket to keep track of the dev work for updating the stepper guidance on the documentation site.

**Comment by melaniebmn** [comment]
Flagging: The alt text for the new preview image was missing as it's not currently part of our guidance document.

**Comment by melaniebmn** [comment]
Update: The new guidance for the stepper update is good to go for the release next week. I will move the ticket to "Done" after the release is done.
