### ISSUE TITLE
Add error message to date input in Figma

### ISSUE THREAD

**Issue by RavinaSamaroo** [cds-snc/design-gc-conception#1040]
- [x] Add options for all [error states](https://www.figma.com/design/7HNtNYzWNmcxjYtG8UlnBz/Internal-assets?node-id=4507-5125&t=eHpl4LpS7z6VmuKY-0) - month not entered, year not entered, day not entered...
- [x] Update Day and Year inputs to use the updated input component (which has a longer width)
- [x] Translation of FR error states in internal assets
- [x] Set up [subcomponents](https://www.figma.com/design/7HNtNYzWNmcxjYtG8UlnBz/Internal-assets?node-id=4507-10913&t=eHpl4LpS7z6VmuKY-0) in internal assets file
- [x] Merge [branch](https://www.figma.com/design/mh2maMG2NBtk41k1O1UGHV/branch/66Br0pTTQDLUOUupcnXibf/GC-Design-System?node-id=14384-4734&t=YwF1NWqduj5b5elC-0) once reviewed by designers
- [x] Add FR subcomponents to internal assets file
- [x] Translation of FR subcomponent property names
- [x] Add error states to FR Figma file
- [x] Update EN poster
- [x] Content review of EN poster
- [x] Update FR poster
- [x] Translation of FR poster content

**Comment by RavinaSamaroo** [comment]
- [ ] Add options for all error states - month not entered, year not entered, day not entered

**Comment by RavinaSamaroo** [comment]
Waiting on @MatildePerrusclet for FR translation of error messages, and designers to review the branch before merging.

**Comment by adorayi** [comment]
Branch merged on EN, need to merge FR and work on posters.

**Comment by ClementineHahn** [comment]
remember to come back to ticket 18216 once solved as a user was checking on which version was the right on "error messaging".
Note that we still did not tell to this user which version (figma or code) was the right one to use

**Comment by adorayi** [comment]
@RavinaSamaroo can you now confirm that the Figma is the most up to date design of this so we can get back to the user that reported?

**Comment by adorayi** [comment]
The report we got was: "The error message treatment on the web page is different from the Figma component. Which is correct?"

**Comment by RavinaSamaroo** [comment]
@adorayi The Figma error message is the correct version - the code hasn't been updated yet.
