### ISSUE TITLE
Development: Basic page templates

### ISSUE THREAD

**Issue by adorayi** [cds-snc/design-gc-conception#1047]
# 📇 User story

As a GC Design System user I want to be able to see and download HTML templates for common basic page templates.

# 📜 Acceptance criteria
- [x] Prior to doing work, clarify scope of ticket with the designers and adjust if necessary
  - [x] Check with DTO if there are upcoming changes (ask designers)
  - [x] Check the figma design with the [current published template](https://design.canada.ca/coded-layout/generic-destination-basic.html)
- [x] Template has header
- [x] Template has footer
- [x] Version with a single column
- [x] Mobile variant of all versions
- [x] Page template receives a content review prior to publishing
- [x] Page templates receives a designer review prior to publishing

# ✅ Definition of Done / Outcomes
**Done when:**
- [x] EN template is merged and published
- [x] FR template is merged and published
- [ ] A publishing date and time is coordinated with Design
- [x] A template output consists of HTML files
- [x] Templates exist in the `gcds-examples/templates` folder
- [x] One file exists for each version of the template

 **Deliverables**

- [x] EN template 
- [x] FR template 

## Notes
- For the single column page we can start by calling it the "Basic content page" based on the [Basic content page layout recommended template](https://design.canada.ca/recommended-templates/generic-destination.html)
- ❓For the version with the side nav, there is currently no exact comparison found on the current [pattern library](https://design.canada.ca/pattern-library.html). Will need to coordinate with the team on a naming convention for this template. Upon discussion on dev/design sync on July 30th, this is still undecided if we're proceeding with a version that contains a side nav, so best to check with the design ticket #427

**Comment by daine** [comment]
Here is the working document on the proposed naming conventions for the standard page templates:
https://docs.google.com/document/d/1q4v397adKEHtWgDWUO3PG3jUl62D9RXMyThRASiHwEU/edit#heading=h.cp3wko3y7gcr

It also contains a mapping of existing templates from the source, to our proposed implementation.

**Comment by melaniebmn** [comment]
Templates are ready for release in [this PR](https://github.com/cds-snc/gcds-examples/pull/14).
