### ISSUE TITLE
Development: Update 'coming soon' cards with design

### ISSUE THREAD

**Issue by adorayi** [cds-snc/design-gc-conception#1048]
Can't use the card component on the 'Get involved' page anymore because we are removing the functionality to use cards without links.

Acceptance criteria:
Design should have a way to show the following information for coming soon items
- [x] item name
- [x] item description

Done when:
- [x] Coming soon page on the website is updated with new design that won't break card component v2

<img width="720" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVdQQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d3ab075f3cc689db5c09f13ee98eacdbd0c5a474/image.png" alt="image.png" />

**Comment by realdylanzheng** [comment]
@adorayi I think this ticket is meant for the dev implementation of the 'coming soon' solution. If so are @SmartMouthWords  and I the appropriate assignees?

**Comment by melaniebmn** [comment]
Translations are missing for the new content.

@MatildePerrusclet Do you think you could help with the translations? The new content is highlighted in pink in [this Figma file](https://www.figma.com/design/oAcr0FE65QkIZN1ae1ltbB/Playground-(internal)?node-id=161-935&t=8VmxOLYQqb0rAclZ-0). Thank you so much for your help!

**Comment by MatildePerrusclet** [comment]
Yes, as discussed I will get back to you by the end of the week. @melaniebmn

**Comment by melaniebmn** [comment]
Thank you @MatildePerrusclet !

**Comment by MatildePerrusclet** [comment]
Done @melaniebmn
