### ISSUE TITLE
Test decision flow

### ISSUE THREAD

**Issue by sarahhobson** [cds-snc/design-gc-conception#105]

**Comment by sarahhobson** [comment]
- [ ] Review documentation needs that were identified in last sprint
- [ ] Build some templates
- [ ] Test with one decision through an informal tabletop exercise 
- [ ] Retro the tabletop exercise to identify iterations for the following sprint

**Comment by sarahhobson** [comment]
Decision Flow 
[MIRO](https://miro.com/app/board/uXjVOe8CfTM=/) board

**Comment by sarahhobson** [comment]
Moving this to backlog until we have more progress on the prototype.

**Comment by ioanacontu** [comment]
Not in scope for MVP, we'll redefine this problem at a later date.
