### ISSUE TITLE
Create Vue starter app

### ISSUE THREAD

**Issue by ethanWallace** [cds-snc/design-gc-conception#1052]
A starter app in the Vue framework to allow developers a quick and easy start using the GC Design System in the Vue framework.

## Acceptance criteria:

- [x] Government of Canada branding (header/footer)
- [x] I18N (English/French)
- [x] Intro page
- [x] Report a bug page
- [x] Basic rendering end-to-end tests (app renders)

## Done when
- [x] English pages
- [x] French pages
- [x] Merged into `gcds-examples` repo under `starter-app` directory
- [x] e2e tests that verify the app has:
    - [x] Rendered
    - [x] Page navigation
- [x] All text have equivalents in french and english
  - [x] French
  - [x] English

**Comment by daine** [comment]
Did some prep work to visualize this while working on the vue starter app: https://miro.com/app/board/uXjVKsYgVU8=/?moveToWidget=3458764596479395624&cot=14

Didn't get to finish it today, but I was in the middle of adding the following pieces:
- i18n
- Removing state management (pinia) - no purpose for it
- Adding a report a bug page that will eventually submit to https://github.com/cds-snc/gcds-components/issues/new?assignees=&labels=&projects=&template=bug_report.yml&title=bug%3A+
  - adding parameters to that URL to prefill the data like:
    -  `&package_version=123`

**Comment by adorayi** [comment]
Code review still pending.
Requires content review and then translation + bilingual review.

**Comment by daine** [comment]
This should be good to go for translation and bilingual review.

Here is all the text that needs to be reviewed and have translation:
https://github.com/cds-snc/gcds-examples/blob/feat/vue-starter-app/starter-apps/vue/vue-template/src/i18n/en.js

Here is the french file (please note it needs a full review): https://github.com/cds-snc/gcds-examples/blob/feat/vue-starter-app/starter-apps/vue/vue-template/src/i18n/en.js


Here are the routing paths in English and french, which will need a review as well. They are the URLs that show on the browser address bar:
https://github.com/cds-snc/gcds-examples/pull/21/files#diff-3e884d1153e9232f30d2b52c0f84a7138454dd8473550b72a350a325b03f2825R9-R27

**Comment by daine** [comment]
Moving the content pieces into another ticket:
- [ ] Content review (English content)
- [ ] Bilingual review and french content
