### ISSUE TITLE
Content: Basic page template

### ISSUE THREAD

**Issue by SmartMouthWords** [cds-snc/design-gc-conception#1058]
Documentation of Basic page template guidance on GC Design System website.
Including use cases, how to use guidance, accessibility guidelines and more.

## Acceptance Criteria
The guidance:
- [x] outlines primary use cases 
- [x] specifies accessibility considerations
- [x] includes descriptive text for images and associated graphics

## Done when
- [x] Reviewed by designers
- [x] Reviewed by developers
- [x] Research and consulting other design libraries
- [x]  Check for consistency across the design system
- [x] Run Writer for plain language, style and inclusive language
- [x] Translation & Localization
- [x] Bilingual review by content design
- [x] Hand off for publishing

## Deliverables
- [x] EN guidance (Google Doc)
- [x] FR guidance (Google Doc)

## Dev impact
**Yes** - Needs to be added to the docsite

**Comment by SmartMouthWords** [comment]
Documentation of standard page template guidance on GC Design System website.
Including use cases, how to use guidance, accessibility guidelines and more.

Acceptance Criteria:

- [ ]  Template review
- [ ]  Sync with Design
- [ ]  Sync with Dev
- [ ]  Research and consulting other design libraries
- [ ]  Template ID (name, definition), use cases (when to use guidance), how to use and accessibility guidance
- [ ]  Descriptive text for images
- [ ]  Check for consistency across the design system
- [ ]  Run Writer for plain language, style and inclusive language
- [ ]  Translation & Localization
- [ ]  Bilingual review – content design
- [ ]  Hand off for publishing

**Comment by adorayi** [comment]
Is this ready for release?

**Comment by adorayi** [comment]
@SmartMouthWords has reviewed, back with @realdylanzheng for some small changes.

**Comment by ClementineHahn** [comment]
waiting for @realdylanzheng as @MatildePerrusclet did a last review

**Comment by SmartMouthWords** [comment]
@MatildePerrusclet
[Translation](https://docs.google.com/document/d/1nbUtOPg9gAp_vkXO0N4zkWItp148UsAWA-akEyP1Sx8/edit?tab=t.0) ready for review. Please send to @ethanWallace once ready. The image caption and alt text can come after if they'e not ready yet.

**Comment by SmartMouthWords** [comment]
@melaniebmn

**Comment by melaniebmn** [comment]
@daine adding you since you are working on those pages for the documentation site.

**Comment by daine** [comment]
I believe we can close this now @SmartMouthWords
