### ISSUE TITLE
Welcome Peter Crane

### ISSUE THREAD

**Issue by mcman12** [cds-snc/design-gc-conception#106]
- [ ] Schedule an AMA style introduction with the team
- [ ] Walkthrough product overview
- [ ] Get new member permissions to tools (github, figma, miro, gdrive (cds), notion, calendars, Slack)
- [ ] Walkthrough sprint rituals and team commitments
- [ ] Walkthrough development work to date
- [ ] Walkthrough Policy implication of the project
- [ ] Walkthrough research to date
- [ ] Organize discipline and pod related discussions
- [ ] Review Onboarding with new member

**Comment by ioanacontu** [comment]
I added Peter to Figma.

**Comment by ioanacontu** [comment]
Laura is giving him to review research documents. + David P's documents.
