### ISSUE TITLE
Develop alt text guidance for images on DS website

### ISSUE THREAD

**Issue by SmartMouthWords** [cds-snc/design-gc-conception#1077]
- [x] Produce guidance for writing alt text for site
- [x] Update template
- [x] Provide examples

**Comment by SmartMouthWords** [comment]
Guidance on alt text added to the [alt text spreadsheet](https://docs.google.com/spreadsheets/d/1FHBEau_Bep6C_FU2Duf58MbDUlY6v_5Bjm9kEGSplaA/edit?pli=1&gid=174021791#gid=174021791).

**Comment by MatildePerrusclet** [comment]
Guidance for writing alt text is available in the [spreadsheet under the tab "Guidance for writing alt text".](https://docs.google.com/spreadsheets/d/1FHBEau_Bep6C_FU2Duf58MbDUlY6v_5Bjm9kEGSplaA/edit?usp=sharing) 
[Component documentation template](https://docs.google.com/document/d/1smhU6CKWwQCmSnYWcRtNltYPlwASilt4lJxaLiJ_Pyo/edit?usp=sharing) will be updated accordingly. We are looking at adding [content string patterns](https://www.youtube.com/watch?v=jsqsnFjtywE) to standardize alt text.
