### ISSUE TITLE
Update font weight for required label

### ISSUE THREAD

**Issue by melaniebmn** [cds-snc/design-gc-conception#1082]
**Summary:** 
Required form labels are currently using a bold font-weight when they should be using a regular font-weight.

**Acceptance Criteria:**
- [x] Update coded form labels to use the regular font-weight for "required"
- [x] Code review
- [x] Push to prod

**Comment by melaniebmn** [comment]
The fix for this was added in [this PR](https://github.com/cds-snc/gcds-components/pull/608).

**Comment by melaniebmn** [comment]
The issue was fixed in release `0.24.1`.

**Comment by adorayi** [comment]
I was expecting the contact us form to reflect this change @melaniebmn

**Comment by melaniebmn** [comment]
Can you check again, please @adorayi? This should be fixed!
