### ISSUE TITLE
Latest dist tags for react ssr npm package

### ISSUE THREAD

**Issue by daine** [cds-snc/design-gc-conception#1084]
## 📇 User story
As a developer, I want to download the latest (although canary) version of the react-ssr package, so that I don't install an older version.

## ✅ Definition of Done / Outcomes
- [x] When a user installs the package, they should get the last published package

## 📜 Acceptance criteria
- [ ] The package should be clearly marked as canary
- [ ] The last published version should be the latest version available for download

## 📝 More info
When you see the versions published:
https://www.npmjs.com/package/@cdssnc/gcds-components-react-ssr?activeTab=versions

Even though we don't tag as latest, [we only use the canary tag](https://github.com/cds-snc/gcds-components/blob/main/.github/workflows/compile-and-publish.yml#L150-L156), the first ever published package was still tagged as `latest` so when you go to the main page, it shows the first version published as the latest version.

Considerations:
- Potentially remove the `latest` tag using `npm dist-tag rm <pkg> latest`
- Add the `latest` tag to all packages, so they will have _two_ tags, `latest` and `canary`. They will still have the `-canary.x` id appended to their version so it's still clear that it's a canary release although it's the latest dist.

**Comment by ethanWallace** [comment]
Tried to do a manual publish of `v0.25.0-canary.0` as latest but was denied.

The best approach may be to release later version with the latest tag since we are wanting the release to act like a latest release. Will discuss more with @daine when she is back.
