### ISSUE TITLE
Align labels in Figma

### ISSUE THREAD

**Issue by RavinaSamaroo** [cds-snc/design-gc-conception#1086]
We have 2 different label styles - one in internal assets and one in the main library. They are different sizes and fonts. The internal assets version (medium font) is used for radios, checks, and date input. The main library version (bold font) is used for select and input. 

- [x] Add the bold label as a new subcomponent to internal assets and remove from main library
- [x] Add the medium font label to the new 'label' page in internal assets
- [x] Update components using bold font label to use the new component (input and select)
- [x] Update components using medium font label to use the new component (radios, checkboxes, and date input)
- [x] Repeat process for FR library

**Comment by adorayi** [comment]
Note: check in with translations if this is done. @RavinaSamaroo to check what the status.
