### ISSUE TITLE
Design: Heading to align with coded heading

### ISSUE THREAD

**Issue by realdylanzheng** [cds-snc/design-gc-conception#1094]
The coded Heading has margin-top and margin-bottom values which the Figma component does not have. Add spacing to Figma Headings to mimic margins so they appear consistent with coded outputs. 

## Acceptance criteria
- [x] All heading levels must have margin-bottom: **400** 
- [x] `h1` must have margin-top: **0**
- [x] `h2`-`h3` must have margin-top: **500**
- [x] Heading must have boolean property: **Vertical margins?**
- [x] Poster to recommend space component for margin values outside of the default
- [x] Updates are done in EN and in FR library

## Done when
- [x] Reviewed by designers
- [x] Reviewed by developers
- [x] EN component is merged and published
- [x] FR component is merged and published
- [x] Poster content design review
- [x] Poster translations
- [x] EN poster merged and published 
- [x] FR poster merged and published

## Deliverables
- [x] EN component in Figma
- [x] FR component in Figma
- [x] EN poster in Figma
- [x] FR postert in Figma

## Dev impact
**None**

**Comment by nmakuch** [comment]
EN updates in branch for review:
https://www.figma.com/design/mh2maMG2NBtk41k1O1UGHV/branch/omJPAgCAbhtOrk6hVH3zi1/GC-Design-System?node-id=9439-684&node-type=FRAME&t=yCdsQLXrViMXPwAG-0

**Comment by nmakuch** [comment]
FR updates in branch for review:
https://www.figma.com/design/o4SguSZdar2CCFzSkWNrmB/branch/qPi2DnQiMXDTY955DnMqz3/Syst%C3%A8me-de-design-GC?node-id=121-15628&node-type=FRAME&t=ImVDu8s57JyJSIwK-0
