### ISSUE TITLE
Design: Text to align with coded Text

### ISSUE THREAD

**Issue by adorayi** [cds-snc/design-gc-conception#1098]
The coded Heading has margin-top and margin-bottom values which the Figma component does not have. Add spacing to Figma Headings to mimic margins so they appear consistent with coded outputs. 

## Acceptance criteria
- [x] All variants should have margin-bottom: **400** 
- [x] Text component must have boolean property: **Vertical margins?**
- [x] Poster to recommend space component for margin values outside of the default
- [x] Work done in EN and in FR

## Done when
- [x] Reviewed by designers
- [x] Reviewed by developers
- [x] EN component is merged and published
- [x] FR component is merged and published
- [x] Poster content design review
- [x] Poster translations 
- [x] EN poster merged and published 
- [x] FR poster merged and published

## Deliverables
- [x] EN component in Figma
- [x] FR component in Figma
- [x] EN poster in Figma
- [x] FR postert in Figma

## Dev impact
**None**

**Comment by nmakuch** [comment]
EN updates in branch for review:
https://www.figma.com/design/mh2maMG2NBtk41k1O1UGHV/branch/omJPAgCAbhtOrk6hVH3zi1/GC-Design-System?node-id=10053-348&node-type=CANVAS&t=yCdsQLXrViMXPwAG-0

**Comment by nmakuch** [comment]
FR updates in branch for review:
https://www.figma.com/design/o4SguSZdar2CCFzSkWNrmB/branch/qPi2DnQiMXDTY955DnMqz3/Syst%C3%A8me-de-design-GC?node-id=114-3353&node-type=CANVAS&t=ImVDu8s57JyJSIwK-0

**Comment by adorayi** [comment]
Figma updates done, poster work in EN done and awaiting review, translation to be started.
