### ISSUE TITLE
Footer fixes, headings are not using font lato

### ISSUE THREAD

**Issue by adorayi** [cds-snc/design-gc-conception#1110]
1. Not using font lato (Headings should be bold Lato)

## ✅ Definition of Done / Outcomes
Bug fix and align with canada.ca

## 📜 Acceptance criteria
_Add here the list of assumed steps that will be needed to complete the task_
- [x] Update tokens in Figma
- [x] Update tokens in code
- [x] Update the website

**Comment by adorayi** [comment]
Before closing, confirm on the design side (Figma).

**Comment by RavinaSamaroo** [comment]
@adorayi This work was not done on the design side. Not sure why the ticket was closed.

**Comment by nmakuch** [comment]
Updated Internal assets subcomponents:
https://www.figma.com/design/mh2maMG2NBtk41k1O1UGHV/GC-Design-System?node-id=1802-4983&node-type=canvas&t=arKw5V6HTdrFUDRk-0

**Comment by nmakuch** [comment]
English Master Component:
https://www.figma.com/design/mh2maMG2NBtk41k1O1UGHV/GC-Design-System?node-id=1802-4983&node-type=canvas&t=arKw5V6HTdrFUDRk-0

**Comment by nmakuch** [comment]
French Master Component:
https://www.figma.com/design/o4SguSZdar2CCFzSkWNrmB/Syst%C3%A8me-de-design-GC?node-id=114-2996&node-type=canvas&t=9vSIDXVC8yLJGSZS-0

**Comment by adorayi** [comment]
@daine @melaniebmn please review the links above match what is in the code

**Comment by melaniebmn** [comment]
@nmakuch had a look and tagged you in 3 comments where it looked like the subcomponent heading wasn't using the bold font-weight.
