### ISSUE TITLE
Footer fixes, update website images

### ISSUE THREAD

**Issue by adorayi** [cds-snc/design-gc-conception#1116]
Context : Bug identified by the design team Ravina and Nick 

On the footer component page on the documentation website, all the images show the bottom links with a line. New images are needed to replace the exiting ones.

- [x] Identify discrepancies
- [x] Create updated images
- [x] Apply updated images on docs repo

<img width="1482" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNW1nQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--23dc1622e5b8e05f0348b5a533f824ec8734184a/image.png" alt="image.png" />

**Comment by RavinaSamaroo** [comment]
Noted another discrepancy with the heading in the footer image - need insight from @SmartMouthWords https://www.figma.com/design/7HNtNYzWNmcxjYtG8UlnBz/Internal-assets?node-id=257-9380&node-type=canvas&t=sXOw3nVUCy0kwI7z-0

**Comment by ClementineHahn** [comment]
@nmakuch  and @RavinaSamaroo to align during dev design sync on this, should this include also date modified or not and have DTO in the loop . So ticket to be groomed.

**Comment by nmakuch** [comment]
Anatomy and footer preview images
https://drive.google.com/drive/folders/14VxBktPsd7sqBBydVrWwUBf5trlPfcIp

**Comment by adorayi** [comment]
Please review this together with ticket 1110 (https://app.zenhub.com/workspaces/design-system-6100624a19f4cf000e46e458/issues/gh/cds-snc/design-gc-conception/1110)

**Comment by nmakuch** [comment]
@adorayi would you want me to update the anatomy images on the doc site as part of this? I don't mind

**Comment by adorayi** [comment]
Yes please @nmakuch

**Comment by nmakuch** [comment]
Pull request:
https://github.com/cds-snc/gcds-docs/pull/437

**Comment by nmakuch** [comment]
Reviewed and merged
