### ISSUE TITLE
Figma alignment(dev): Remove focus colour from coded form component labels

### ISSUE THREAD

**Issue by adorayi** [cds-snc/design-gc-conception#1118]
## ✅ Definition of Done / Outcomes
To align with the design specs in Figma, remove the focus colour from form component labels when a component is focused. Form component labels/legends should no longer change to the focus colour.

## 📜 Acceptance criteria
- [x] Form components with a label/legend no longer change the colour of their label/legend on focus
- [x] Tokens package has been updated and published to remove unused tokens
- [x] Dev review
- [x] Merge
- [x] Release

**Comment by ClementineHahn** [comment]
Needs review but ready to be done

**Comment by daine** [comment]
PR approved, waiting for merge and release
https://github.com/cds-snc/gcds-components/pull/678

**Comment by daine** [comment]
Released with [v0.27.0](https://github.com/cds-snc/gcds-components/releases/tag/gcds-components-v0.27.0)
