### ISSUE TITLE
Publish: Date input component

### ISSUE THREAD

**Issue by adorayi** [cds-snc/design-gc-conception#1137]
## 📇 User story
Publish the pieces needed for Date input component

## ✅ Definition of Done / Outcomes
- [x] Done when design has merged the  Date input component in figma
- [x] Done when development has merged the Date input PR in github
- [x] Website has been updated with documentation

## 📜 Acceptance criteria
- [x] Design ticket is finalized and ready for merge
- [x] Develop ticket is finalized and ready for merge [#698 ]
  - https://github.com/cds-snc/gcds-components/pull/607

## 📝 More info
This ticket only tracks the complete of this specific template.

**Comment by daine** [comment]
Changed the estimate to a 2 because there's no ticket for the new pages on the website (this is currently the ticket to update the website).

**Comment by daine** [comment]
Hi - here is the PR for the website code changes. Would appreciate a final review from design and translation @RavinaSamaroo @MatildePerrusclet TIA!
French URL - https://pr-420.d35vdwuoev573o.amplifyapp.com
English URL - https://pr-420.djtlis5vpn8jd.amplifyapp.com

**Comment by ClementineHahn** [comment]
@daine Update PR with latest content today + last round of review and looking to publish soon, by end of sprint for sure.

**Comment by RavinaSamaroo** [comment]
New anatomy text proposed by Matilde is more descriptive, but is misaligned from the anatomy text used in similar components, like the input field. I've asked @SmartMouthWords to review and provide a decision on if we move forard with the new text or keep the old text. https://www.figma.com/design/7HNtNYzWNmcxjYtG8UlnBz/Internal-assets?node-id=1925-9533&node-type=symbol&t=wVdSaIOWBCNSxwlU-0

**Comment by daine** [comment]
I have updated the PR with the new text and images. Here is the PR with detailed description & links to preview the changes: https://github.com/cds-snc/gcds-docs/pull/420

A few little things I've found that I've made changes on:
- In french, under "Composants connexes", I've commonly seen the pattern `<component name> : <description>`. An example is the input/champ de saise component having this: "Sélecteur de date : lorsque vous". For consistency, I applied the same pattern on the PR, even thought the google doc doesn't have the " : ".
- Under "Composants connexes", we mention "Sélecteur de date", but I have compared the english version in both Date Input and the regular Input components and we have two names for this in english: "Date picker" (found in Date input) and "Date selectors" (found in Input). I've left this as-is and I've followed the content in the document instead. Just flagging this if this is an inconsistency or not.
- In both english and french, most of our pages have this text:
  - Design and accessibility for `<component name>` | Accessibilité et design des `<component name>`

**Comment by daine** [comment]
Thanks for confirming Matilde! I've updated the PR with changes to add the following: 

**Other comments**
- Period is missing on the component overview page (EN and FR)
  _- “Other names: dates, dateinput, date, memorable date[PERIOD]_
- Period is missing on the date input page EN
  _- Also called: dates, dateinput, date, memorable date [PERIOD]_

In regards to the partials - I think it's best to have a separate ticket for it. It does appear on all our other components as well, so it's not just date input that's currently affected by it. Good catch!
