### ISSUE TITLE
Development - Setup automation workflow and hosting of fable test app

### ISSUE THREAD

**Issue by ethanWallace** [cds-snc/design-gc-conception#1140]
# Summary

Setup a GitHub workflow that allows automated publishing of new changes to fable test app to GitHub pages.

## Acceptance criteria

- [x] ~Setup Github branch `gh-pages`~
- [x] ~Configure repo to host app~
- [x] ~Create workflow to push new changes to `gh-pages` branch~
- [x] Hide app from search crawlers
- [x] Setup amplify app for fable testing
- [x] Cleanup and revert previous changes made when we were hoping to host it on github pages
- [x] Delete github publishing workflow
- [x] Delete github branch `gh-pages`

## Done when
- [x] Merged into main
- [x] Fable test app is live with a URL (on AWS amplify)

**Comment by daine** [comment]
Hosting it on github didn't work as well as we were hoping, so we've decided to host it on AWS amplify instead.
PRs were created to:
- [add the new app to amplify](https://github.com/cds-snc/gcds-terraform/pull/69)
- [change the name of the subdomain to reflect its purpose](https://github.com/cds-snc/gcds-terraform/pull/70)


The app is accessible through this URL: https://fable-test.d2fzvkr34ak02t.amplifyapp.com/
