### ISSUE TITLE
Dev: Details component + Link component Figma fixes

### ISSUE THREAD

**Issue by adorayi** [cds-snc/design-gc-conception#1147]
## 📇 User story
- As a GCDS Components developer, I want to have the coded components for Link and Details aligned with their corresponding designs in figma

## ✅ Definition of Done / Outcomes
- [x] Done when PR is opened and approved
- [x] Done when PR is determined to be in the next release, in which it gets merged to main
- [x] **Do not release** the package, releasing will be done on ticket #1172

## 📜 Acceptance criteria
- [x] ~~Link: Mobile Link font token is set to 16px, 150% line height~~
- [x] Mobile link size: `textMobile`
- [x] Link: Spacing between text and icon on desktop is increased from 3px to 6px
- [x] Link: [Figma file](https://www.figma.com/design/mh2maMG2NBtk41k1O1UGHV/GC-Design-System?node-id=2646-8407&node-type=canvas&t=XJhXIXLOzn5ueai7-0)
- [x] ~~Details: Mobile Link font token is set to 16px, 150% line height~~
- [x] Details mobile link size: `textMobile`
- [x] Details: Spacing matches design
- [x] Details: [Figma file](https://www.figma.com/design/mh2maMG2NBtk41k1O1UGHV/branch/pSMepnlmvLjAcwFk16JkpN/GC-Design-System?node-id=8000-362812&node-type=frame&t=7LwnoB313Q4OX4Hd-0)

**Comment by ClementineHahn** [comment]
Might need designer review after

**Comment by daine** [comment]
Released [v0.27.0](https://github.com/cds-snc/gcds-components/releases/tag/gcds-components-v0.27.0)
