### ISSUE TITLE
Evaluate alignment of typography

### ISSUE THREAD

**Issue by realdylanzheng** [cds-snc/design-gc-conception#1155]
Evaluate alignment of GC Design System typography styles with DTO's typography guidance.

## Definition of done

- [x] Identify and document differences between the two typography systems
- [x] Outline potential risks of misalignment
- [x] Provide options for alignment

## Deliverables

- [x] [Preliminary type scale evaluation](https://docs.google.com/document/d/1OC2Py-iFvsNt2ySWQ4rf2nPgv-XLJx95QTYO8EQOQNI/edit?usp=sharing)
- [x] [Current typography requirements](https://docs.google.com/document/d/1Nx6zuTk3kLzCxIrG-WxppiMpq5INdIKaErW6JSz4wFk/edit?tab=t.uiaodq21czti) (presented to DTO)
- [x] [Proposed typography](https://docs.google.com/document/d/1Nx6zuTk3kLzCxIrG-WxppiMpq5INdIKaErW6JSz4wFk/edit?tab=t.g7jbynah0ooz)
- [x] [Mock ups using proposed typography on Topic and Basic pages](https://www.figma.com/proto/4wF8Kr9o2sGTQjaOpY7qcZ/Component-archive-%2B-decision-record?node-id=2518-6544&node-type=frame&t=6Gb8i8XOy7zisya5-1&scaling=min-zoom&content-scaling=fixed&page-id=2333%3A4922&starting-point-node-id=2441%3A40715)

**Comment by ClementineHahn** [comment]
Meeting today will help progress on this discussion, we dont foresee decision yet as we need some time to discuss with team after

**Comment by ClementineHahn** [comment]
@realdylanzheng continue to work on this per decisions made after the DTO / GCDS sync . @adorayi link to be added here
