### ISSUE TITLE
Update Get involved with new components

### ISSUE THREAD

**Issue by adorayi** [cds-snc/design-gc-conception#1162]
## 📇 User story
Given components mentioned on the get involved page are complete or almost complete, we should start making updates to reflect the next items in progress

## ✅ Definition of Done / Outcomes
Done when the page is updated in EN and FR to display new and correct information
- [x] Notice component
- [x] Topic page template
- [x] Ministerial page template
- [x] VueJS starter app template

## 📜 Acceptance criteria
_Add here the list of assumed steps that will be needed to complete the task_
- [x] Updated EN page
- [x] Updated FR page

## 📝 More info
We should plan to update this page every end of quarter, along with the Github contributions page as well.

**. 🚫 Out of scope**
_ If possible, give precisions on what is *not* part of this work_

**Comment by brockhigg10** [comment]
Content developed in English - https://docs.google.com/document/d/158h4o7vVBFox7xyP1pp0meBWVdbSYlEsos578iJQy8g/edit?usp=sharing.  Sent to translation.

**Comment by ClementineHahn** [comment]
All published and done
