### ISSUE TITLE
GCDS Q2 Product update presentation

### ISSUE THREAD

**Issue by adorayi** [cds-snc/design-gc-conception#1174]
## 📇 User story
_Add here context on why we have to work on that_
As a PM, I want to create and share the work done for the Q2 quarter, in order to show progress, gain trust and show accountability towards our committed goals and OKRs.

## ✅ Definition of Done / Outcomes
- [x] A presentation in EN
- [x] A presentation in FR

## 📜 Acceptance criteria
_Add here the list of assumed steps that will be needed to complete the task_
- [x] Check in on status of work done
- [x] Prepare presentation with evidence of work
- [x] Translation
- [x] Demo to GCWP
- [ ] Demo at Platform Townhall

**Comment by adorayi** [comment]
Slides in EN are done [here](https://docs.google.com/presentation/d/1hnDQkBguR4SrHj1pl4fxqDChZEUufJQL3FTW1SS5gac/edit#slide=id.g2bcac7083ba_0_5892)
@EliseKa  Need a translation please.

**Comment by EliseKa** [comment]
@adorayi Translation complete - [slides in FR](https://docs.google.com/presentation/d/1ndYsQJitoqQv7U6B1u1Ckra2TS_9KprvbeOT3mbJHwc/edit#slide=id.p1)
