### ISSUE TITLE
Design issue: Discrepancy with font color token selection in poster 

### ISSUE THREAD

**Issue by adorayi** [cds-snc/design-gc-conception#1179]
Support issue:
See images, 2 different font colors and client is asking if this is an error.
<img width="1550" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXdLQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ed94cd6f832d2a3100604353799c846603ca0670/image%20%287%29.png" alt="image (7).png" />

<img width="1143" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTBLQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7afd2428d7ebd78ee8d0e3d40d6e28d07fdabff1/image%20%286%29.png" alt="image (6).png" />

**Comment by realdylanzheng** [comment]
This is an error, poster was incorrect. Now fixed.
