### ISSUE TITLE
Dev documentation fix: mainContainer should be main-container on Container

### ISSUE THREAD

**Issue by daine** [cds-snc/design-gc-conception#1184]
## 📇 User story
_Add here context on why we have to work on that_
As a developer, I want to see consistent documentation on the Container component so that I can understand how to use it effectively.

## ✅ Definition of Done / Outcomes
- [x] Done when storybook event and properties page has been updated to say `main-container` instead of `mainContainer`

## 📜 Acceptance criteria
- [x] The website documentation is shows kebab case `main-container` on https://design-system.alpha.canada.ca/en/components/container/code/

## 📝 More info
Do we need design updates on the container component or is it named correctly there?

This issue was raised by a user through our contact us feedback form. [Freshdesk ticket](https://cds-snc.freshdesk.com/a/tickets/19253)

**Comment by jprince-cds** [comment]
Please let the support team know once completed to circle back with [Freshdesk #19253](https://cds-snc.freshdesk.com/a/tickets/19253). Thanks!
