### ISSUE TITLE
Dev: Component updates for new typography and spacing

### ISSUE THREAD

**Issue by melaniebmn** [cds-snc/design-gc-conception#1277]
## 📇 Summary
Update component tokens to address the following issues caused by the new typography and spacing:

## 📜 Acceptance criteria
- [x] Updates have been tested
- [x] Updates have been reviewed by at least 1 designer
- [x] Updates have been reviewed by at least 1 developer 

## ✅ Definition of Done / Outcomes
Button
- [x] Reduce increased button height  (reduce vertical padding)
- [x] Change line-height to 140%

Card
- [x] Either badge height needs to be reduced or the spacing between the badge and the image needs to be increased

Checkbox
- [x] Checkmark alignment is slightly off

Container
- [x] Default spacing needs to be adjusted in example (dev: Storybook, design: Figma)
- [x] Margin + padding props need to be updated to include new spacing values

Date input
- [x] Input height needs to be reduced (reduce vertical padding)

Details
- [x] Details summary is misaligned with arrow

File uploader
- [x] Reduce height for "Choose file" btn + upload file box  (reduce vertical padding)

Heading
- [x] Margin-top + bottom props need to be updated to include new spacing values
- [x] Adjust default values for margin-top + bottom to match new spacing tokens
- [x] Update Storybook story to include new margin spacing values

Icon
- [x] Margin-left + right props need to be updated to include new spacing values
- [x] Update Storybook story to include new margin spacing values

Input
- [x] Reduce increased height  (reduce vertical padding)

Nav link
- [x] Reduce increased height  (reduce vertical padding)

Nav group
- [x] Reduce increased height  (reduce vertical padding)

Notice
- [x] Title alignment with icon needs to be fixed

Pagination
- [x] Prev/next links don't align with page links (adjust vertical padding for both to match)

Radio
- [x] Checked radio btn isn't centered (adjust alignment)

Search
- [x] Reduce increased height  (reduce vertical padding)

Select
- [x] Reduce increased height for dropdown  (reduce vertical padding)

Text
- [x] Margin-top + bottom props need to be updated to include new spacing values
- [x] Adjust default values for margin-top + bottom to match new spacing tokens
- [x] Update Storybook story to include new margin spacing values

Textarea
- [x] Reduce increased height  (reduce vertical padding)

Topic menu
- [x] Reduce increased height for links  (reduce vertical padding)
- [x] Fix background colour on dropdown content

- [x] Done when the components package has been updated with a PR that is approved
- [x] Done when the components package has been merged and released

##  Related tickets
- #1272

**Comment by daine** [comment]
Updates will need to be tested, which can happen when we update our documentation website

**Comment by daine** [comment]
This is done, and has been released.
