### ISSUE TITLE
Release messaging: Typography and spacing

### ISSUE THREAD

**Issue by daine** [cds-snc/design-gc-conception#1279]
## 📇 Summary

This is part 2 of the work on release comms. This ticket is specifically for the work items needed for the release messaging on Typography.

As part of the typography and spacing changes, we need communication to inform our users on what to expect and how it potentially impacts them.

## 📜 Acceptance criteria
- [x] Message mentions the impact to developers
  - [x] There is information for people using components
  - [x] There is information for people using margin and padding properties on components (Heading, Text, Container)
  - [x] There is information for people using margin and padding properties on the Icon component
- [x] Message mentions the impact to designers
- [x] Message is clear and easy to understand
- [x] Message has been reviewed by a designer
- [x] Message has been reviewed by a developer
- [ ] Support team has been given advance notice 
- [ ] Message was proofread and Writer was run   
- [x] Sent to latest mailing list subscribers

## ✅ Definition of Done / Outcomes
- [x] Done when there is a breaking change release messaging to be sent through the mailing list
  - [x] Message in EN
  - [x] Message in FR
- [x] Done when there is a detailed release notes and CHANGELOG
  - [x] Message in EN
  - [x] Message in FR
  - [x] Informs what a user needs to do if they use `gcds-tokens` directly
  - [x] Informs what a user needs to do if they use `gcds-utility` with affected classes
  - [x] Informs what a user needs to do if they use `gcds-components` Heading, Text, Container properties for setting margins and paddings
  - [x] Informs what a user needs to do if they are using the Icon component, and if they are setting the margin and padding properties
- [x] Done when we have identified where to put the information for designers
- [x] Done when message is sent out through the mailing list
- [x] Check through Notify dashboard message was sent

**Comment by daine** [comment]
The release drafts are located here:
https://docs.google.com/document/d/1YC3O3Z5lHd79wCqJmB4OvC6zZeexOViT-hCtmVORGgM/edit?tab=t.0

**Comment by SmartMouthWords** [comment]
Release email sent to translation yesterday. They should have done the morning of the release.

**Comment by ClementineHahn** [comment]
change logs still being updated in FR with @SmartMouthWords  review , waiting for that to be checked by @daine to publish changelog

**Comment by ClementineHahn** [comment]
Creating duplicate of this to capture where release messaging needs also to be sent slack and figma @SmartMouthWords

**Comment by ClementineHahn** [comment]
Release coms email about to be sent by @SmartMouthWords once finalization of change logs with @daine

**Comment by daine** [comment]
I believe we can close this now, the release messaging email was sent to the mailing list yesterday
