### ISSUE TITLE
Dev - component spacing updates 

### ISSUE THREAD

**Issue by RavinaSamaroo** [cds-snc/design-gc-conception#1281]
1. **[Breadcrumbs](https://www.figma.com/design/mh2maMG2NBtk41k1O1UGHV/branch/LTltmBor2VVv8MMpfhm2U6/GC-Design-System?node-id=7628-1934&node-type=frame&t=8HgGUF1poPGJyfDW-0)**
- [x] Spacing between icon and link from 9px to 10px

2. **[Card](https://www.figma.com/design/mh2maMG2NBtk41k1O1UGHV/GC-Design-System?node-id=40573-956&node-type=frame&t=Iw6X6NKuKOqacZAM-0)**
Use new small text for badge
- [x] 18px bold, 28px line height on desktop
- [x] 16px bold, 24px line height on mobile

Padding on top and bottom of badge:
- [x] 0px on desktop
- [x] 2px on mobile
- [x] Space between title and description from 9 to 10px

3. **[Buttons](https://www.figma.com/design/mh2maMG2NBtk41k1O1UGHV/branch/OPMe9xHljUSgMuwy8CWOa9/GC-Design-System?node-id=7795-7785&node-type=frame&t=L9T7U9Qt5mls6ubV-0)**

- [x] use 140% for line height 
- [x] --gcds-button-padding: 0.625rem; 

4. **[Details](https://www.figma.com/design/mh2maMG2NBtk41k1O1UGHV/branch/pSMepnlmvLjAcwFk16JkpN/GC-Design-System?node-id=8000-362812&node-type=frame&t=awv3w0oRuvhsIHEo-0)**

- [x] change icon size from 18x15px to 18x16px

5. Checkbox

- [x] --gcds-checkbox-padding: 0.5rem 

6. Error Message

- [x] For error message change mr-100 on icon to mr-50

7. File uploader

- [x] --gcds-file-uploader-font: 400 1.25rem/140% 'Noto Sans', sans-serif;
- [x] --gcds-button-padding: 0.625rem;
 
8. Footer

- [x] --gcds-footer-listitem-margin: 0 0 0.625rem;

9. Input

- [x] --gcds-input-padding: 0.5rem;

10. Label 

- [x]  --gcds-label-margin: 0 0 0.125rem;

11. Nav Group

- [x] --gcds-nav-group-trigger-padding: 0.625rem;
- [x] --gcds-nav-group-top-nav-trigger-padding: 0.875rem;

12. Nav Link

- [x]  --gcds-nav-link-side-nav-padding: 0.625rem 0.5rem;
- [x]  --gcds-nav-link-top-nav-padding: 0.875rem;

13. Side nav

- [x]  --gcds-side-nav-heading-padding: 0.625rem;

14. Pagination

- [x] --gcds-pagination-list-end-button-padding: 0.625rem 0.5rem; _**( changed to: --gcds-pagination-list-end-button-padding: 0.5rem; )**_
- [x] list items with page numbers should have a width and height of 3rem or 48px (dimensions should be 48x48)

15. Radios
- [x] --gcds-radio-padding: 0.5rem

16. Search
- [x] --gcds-button-padding: 0.625rem; _**( changed to: --gcds-button-padding: 0.5rem; )**_
- [x] --gcds-button-font: 500 1.25rem/140% 'Noto Sans', sans-serif

17. Select
- [x] --gcds-select-padding: 0.5rem 3.75rem 0.5rem 0.5rem;

18. Textarea
- [x] --gcds-textarea-padding: 0.5rem;

19. Error message
- [x] Change margin-bottom to: 0.5rem;

20. Hint
- [x] --gcds-hint-margin: 0 0 0.5rem;

**Comment by nmakuch** [comment]
Going to add mine in

**Comment by nmakuch** [comment]
Added 👍🏽

**Comment by daine** [comment]
Designers provided their input on the values for the spacing tokens, and they have been applied on the code

**Comment by daine** [comment]
Done and released
