### ISSUE TITLE
Dev - notice spacing updates 

### ISSUE THREAD

**Issue by melaniebmn** [cds-snc/design-gc-conception#1283]
**[Notice](https://www.figma.com/design/mh2maMG2NBtk41k1O1UGHV/branch/Uq2iUvQPdgYwcQFh0xFzhH/GC-Design-System?node-id=33105-831&node-type=frame&t=YeTl5gt6synL3jyW-0)**

## 📇 Summary
Update the notice component (currently in a PR) with the new spacing tokens

## ✅ Definition of Done / Outcomes
- [x] Done when changes to the PR on the `gcds-components` repository is approved and ready for merge
- [x] Done when changes are applied through a PR on the `gcds-tokens` repository that have been approved, merged, and released
- [x] Done when changes have been reviewed by at least 1 developer
- [x] Done when changes have been reviewed by at least 1 designer

## 📜 Acceptance criteria
- [x] Code follows design updates
- [x] Spacing between graphic (on left) and text from 15 to 14px
- [x] Spacing between title and message from 9 to 8px
- [x] Spacing at top of title from 15 to 16px on desktop and 20px on mobile

**Comment by ClementineHahn** [comment]
patch updates went on yesterday by @ethanWallace , to update with proper tokens

**Comment by daine** [comment]
This has been done and released
