### ISSUE TITLE
Documentation: Spacing and typography updates

### ISSUE THREAD

**Issue by daine** [cds-snc/design-gc-conception#1288]
## 📇 Summary
Implement new and updated token values for our spacing as proposed in [[doc here](https://docs.google.com/document/d/1duGEYoerJaYj_6oGKFGJtLv6PaOS0SUcRlftNbe33iA/edit?tab=t.0#heading=h.t19ls6lmub34)]

## 📜 Acceptance criteria
- [x] PR has been reviewed by at least 1 developer

## ✅ Definition of Done / Outcomes
- [x] Done when the tokens, components and utility packages have been updated to use the release the contains the changes above
- [x]  Done when UF spacing classes used within the site have been updated with the new spacing tokens
- [x] Done when custom CSS spacing styles have been updated with the new spacing tokens
- [x] Done when we can confirm that the new spacing tokens are all added correctly to the spacing table on the spacing page
- [x] Done when a PR on the documentation website is approved 
- [x] Done when the PR has been merged and published
\* **note:** there is no need to wait for publishing on this ticket so we can merge and publish the changes immediately.

**Comment by ClementineHahn** [comment]
@melaniebmn , working on this , investigating some unexpected behaviours

**Comment by daine** [comment]
This was done ([PR link](https://github.com/cds-snc/gcds-docs/pull/443)) and published yesterday
