### ISSUE TITLE
Inputs: Defines styles: width, max-width, typography, color, margin, padding

### ISSUE THREAD

**Issue by abdul-CDS** [cds-snc/design-gc-conception#162]
Define in figma for text inputs:
- [x] Width / max-width
- [x] Typography (labels, descriptions etc.)
- [x] Colour
- [x] Border
- [x] Padding

**Outcomes**
Determine base styles for our text inputs

**Deliverables**
Styles documented in figma (and on a sandbox webpage if time permits)

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [ ] S: half a day
- [x] M: 1-2 day
- [ ] L: 1 week
- [ ] XL: Move to an epic

**Out of scope**
-

**Comment by nmakuch** [comment]
Styles in figma

https://www.figma.com/file/VUxfzUWHbMmOpasyNM6e5m/GC-DS-Product-Design?node-id=3160%3A1024

**Comment by nmakuch** [comment]
Sandbox demo page

https://sandbox-brown.vercel.app/inputs
