### ISSUE TITLE
Text area - Defines styles: width, max-width, height, typography, color, margin, padding

### ISSUE THREAD

**Issue by abdul-CDS** [cds-snc/design-gc-conception#176]
Define in figma for text inputs:
- [x] Width / max-width
- [x] Typography (labels, descriptions etc.)
- [x] Colour
- [x] Border
- [x] Padding

**Outcomes**
Determine base styles for our textareas

**Deliverables**
Styles documented in figma (and on a sandbox webpage if time permits)

**Out of scope**
-

**Comment by nmakuch** [comment]
Textarea styles can be viewed live on this webpage
[Textarea demo page](https://sandbox-brown.vercel.app/textarea)

**Comment by nmakuch** [comment]
Textarea styles are documented in figma
[Textarea figma page](https://www.figma.com/file/VUxfzUWHbMmOpasyNM6e5m/GC-DS-Product-Design?node-id=3340%3A1024)
