### ISSUE TITLE
Text area: Define states: default, focus, disabled, error

### ISSUE THREAD

**Issue by abdul-CDS** [cds-snc/design-gc-conception#177]
**Define input states for:**
- [x] Default should be covered in the input styles card
- [x] Focus State
- [x] Disabled State
- [x] Error State

**Outcomes**
All textarea states are accounted for

**Deliverables**
States are documented in figma (and a sandbox webpage if time permits)

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [ ] S: half a day
- [ ] M: 1-2 day
- [ x ] L: 1 week
- [ ] XL: Move to an epic

**Out of scope**
-

**Comment by nmakuch** [comment]
Textarea states can be viewed live on this webpage
[Textarea demo page](https://sandbox-brown.vercel.app/textarea)

**Comment by nmakuch** [comment]
Textarea states are documented in figma
[Textarea figma page](https://www.figma.com/file/VUxfzUWHbMmOpasyNM6e5m/GC-DS-Product-Design?node-id=3340%3A1024)
