### ISSUE TITLE
Design principles [Workshop]

### ISSUE THREAD

**Issue by ioanacontu** [cds-snc/design-gc-conception#23]
**TODO**
- [ ] 

**Outcomes**
- 

**Deliverables**
- 

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [ ] S: half a day
- [x] M: 1-2 day
- [ ] L: 1 week
- [ ] XL: Move to an epic

**Out of scope**
-

**Comment by adeyfarah** [comment]
Ioana/Amy to look at Nov 1st afternoon

**Comment by duboisp** [comment]
Here some reference on this subject:
* General principles related to design - https://www.w3.org/TR/2021/NOTE-design-principles-20210923/#basic-principles
* Naming principles - https://www.w3.org/TR/2021/NOTE-design-principles-20210923/#naming-is-hard
* Best practice template (Data on the web) - https://www.w3.org/TR/2017/REC-dwbp-20170131/#bp-template
* Digital playbook (Archived) - https://canada-ca.github.io/digital-playbook-guide-numerique/en/overview.html
