### ISSUE TITLE
EN Content / Documentation: Banner component

### ISSUE THREAD

**Issue by abdul-CDS** [cds-snc/design-gc-conception#260]
*TODO**
- [x] First version of EN documentation for Banner component using documentation template
- [ ] Review of documentation
- [ ] Publishing documentation on site

**Outcomes**
- First version of documentation for component for feedback

**Deliverables**
- Published documentation page(s)

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [ ] S: half a day
- [ ] M: 1-2 day
- [ ] L: 1 week
- [ ] XL: Move to an epic

**Out of scope**
-

**Comment by melaniebmn** [comment]
@SmartMouthWords here is the link to the Figma file:

https://www.figma.com/file/nfpEteHyEJ9dhJ2YvuvLeo/Documentation-site%2FComponent-Pages?node-id=5811%3A553
