### ISSUE TITLE
EN Content / Documentation: Gov Verify Banner component

### ISSUE THREAD

**Issue by abdul-CDS** [cds-snc/design-gc-conception#261]
*TODO**
- [x] First version of EN documentation for Gov Verify component using documentation template
- [x] Review of documentation

**Outcomes**
- First version of documentation for component for feedback

**Deliverables**
- Published documentation page(s)

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [ ] S: half a day
- [x] M: 1-2 day
- [ ] L: 1 week
- [ ] XL: Move to an epic

**Out of scope**
-

**Comment by melaniebmn** [comment]
@SmartMouthWords here is my first version of the documentation for the verify-banner component:

https://www.figma.com/file/H2DMs2sFa5MxjbxHB7PTSr/Draft-verify-banner-component?node-id=0%3A1
