### ISSUE TITLE
Development: Notice component

### ISSUE THREAD

**Issue by adorayi** [cds-snc/design-gc-conception#269]
**TODO**
- [x] Prototype & Development
- [ ] Review

**Outcomes**
- Development according to designs
- Considerations for accessibility

**Deliverables**
- Code in Github
- Publish on npm

**Comment by adorayi** [comment]
Looking to get some input from @SmartMouthWords on the name and design changes.

**Comment by adorayi** [comment]
Needs grooming, @melaniebmn @ethanWallace to groom.

**Comment by ethanWallace** [comment]
Blocked by accessibility issues with colours

**Comment by ethanWallace** [comment]
New tokens: https://github.com/cds-snc/gcds-tokens/pull/330

Updated look of notice component, juts need to update the unit tests.

**Comment by ClementineHahn** [comment]
Pending @daine review
