### ISSUE TITLE
EN Documentation: Notifcation & Alert component

### ISSUE THREAD

**Issue by abdul-CDS** [cds-snc/design-gc-conception#270]
*TODO**
- [x] First version of EN documentation for component using documentation template
- [ ] Review of documentation
- [ ] Publishing documentation on site

**Outcomes**
- First version of documentation for component for feedback

**Deliverables**
- Published documentation page(s)

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [ ] S: half a day
- [ ] M: 1-2 day
- [ ] L: 1 week
- [ ] XL: Move to an epic

**Out of scope**
-

**Comment by melaniebmn** [comment]
@nmakuch can you review the design part, please?

@SmartMouthWords the draft is ready for your review.

The draft can be found here:
https://docs.google.com/document/d/1OWtLThCcHF1y3o2VgqF8Wt2LtU6kTkUMppYpcjZ8XRI/edit?usp=sharing

**Comment by nmakuch** [comment]
Looks good, nothing to currently add that isn't there already
