### ISSUE TITLE
CDS devs research insights

### ISSUE THREAD

**Issue by ioanacontu** [cds-snc/design-gc-conception#32]
### Interview guide: 
https://docs.google.com/document/d/13WaXfEFRnnZzCol6jYP8mTJ5hk6k0p9Olq8vIw8EEOE/edit#heading=h.n1d0qafnheeb

### Interviews notes: 
Participant A → [Notes](https://docs.google.com/document/d/1B140K5TgzFxF5G8-udwkGO-KT4OdqEEia0t3zcxXq1s/edit?usp=sharing)
Participant B → [Notes](https://docs.google.com/document/d/1q7DmD5g3NmcK1odgV6AWWhXTlrvZbfoIVTE8o_NZWBM/edit?usp=sharing)
Participant C → [Notes](https://docs.google.com/document/d/12d2cs8QF7UUwPjIyfg7xAQoCi28wJ4QsCbwBLOgfLVk/edit?usp=sharing)
Participant D → [Notes](https://docs.google.com/document/d/16O4ibUIQz3Sq4OSI7Cm5snNDwZqc6MnwQgmf5OF3giY/edit?usp=sharing)
Participant E → [Notes](https://docs.google.com/document/d/1zNOeMQzSzLAJk0ksUgUi-i69KqQHU_DAM4jSbd0QkJw/edit#)
Participant F → [Notes](https://docs.google.com/document/d/10PeZPPd8-BnZsLfM5iIBeC5cMotyBCqsIK2MBdbqYbc/edit?usp=sharing)

### Analysis and insights TBD.

**Comment by mcman12** [comment]
taking raw notes to gather insights and highlights main points.

**Comment by ioanacontu** [comment]
I have not yet started on this. But the plan is to start towards the end of this week.

**Comment by ioanacontu** [comment]
A few highlights added to the product vision research refresher.

**Comment by ioanacontu** [comment]
No progress on this.
