### ISSUE TITLE
Stakeholder interviews [planning]

### ISSUE THREAD

**Issue by ioanacontu** [cds-snc/design-gc-conception#33]
### Research plan — GC Design system stakeholder interviews: 
https://docs.google.com/document/d/1Rw5nBZIfsg6LnJJ4NJJotBnZp-1MkkZsID3hzhwW2n4/edit#heading=h.yp22ocgrla7w

### Facilitation guide: 
https://docs.google.com/document/d/1uvPLRuQHiiRGSAA90BaD3cyFFEFYFiGTq6WSAw8sQWA/edit#

**Comment by mcman12** [comment]
Set interviews with stakeholders on current system, to understand approvals. Sarah to take notes. Interviews happening next sprint

**Comment by duboisp** [comment]
Here some feedback that we got in written by Stat Can in regard of WET4 pros/cons and wish list.
https://wet-boew.github.io/wet-boew-documentation/research/2018-13-wet5-workshop-statcan.html

**Comment by ioanacontu** [comment]
Interviews in progress.

**Comment by ioanacontu** [comment]
Moved it in review - it depends on the "interviews carry out" card. Will keep it here until the carry-out card is done.
