### ISSUE TITLE
Content: Grid component

### ISSUE THREAD

**Issue by adorayi** [cds-snc/design-gc-conception#335]
**Summary:** Documentation of component guidance in EN for the Grid component on the Design System website.
Including use cases, how to use guidance, accessibility guidelines and more.

**Linked to:** #326

**Acceptance Criteria:**

- [x] Component Kickoff
- [x] Component review
- [x] Sync with Dev and Design
- [x] Research and consulting other design libraries
- [x] Component ID (name, definition, example image 
- [x] Use case (when to use guidance & related components)  
- [x] How to use guidance 
- [x] Accessibility guidelines
- [x] Inclusive language
- [x] Descriptive text for images
- [x] Translation & Localization
- [x] Bilingual review – content design
- [x] Ensure consistency: ordering, terminology, high level voice/tone/style 
- [x] Final review

**Comment by nchoquet** [comment]
test mention @nchoquet

**Comment by nchoquet** [comment]
test mention @nchoquet 2

**Comment by ClementineHahn** [comment]
It will overlap with next sprint

**Comment by anikbrazeau** [comment]
## Sent to translation on August 4, 2023 

https://www.figma.com/file/nfpEteHyEJ9dhJ2YvuvLeo/Documentation-site%2FComponent-Pages?type=design&node-id=5806-162&mode=design&t=xp7tJ0cKwn0P32ME-0

**Comment by anikbrazeau** [comment]
- Back from translation.
- Now Reviewing bilingually (August 25)

**Comment by melaniebmn** [comment]
Grid guidance has been added to the documentation site.
