### ISSUE TITLE
Content: Icon component

### ISSUE THREAD

**Issue by adorayi** [cds-snc/design-gc-conception#337]
**Summary:** Documentation of component guidance in EN for the Icons component on the Design System website.
Including use cases, how to use guidance, accessibility guidelines and more.

Existing draft to be rewritten to reflect the new icon set built in house that's replacing the FontAwesome set. New content specifically around individual use of icons.

**Acceptance Criteria:**

- [x] Component Kickoff
- [x] Component review
- [x] Sync with Design
- [x] Sync with Dev
- [x] Research and consulting other design libraries
- [x] Component ID (name, definition, example image 
- [x] Use case (when to use guidance & related components)  
- [x] How to use guidance 
- [x] Accessibility guidelines
- [x] Inclusive language
- [x] Descriptive text for images
- [x] Translation & Localization
- [x] Bilingual review – content design
- [x] Ensure consistency: ordering, terminology, high level voice/tone/style 
- [x] Final review

**Comment by anikbrazeau** [comment]
**Icon documentation on canada.ca:** https://design.canada.ca/common-design-patterns/icons.html

**Comment by SmartMouthWords** [comment]
Notes from a past dev/design sync on icons. Outstanding questions were around:
- when to recommend the use of alt text and when it should not be used (if it has a label that renders the alt text redundant/repetitive)   
- how can a user determine if their use of an icon is decorative only 
- Which icons come with built in labels and which don't
- what to do with alt text when the label doesn't match the message the icon is being used to communicate
[Notes from a past dev/design sync on icons: https://docs.google.com/document/d/1azuCFDh3R4D0Qsz5N6S2Vxe2zxbgb2Qrb4aPgLCxtXc/edit](url)

**Comment by anikbrazeau** [comment]
## English draft documentation

https://docs.google.com/document/d/1ZsUnSfni07k8HfaRJiTN0Cmo3gCutlTBd5hReAWJxj8/edit

**Comment by nmakuch** [comment]
some of the images in the documentation I created can be found here:
https://www.figma.com/file/mh2maMG2NBtk41k1O1UGHV/Canadian-Digital-Service%E2%80%A8---GC-Design-System?type=design&node-id=1847-5001&mode=design&t=XfqhPtRcfelbixFF-0

**Comment by ClementineHahn** [comment]
https://docs.google.com/document/d/1ZsUnSfni07k8HfaRJiTN0Cmo3gCutlTBd5hReAWJxj8/edit

**Comment by SmartMouthWords** [comment]
20-Sept-23: Discussed icons issues in [dev/design sync](https://docs.google.com/document/d/1ZshJZZ4apf-jAfwrTX512egTHKkbTWFdQpd_yHt8VW8/edit#heading=h.9qymgxe7d5o6)

**Comment by ClementineHahn** [comment]
Next teps will be : talk with dev for guidance, send to translation and start the design work. So next steps and cards to create for grooming @adorayi

**Comment by ClementineHahn** [comment]
@nmakuch can you update the acceptance criteria progress on this card by cehcking off the steps already done so we can visualize what is left to be done ? 
thank you

**Comment by nmakuch** [comment]
https://docs.google.com/document/d/1Z4UJI0QLLbEGuzbOmC2s6Bs5SHL-9h3NSHtjVg1eG74/edit#heading=h.973xw9922bbn

Revised Icon content

**Comment by nmakuch** [comment]
sent to translation

**Comment by nmakuch** [comment]
French icon documentation:
https://docs.google.com/document/d/1kUwUopBAJV6z64TximwEX-hsztKrNZmgIXncgD0VZco/edit

**Comment by nmakuch** [comment]
Ready for a final review
