### ISSUE TITLE
EN Content: Language Toggle component

### ISSUE THREAD

**Issue by abdul-CDS** [cds-snc/design-gc-conception#338]
**Summary:** Documentation of component guidance in EN for the Language toggle component on the Design System website.
Including use cases, how to use guidance, accessibility guidelines and more.

**Acceptance Criteria:**

- [x] Component Kickoff
- [x] Component review
- [x] Sync with Dev and Design
- [x] Research and consulting other design libraries
- [x] Component ID (name, definition, example image 
- [x] Use case (when to use guidance & related components)  
- [x] How to use guidance 
- [x] Accessibility guidelines
- [x] Inclusive language
- [x] Descriptive text for images
- [x] Translation & Localization
- [x] Bilingual review – content design
- [x] Ensure consistency: ordering, terminology, high level voice/tone/style 
- [x] Final review

[Draft document](https://docs.google.com/document/d/1O5c6UDG8hsVUQXoSHLmAZTbE8endbbSVZ0yjvKPbl9M/edit?usp=sharing)

**Comment by mcman12** [comment]
Reviewed!

**Comment by SmartMouthWords** [comment]
@nchoquet [Document](https://docs.google.com/document/d/1O5c6UDG8hsVUQXoSHLmAZTbE8endbbSVZ0yjvKPbl9M/edit#heading=h.docbrua3m7ts)'s ready for translation.

**Comment by abdul-CDS** [comment]
ETA for FR content: 28th June.

**Comment by nchoquet** [comment]
@ethanWallace, translation is ready here:

https://docs.google.com/document/d/1Ri7sXekCCqapL_oRr8GUgXiR5O7l5cb7co8QlhL-piQ/edit?usp=sharing

**Comment by anikbrazeau** [comment]
# Bilingual content review underway 

**EN**: https://docs.google.com/document/d/1O5c6UDG8hsVUQXoSHLmAZTbE8endbbSVZ0yjvKPbl9M/edit#heading=h.4pwu50pkptap
**FR**: https://docs.google.com/document/d/1Ri7sXekCCqapL_oRr8GUgXiR5O7l5cb7co8QlhL-piQ/edit

**Comment by anikbrazeau** [comment]
# ✅ Final content review complete
> Missing Visual for French Anatomy 

# 🚀 Ready for dev
