### ISSUE TITLE
Content: Pagination component

### ISSUE THREAD

**Issue by adorayi** [cds-snc/design-gc-conception#339]
**Summary:** Documentation of component guidance in EN for the Pagination component on the Design System website.
Including use cases, how to use guidance, accessibility guidelines and more.

**Linked to:** #395 #330 #405

**Acceptance Criteria:**

- [x] Component Kickoff
- [x] Component review
- [x] Sync with Dev and Design
- [x] Research and consulting other design libraries
- [x] Component ID (name, definition, example image 
- [x] Use case (when to use guidance & related components)  
- [x] How to use guidance 
- [x] Accessibility guidelines
- [x] Inclusive language
- [x] Descriptive text for images
- [x] Translation & Localization
- [x] Bilingual review – content design
- [x] Ensure consistency: ordering, terminology, high level voice/tone/style 
- [x] Final review

**Comment by ClementineHahn** [comment]
@SmartMouthWords did review ok. 
Review with @dylanzheng94 still need to happen then when all good, ok to send to translation and need to mention Nicholas C so he knows when its ready

**Comment by nmakuch** [comment]
I've made the edits Amy asked of me before going on vacation 
https://www.figma.com/file/nfpEteHyEJ9dhJ2YvuvLeo/Documentation-site%2FComponent-Pages?type=design&node-id=6784-7591&mode=design&t=cSLR1x0KwkzUiLWG-0

Should check in with @anikbrazeau when she's back and I think this is good to go

**Comment by anikbrazeau** [comment]
## Sent to translation on August 15, 2023 
cc @nchoquet 

https://www.figma.com/file/nfpEteHyEJ9dhJ2YvuvLeo/Documentation-site%2FComponent-Pages?type=design&node-id=6784%3A7591&mode=design&t=xRpoPfYnroQjGEma-1

**Comment by anikbrazeau** [comment]
- Back from translation.
- Now Reviewing bilingually (August 25)

**Comment by anikbrazeau** [comment]
# ✅ Final bilingual content review complete

# 🚀 Ready for dev
>  - **EN**: https://www.figma.com/file/nfpEteHyEJ9dhJ2YvuvLeo/Documentation-site%2FComponent-Pages?type=design&node-id=6784-7591&mode=design&t=sQ2vFagl3nDjRNKI-0
>  - **FR**: https://www.figma.com/file/nfpEteHyEJ9dhJ2YvuvLeo/Documentation-site%2FComponent-Pages?type=design&node-id=10865-783&mode=design&t=sQ2vFagl3nDjRNKI-0

CC  @melaniebmn @ethanWallace @dylanzheng94 @nmakuch @ClementineHahn

**Comment by anikbrazeau** [comment]
# Anatomies need to be reworked

https://www.figma.com/file/E5Kymz26ju5abRn3UGOWlX/Anatomies---bilingual-reviews?type=design&node-id=216%3A972&mode=design&t=phQHHNfSIyk36LUx-1
