### ISSUE TITLE
Content: Signature component

### ISSUE THREAD

**Issue by adorayi** [cds-snc/design-gc-conception#341]
**Summary:** Documentation of component guidance in EN for the Signature component on the Design System website.
Including use cases, how to use guidance, accessibility guidelines and more.

**Acceptance Criteria:**

- [x] Component Kickoff
- [x] Component review
- [x] Sync with Dev and Design
- [x] Research and consulting other design libraries
- [x] Component ID (name, definition, example image 
- [x] Use case (when to use guidance & related components)  
- [x] How to use guidance 
- [x] Accessibility guidelines
- [x] Inclusive language
- [x] Descriptive text for images
- [x] Translation & Localization
- [x] Bilingual review – content design
- [x] Ensure consistency: ordering, terminology, high level voice/tone/style 
- [x] Final review

**Comment by nmakuch** [comment]
First draft of Signature component content for review
https://docs.google.com/document/d/1M_wtvVaaYjE175OY18hi0hVRriHynm9p-gR5wrBY8sg/edit

**Comment by SmartMouthWords** [comment]
Had to verify a few things with Nick, consulted the FIP design standard and asked Sarah for review. @nchoquet file's now ready for translation.

**Comment by nchoquet** [comment]
Translation is ready @nmakuch and @SmartMouthWords 

https://docs.google.com/document/d/1qF2c1-17aejxDZRr6mHigXtAK3pMEsMyOaZDW7I-2fU/edit?usp=sharing

**Comment by anikbrazeau** [comment]
# 👀 Bilingual content review underway 

**EN**: https://docs.google.com/document/d/1M_wtvVaaYjE175OY18hi0hVRriHynm9p-gR5wrBY8sg/edit
**FR**: https://docs.google.com/document/d/1qF2c1-17aejxDZRr6mHigXtAK3pMEsMyOaZDW7I-2fU/edit

**Comment by anikbrazeau** [comment]
# ✅ Final bilingual content review complete
> - Confirming final section content "Apply the wordmark type"
> - Missing Visuals for French Anatomy 

# 🚀 Ready for dev
> @ethanWallace @melaniebmn @ClementineHahn

**Comment by ClementineHahn** [comment]
@nmakuch to source the picture then to publish on the website

**Comment by nmakuch** [comment]
added french images to the docs file
https://docs.google.com/document/d/1M_wtvVaaYjE175OY18hi0hVRriHynm9p-gR5wrBY8sg/edit?pli=1

**Comment by ClementineHahn** [comment]
More work was needed on the images of Canada.ca , should be done by end of sprint
