### ISSUE TITLE
Content: Select component

### ISSUE THREAD

**Issue by adorayi** [cds-snc/design-gc-conception#342]
**Summary:** Documentation of component guidance in EN for the Select component on the Design System website.
Including use cases, how to use guidance, accessibility guidelines and more.

**Linked to:** #385 #333
 
**Acceptance Criteria:**

- [x] Component Kickoff
- [x] Component review
- [x] Sync with Dev and Design
- [x] Research and consulting other design libraries
- [x] Component ID (name, definition, example image 
- [x] Use case (when to use guidance & related components)  
- [x] How to use guidance 
- [x] Accessibility guidelines
- [x] Inclusive language
- [x] Descriptive text for images
- [x] Translation & Localization
- [x] Bilingual review – content design
- [x] Ensure consistency: ordering, terminology, high level voice/tone/style 
- [x] Final review

**Comment by ethanWallace** [comment]
Draft documentation: https://docs.google.com/document/d/1tR94i1FWJzyynQgV9v1PCxHsBdyYKowPnDbfoX6kNVM/edit?usp=sharing

**Comment by anikbrazeau** [comment]
## Sent to translation on August 4, 2023

https://docs.google.com/document/d/1tR94i1FWJzyynQgV9v1PCxHsBdyYKowPnDbfoX6kNVM/edit#heading=h.st7ju6r805zl

**Comment by ClementineHahn** [comment]
Great ! Thank you 🎉

**Comment by anikbrazeau** [comment]
# ✅ Final bilingual content review complete

# 🚀 Ready for dev
>  - **EN**: https://docs.google.com/document/d/1tR94i1FWJzyynQgV9v1PCxHsBdyYKowPnDbfoX6kNVM/edit
>  - **FR**: https://docs.google.com/document/d/1zVu1rc0lLKRL6PjffnWGnM2p_1mo_fbs7C2dHIiiG8Q/edit

CC @ethanWallace @melaniebmn @dylanzheng94  @ClementineHahn

**Comment by melaniebmn** [comment]
PR to add select content to the documentation site:

https://github.com/cds-snc/gcds-docs/pull/173
