### ISSUE TITLE
Content: File uploader component

### ISSUE THREAD

**Issue by adorayi** [cds-snc/design-gc-conception#343]
**Summary:** Documentation of component guidance in EN for the File uploader component on the Design System website.
Including use cases, how to use guidance, accessibility guidelines and more.

**Linked to:** #387 #334

**Acceptance Criteria:**

- [x] Component Kickoff
- [x] Component review
- [x] Sync with Dev and Design
- [x] Research and consulting other design libraries
- [x] Component ID (name, definition, example image 
- [x] Use case (when to use guidance & related components)  
- [x] How to use guidance 
- [x] Accessibility guidelines
- [x] Inclusive language
- [x] Descriptive text for images
- [x] Translation & Localization
- [x] Bilingual review – content design
- [x] Ensure consistency: ordering, terminology, high level voice/tone/style 
- [x] Final review

**Comment by ClementineHahn** [comment]
Pending @SmartMouthWords  we will be able to send this to translation

**Comment by anikbrazeau** [comment]
@dylanzheng94 possible to get a link to this file for review?

**Comment by anikbrazeau** [comment]
### Reviewing English draft 👀 
https://docs.google.com/document/d/1z-te5Aa8FfZIXxHvPRNH3y6UOIv-UeSoQA_-jee8QrU/edit

**Comment by SmartMouthWords** [comment]
Reviewed draft and added comments. Meeting with Dylan and Anik today to review and clarify sone outstanding questions about:

- file uploader capabilities and options for users 
- relationship between uploading a file, removing a file, and submitting
- error validation 
- plain language equivalents

**Comment by anikbrazeau** [comment]
# ✅ Final bilingual content review complete

# 🚀 Ready for dev
>  - **EN**: https://docs.google.com/document/d/1z-te5Aa8FfZIXxHvPRNH3y6UOIv-UeSoQA_-jee8QrU/edit
>  - **FR**: https://docs.google.com/document/d/17SfiyWnxd8E3m9-jlxk-ZLBQBVGwAeZ4U-sFP_Vo_vk/edit

CC @ethanWallace @melaniebmn @dylanzheng94  @ClementineHahn

**Comment by melaniebmn** [comment]
PR to add file uploader content to the documentation site:

https://github.com/cds-snc/gcds-docs/pull/175
