### ISSUE TITLE
EN Content: Error Summary

### ISSUE THREAD

**Issue by abdul-CDS** [cds-snc/design-gc-conception#361]

**Comment by SmartMouthWords** [comment]
[https://www.figma.com/file/nfpEteHyEJ9dhJ2YvuvLeo/Documentation-site%2FComponent-Pages?node-id=6981%3A6478&t=MtYma4bYzQuRdCjT-1](Figma prototype)

**Comment by SmartMouthWords** [comment]
- [ ] Assemble best practice research writing error messages
- [ ] Prototype pages (use case, design, code)
- [ ] Draft content for use case
- [ ] Draft content for design 
- [ ] Draft content for code
- [ ] Review and validate content with @nmakuch and @ethanWallace

**Comment by SmartMouthWords** [comment]
Also started [comparison and analysis ](https://www.figma.com/file/nfpEteHyEJ9dhJ2YvuvLeo/Documentation-site%2FComponent-Pages?node-id=7072%3A7216&t=MtYma4bYzQuRdCjT-1)of error message, error summary, and potential future error pattern content:

**Comment by SmartMouthWords** [comment]
Completed draft and sent for translation 14-Apr-2023
