### ISSUE TITLE
Research Design best practice and design session with David Elisma on site menu

### ISSUE THREAD

**Issue by abdul-CDS** [cds-snc/design-gc-conception#370]
- [x] Research design best practices for site menu and navigation
- [x] Schedule session with David Elisma to learn about DTO changes to site menu and header
- [x] Document design best practices for site menu and navigation and share with team

**Comment by SmartMouthWords** [comment]
Research links for documentation work : 
(https://insidegovuk.blog.gov.uk/2021/11/11/launching-gov-uks-new-menu-bar/)
(https://design-patterns.service.justice.gov.uk/components/side-navigation/)
Fixed sidebar, W3 schools: (https://www.w3schools.com/howto/howto_css_fixed_sidebar.asp) 
Response sidebar, W3 schools: (https://www.w3schools.com/howto/howto_css_sidebar_responsive.asp)
Left-side vertical nav, NN: (https://www.nngroup.com/articles/vertical-nav/)
Multiple nav landmarks, what no to do, Canada.ca example: (https://www.aditus.io/patterns/multiple-navigation-landmarks/)
Types of navigation, information seeking behaviours, O’Reily: (https://www.oreilly.com/library/view/designing-web-navigation/9780596528102/ch04.html#:~:text=CONTEXTUAL%20NAVIGATION,-Also%20called%3A%20associative&text=It%27s%20situational.,the%20content%20of%20a%20page.) 

IRCC DS navigation: (https://www.figma.com/file/scmNcZkQomZSrwBbQU1bvn/Documentation?node-id=4-33&t=LtX26Frt48lAyiCj-0)
(https://www.systeme-de-design.gouv.fr/utilisation-et-organisation/)
(https://www.systeme-de-design.gouv.fr/elements-d-interface/composants)
