### ISSUE TITLE
EN: Content Top Navigation

### ISSUE THREAD

**Issue by SmartMouthWords** [cds-snc/design-gc-conception#377]
*Summary:** Documentation of component guidance in EN for the Site Menu component on the Design System website.
Including use cases, how to use guidance, accessibility guidelines and more.

**Acceptance Criteria:**

- [x] Component Kickoff
- [x] Component review
- [x] Sync with Dev and Design
- [x] Research and consulting other design libraries
- [x] Component ID (name, definition, example image 
- [x] Use case (when to use guidance & related components)  
- [x] How to use guidance 
- [x] Accessibility guidelines
- [x] Inclusive language
- [x] Descriptive text for images
- [x] Translation & Localization
- [x] Bilingual review – content design
- [x] Ensure consistency: ordering, terminology, high level voice/tone/style 
- [x] Final review

**Comment by SmartMouthWords** [comment]
- [ ] Assemble best practice research writing error messages
- [ ]  Meet with developer to review planned functionality
- [ ]  Prototype pages (use case, design, code)
- [ ]  Draft content for use case
- [ ]  Draft content for design
- [ ]  Draft content for code
- [ ]  Review and validate content with designer(s) and developer(s) 
- [ ]  Bring to content critique

**Comment by ClementineHahn** [comment]
is now known as the "header navigation"

**Comment by SmartMouthWords** [comment]
[Draft content ](https://www.figma.com/file/nfpEteHyEJ9dhJ2YvuvLeo/Documentation-site%2FComponent-Pages?type=design&node-id=9409%3A55558&t=bLCX8bMfFqwuv8tH-1 )

**Comment by ClementineHahn** [comment]
@SmartMouthWords waiting on side nav to be reviewed first in order to review this one for wording consistency

**Comment by SmartMouthWords** [comment]
12-Jun: Did some alignment with @dylan on with the side menu. Removing mobile anatomies from documentation site pages for both components. 
13-June: Updates to the name: The component will be called top navigation   
14- Fixes to the anatomy, terminology updates and finalized review

**Comment by SmartMouthWords** [comment]
@nchoquet This [file's in Figma](https://www.figma.com/file/nfpEteHyEJ9dhJ2YvuvLeo/Documentation-site%2FComponent-Pages?type=design&node-id=9409%3A55522&t=bLCX8bMfFqwuv8tH-1) ready for translation.

**Comment by ClementineHahn** [comment]
@amy to update status on "clear to publishing" or not on this so @ethan can push forward
