### ISSUE TITLE
EN: Content "Side nav"

### ISSUE THREAD

**Issue by SmartMouthWords** [cds-snc/design-gc-conception#378]
**Summary:** Documentation of component guidance in EN for the Left-hand navigation component on the Design System website.
Including use cases, how to use guidance, accessibility guidelines and more.

**Acceptance Criteria:**

- [x] Component Kickoff
- [x] Component review
- [x] Sync with Dev and Design
- [x] Research and consulting other design libraries
- [x] Component ID (name, definition, example image 
- [x] Use case (when to use guidance & related components)  
- [x] How to use guidance 
- [x] Accessibility guidelines
- [x] Inclusive language
- [x] Descriptive text for images
- [x] Translation & Localization
- [x] Bilingual review – content design
- [x] Ensure consistency: ordering, terminology, high level voice/tone/style 
- [x] Final review

**Comment by SmartMouthWords** [comment]
- [ ] -  Assemble best practice research writing error messages
- [ ] -  Meet with developer to review planned functionality
- [ ] -  Prototype pages (use case, design, code)
- [ ] -  Draft content for use case
- [ ] -  Draft content for design
- [ ] -  Draft content for code
- [ ] -  Review and validate content with designer(s) and developer(s)
- [ ] -  Bring to content critique

**Comment by SmartMouthWords** [comment]
@nchoquet [Side navigation](https://docs.google.com/document/d/11QfydplaM-fDoxjJkNd7u778o1cS5JMFQf0jApzeGks/edit)'s ready.

**Comment by nchoquet** [comment]
@SmartMouthWords, translation is ready here:

https://docs.google.com/document/d/1rpl65Se7vOnkZ0nXdhoLt0IpoBFgrqo4yc7JCBUsuKo/edit?usp=sharing

**Comment by anikbrazeau** [comment]
# ✅ Final bilingual content review complete
> Missing "Also called" section
> Missing Visuals for French Anatomy 
> Should be released in tandem with Top navigation

# 🚀 Ready for dev
> @ethanWallace @melaniebmn @ClementineHahn 

**EN**: https://docs.google.com/document/d/11QfydplaM-fDoxjJkNd7u778o1cS5JMFQf0jApzeGks/edit
**FR**: https://docs.google.com/document/d/1rpl65Se7vOnkZ0nXdhoLt0IpoBFgrqo4yc7JCBUsuKo/edit
