### ISSUE TITLE
Competitive analysis

### ISSUE THREAD

**Issue by ioanacontu** [cds-snc/design-gc-conception#40]
For the Design System guidance website, it might be useful to do a review of other design systems' information architecture, page templates etc.

**Comment by ioanacontu** [comment]
Common themes on different design systems is started. Ongoing.

**Comment by quidampepin** [comment]
Started a presentation (work in progress): https://docs.google.com/presentation/d/1XdrZSdzG3fBz6wJS0Dy_z6k7FeF8Y42lhfvlmFeAtOY/edit?usp=sharing

**Comment by ioanacontu** [comment]
Navigation of a guidance
Content guidance
A11y guidance
Do certain systems work better than others. 
Will be shared back.

**Comment by ioanacontu** [comment]
At the guidance pod meeting - a review. 
testing plan - to be showed at the guidance pod meeting.

**Comment by ioanacontu** [comment]
There was a discussion during the Guidance Pod meeting. 
___
Quick update on the guidance testing:
the project sheet is here: https://docs.google.com/spreadsheets/d/1GLLkAjhN21n3aW9S2D4m-JlTdYqGBBmLWzzDogYBnd8/edit?usp=sharing
testing should start this PM
There is a prototype of a GC Design System that we started working on (that borrows from work done by CRA and some things we had done in the previous design system project). It was named "GC Design System". To avoid giving the impression that this is THE prototype the whole group is working on and has agreed upon, I gave it a name (Borealis - cheesy, I know). I'm not suggesting this is the way we should build a prototype - but I thought that we might as well see how it's working or not and learn from it. https://design.canada.ca/revamp/started.html

**Comment by quidampepin** [comment]
- initial analysis is done: https://docs.google.com/presentation/d/1XdrZSdzG3fBz6wJS0Dy_z6k7FeF8Y42lhfvlmFeAtOY/edit#slide=id.g332e4c1316_2_167
- testing will start today (project sheet is here: https://docs.google.com/spreadsheets/d/1GLLkAjhN21n3aW9S2D4m-JlTdYqGBBmLWzzDogYBnd8/edit?usp=sharing)
