### ISSUE TITLE
Content - Cards component

### ISSUE THREAD

**Issue by adorayi** [cds-snc/design-gc-conception#401]
**Summary:** Documentation of component guidance in EN for the Cards component on the Design System website.
Including use cases, how to use guidance, accessibility guidelines and more.

**Linked to:** #396 #399 #400

**Acceptance Criteria:**

- [x] Component Kickoff
- [x] Component review
- [x] Sync with Dev and Design
- [x] Research and consulting other design libraries
- [x] Component ID (name, definition, example image 
- [x] Use case (when to use guidance & related components)  
- [x] How to use guidance 
- [x] Accessibility guidelines
- [x] Inclusive language
- [x] Descriptive text for images
- [x] Translation & Localization
- [x] Bilingual review – content design
- [x] Ensure consistency: ordering, terminology, high level voice/tone/style 
- [x] Final review

**Comment by ClementineHahn** [comment]
Pending last review from @SmartMouthWords , will be good to go to translation

**Comment by anikbrazeau** [comment]
**EN**: https://docs.google.com/document/d/12ESkEF2pafMN-XoUWznvkOB2EyBxasOxvyVxTMZAZsY/edit#heading=h.tbswke9yeyw2

**Comment by SmartMouthWords** [comment]
Sent to translation 26-July-2023

**Comment by anikbrazeau** [comment]
# ✅ Final bilingual content review complete
> **Outstanding issues**
> - Confirming whether it should be "Headline link or "Card title"
> - Missing Visuals for French Anatomy 

# 🚀 Ready for dev
> **Otherwise ready to stage:**
>  - **EN**: https://docs.google.com/document/d/12ESkEF2pafMN-XoUWznvkOB2EyBxasOxvyVxTMZAZsY/edit
>  - **FR**: https://docs.google.com/document/d/1Kam7vpJrm6Iijfy61KN4P5UkdUICZHGXg-2BXeyemRs/edit

CC @ethanWallace @melaniebmn @dylanzheng94  @ClementineHahn
