### ISSUE TITLE
Design - Icons component

### ISSUE THREAD

**Issue by adorayi** [cds-snc/design-gc-conception#408]
**Summary:** Design of the Icons component. 
Design on component branch and push to main Figma file when approved.

**Acceptance Criteria:**

- [x] Component Kickoff
- [x] Sync with Dev and Design
- [x] Research and consulting other design libraries
- [x] WCAG Goal can be completed using a screen reader.
- [x] WCAG Visual elements observe color contrast requirements.
- [x] WCAG Manual accessibility testing meets WCAG 2.1 AA requirements.
- [x] Provides equal service in French and English.
- [x] Sync with Dev and Design
- [x] Comparison with official policy, documented reasons for deviation if any
- [x] Design review
- [x] Policy index is updated accordingly
- [x] [Policy review](https://www.figma.com/file/p0eiLxdme1g93sIuggjipR/Colour-%26-typography-differences-GCDS-vs.-Canada.ca?type=design&node-id=0-1&t=kkavFCQ74dMoZw6V-0)
- [x] Design - Different screen sizes
- [x] Design - Short content / long content (text overflow etc.)
- [x] Design - Error state (if applicable)
- [x] Design - Empty state (if applicable)
- [x] Inventory of icons
- [x] Design of all icons
- [x] Document
- [x] Component anatomy
- [x] Write draft of design guidance
- [x] Handoff from draft dev guidance to documentation author/lead
- [x] Update Figma version

**Comment by abdul-CDS** [comment]
Icons need definition of which needed alt text and when, which could rely on the icon labels, and which were decorative – and how to tell the difference.

**Comment by abdul-CDS** [comment]
Icons need definition of which needed alt text and when, which could rely on the icon labels, and which were decorative – and how to tell the difference.

**Comment by abdul-CDS** [comment]
Icons need definitions of which needed alt text and when, which could rely on the icon labels, and which were decorative – and how to tell the difference.

**Comment by adorayi** [comment]
Quite a few changes needed.

**Comment by anikbrazeau** [comment]
## English Draft Documentation

https://docs.google.com/document/d/1ZsUnSfni07k8HfaRJiTN0Cmo3gCutlTBd5hReAWJxj8/edit

**Comment by adorayi** [comment]
Reopened - based on the decision reached, we will design our own icons from the ones being used in our components and patterns, thereby limiting the options and growing based on need.

**Comment by nmakuch** [comment]
Icon inventory:
https://docs.google.com/spreadsheets/d/1RkJgEHIf40cxXdDQ9cIwLaINaZJFWK574TtVNRex6r0/edit?pli=1#gid=0

**Comment by nmakuch** [comment]
Icon inventory:
https://docs.google.com/spreadsheets/d/1RkJgEHIf40cxXdDQ9cIwLaINaZJFWK574TtVNRex6r0/edit?pli=1#gid=0

**Comment by adorayi** [comment]
Icon inventory:
https://docs.google.com/spreadsheets/d/1RkJgEHIf40cxXdDQ9cIwLaINaZJFWK574TtVNRex6r0/edit?pli=1#gid=0

**Comment by nmakuch** [comment]
https://www.figma.com/file/mh2maMG2NBtk41k1O1UGHV/Canadian-Digital-Service%E2%80%A8---GC-Design-System?type=design&node-id=1847-5001&mode=design&t=pJVKx4ROAWdsGNum-0

**Comment by nmakuch** [comment]
Made icons into a font to hopefully make the dev work a lot smoother

[gcds-icons-v1.0.zip](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGtEQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--274badd901130b77646c5cfcee777686d07acb0e/gcds-icons-v1.0.zip)
