### ISSUE TITLE
Content: Container component

### ISSUE THREAD

**Issue by adorayi** [cds-snc/design-gc-conception#416]
**Summary:** Documentation of component guidance in EN for the container component on the Design System website.
Including use cases, how to use guidance, accessibility guidelines and more.

**Linked to:** #414 #415 #413

**Acceptance Criteria:**

- [x] Component Kickoff
- [x] Component review
- [x] Sync with Dev and Design
- [x] Research and consulting other design libraries
- [x] Component ID (name, definition, example image 
- [x] Use case (when to use guidance & related components)  
- [x] How to use guidance 
- [x] Accessibility guidelines
- [x] Inclusive language
- [x] Descriptive text for images
- [x] Translation & Localization
- [x] Bilingual review – content design
- [x] Ensure consistency: ordering, terminology, high level voice/tone/style 
- [x] Final review

**Comment by ClementineHahn** [comment]
Currently in review with @SmartMouthWords , then go to translation

**Comment by anikbrazeau** [comment]
https://docs.google.com/document/d/17hV1utiNKbLZ8i276-3Ve-zuwMt5SPEtYJnvWwuq2Q8/edit

**Comment by anikbrazeau** [comment]
## Sent to translation on August 4, 2023 

https://docs.google.com/document/d/17hV1utiNKbLZ8i276-3Ve-zuwMt5SPEtYJnvWwuq2Q8/edit

**Comment by anikbrazeau** [comment]
# ✅ Final bilingual content review complete
> **Outstanding issues:**
> - Definition structure in French

# 🚀 Ready for dev
> **Otherwise ready to stage:**
>  - **EN**: https://docs.google.com/document/d/17hV1utiNKbLZ8i276-3Ve-zuwMt5SPEtYJnvWwuq2Q8/edit
>  - **FR**: https://docs.google.com/document/d/1Mr3E6plnKPGobZBQZCQgdh2YXW5xL3Fk2OL6zj6Ld70/edit

CC @ethanWallace @melaniebmn @dylanzheng94  @ClementineHahn

**Comment by melaniebmn** [comment]
Container guidance has been added to our documentation site.
