### ISSUE TITLE
Design: Apply colour changes to the components to make them compliant to policy.

### ISSUE THREAD

**Issue by adorayi** [cds-snc/design-gc-conception#423]
To do:
- [x] Update colour tokens library in github with new colours
- [x] Load colour tokens into tokens plugin in figma
- [x] Apply new colour tokens to figma library
- [ ] Review design and dev to ensure we're using the same token values

**Comment by nmakuch** [comment]
Colour tokens have been updated in figma
https://www.figma.com/file/mh2maMG2NBtk41k1O1UGHV/Canadian-Digital-Service%E2%80%A8---GC-Design-System?type=design&node-id=4-1006&mode=design&t=RuxakLTwSZ41AqZJ-0

**Comment by nmakuch** [comment]
Almost done reviewing tokens,

topnav has been updated to use the canada.ca hover style:
https://github.com/cds-snc/gcds-components/pull/219

**Comment by nmakuch** [comment]
Reviewed figma and github components and the rest of the style update work has been done in this PR just waiting for approval before merging

https://github.com/cds-snc/gcds-components/pull/221

**Comment by ClementineHahn** [comment]
@melaniebmn to review last PR. 
@Lu-stack-art @ClementineHahn  to double check if that creates prompt for further assessment on issues raised during a11y testing (check what did we address and what did we not)
