### ISSUE TITLE
Design: Standard page templates

### ISSUE THREAD

**Issue by adorayi** [cds-snc/design-gc-conception#427]
Standard web page with header, footer, grid and whatever else is needed.

## Acceptance criteria

- [x] Template has header
- [x] Template has footer
- [x] Template has a body section that aligns with grid
- [x] Template grows to fill content
- [x] Layout with single column
- [x] Layout with side nav (won't do)
- [x] Mobile variant of all versions

## Done when

- [x] EN template is marked ready for dev
- [x] FR template is ready for merge
- [x] A [standard process](https://docs.google.com/document/d/1O-WXAlz5niqYbrXyKjN9MM5UKfCZLdmbJz6WtBGvRmQ/edit?usp=sharing) for designing templates is created and shared

## Deliverables

- [x] [EN template (opens in Figma)](https://www.figma.com/design/T0T9vUC8DghZEkP29X6ui3/Basic-Page-Template-%7C-ZH-427?node-id=30186-2206&t=t0jMDKxxwB2SNhXG-4)
- [x] [FR template (opens in Figma)](https://www.figma.com/design/84sAFVNJVjcLXWPMKrbJwi/Start-of-templates?node-id=2951-2995&t=AYhZQbE7RtTKevOd-4)

## Dev impact
**Yes** - Needs HTML equivalent (ticket)

## W.I.P.
[Basic Page (opens in Figma)](https://www.figma.com/design/T0T9vUC8DghZEkP29X6ui3/Basic-Page-Template-%7C-ZH-427?node-id=30173-2205)

**Comment by adorayi** [comment]
Template for the dental demo is available and should be used as a starting point.

**Comment by adorayi** [comment]
Since the search can be toggled on/off, we don't need to include different versions showing that.

**Comment by daine** [comment]
In the current Acceptance Criteria, there is an item for "Version with side nav" however upon discussion at dev/design sync today it seems it's something that still needs to be looked into. Could we add "Decide if we're proceeding with a version with a side nav" to the "Definition of done", so the devs know during handoff if it exists or not? TIA!

**Comment by daine** [comment]
Here is the working document on the proposed naming conventions for the standard page templates:
https://docs.google.com/document/d/1q4v397adKEHtWgDWUO3PG3jUl62D9RXMyThRASiHwEU/edit#heading=h.cp3wko3y7gcr

It also contains a mapping of existing templates from the source, to our proposed implementation.

**Comment by realdylanzheng** [comment]
@adorayi The templates rely on a [spacing component](https://www.figma.com/design/T0T9vUC8DghZEkP29X6ui3/Basic-Page-Template-%7C-ZH-427?node-id=30186-3536&t=sZGga27JjE1EcGwP-4) (concept only) to help designer more conveniently set varying space values between sections in a template. Currently we don't have a suitable or complete of this, requesting that we prioritize to formally create one.
