### ISSUE TITLE
Design: Ministerial profile page template

### ISSUE THREAD

**Issue by adorayi** [cds-snc/design-gc-conception#428]
## Acceptance criteria

- [x] The template meets all requirements specified in the [requirements document](https://docs.google.com/document/d/1iZnQH7-cTBS30wqa2LdhUu63yYIU-moL89NMAPMqMJg/edit?tab=t.0#heading=h.dzdv26uegc1o). 

## Definition of done

- [x] Templates are shared in ds-design-dev channel
- [x] Templates are reviewed and approved by designers
- [x] Guidance draft is handed off to content designers

## Deliverables
- [x] [EN template](https://www.figma.com/design/7HNtNYzWNmcxjYtG8UlnBz/Internal-assets?node-id=5306-6842&t=hs1MPDma3LpwwieW-4)
- [x] [FR template](https://www.figma.com/design/7HNtNYzWNmcxjYtG8UlnBz/Internal-assets?node-id=5346-15402&t=PCaBQXSGRRsCWvSx-4)
- [x] [Requirements document](https://docs.google.com/document/d/1iZnQH7-cTBS30wqa2LdhUu63yYIU-moL89NMAPMqMJg/edit?usp=sharing)
- [x] [Guidance (draft)](https://docs.google.com/document/d/1gINo1_84tBF1STY-ah7rIuqxrFDgHSM3ikqTazEvsQ0/edit?usp=sharing)

**Comment by RavinaSamaroo** [comment]
The GC design system Figma has this template already that we can use: https://www.figma.com/design/TodbPq5LF1G6l1E3Kx2qPP/GC-Design-Library?node-id=779-10465&t=b67gOinRD51Cq95E-0

**Comment by daine** [comment]
Hello, I've updated the ticket pairing for the development. As this is a currently existing template, could you confirm if we could proceed with implementation (development) prior to design completing this task? Here are the items that we may need to check with design (they are under the acceptance criteria):
- Prior to doing work, clarify scope of ticket with the designers and adjust if necessary
  - Check with DTO if there are upcoming changes (ask designers)
  - Check the figma design with the current published template
