### ISSUE TITLE
Pattern inventory

### ISSUE THREAD

**Issue by ioanacontu** [cds-snc/design-gc-conception#43]
In order to create new patterns, we need to investigate pattern needs and current uses of colour and typography, level of accessibility and to approach colour and typography using design tokens. 

________
### References: 
For some reference, in terms of documentation for WET-BOEW / GCWeb we have:
- WET-BOEW:  https://wet-boew.github.io/wet-boew/demos/index-en.html 
- GCWeb:  https://wet-boew.github.io/GCWeb/index-en.html 
- Styleguide:  https://wet-boew.github.io/wet-boew-styleguide/index-en.html  (no longer updated)

DTO now have a centralized pattern library that could be the way to go going forward, however that library and WET-BOEW / GCWeb needs to be aligned as there are missing pieces on both sides:  https://www.canada.ca/en/government/about/design-system/pattern-library.html 

And here I know that I am referring only to the web framework and not considering the whole Design system.

________
### More references: 

**A guide for how to systemize patterns:** 
https://docs.google.com/presentation/d/1siqFuyJ1qmf2MJM2jrBKLdpHfwa2f6WoAVmntEGDdDE/edit#slide=id.g4cea57f733_0_0

**Exploring design patterns with system and empathy maps:** 
https://docs.google.com/presentation/d/115oiRgvAv19OMncE9x9ev1C7a2cPmU43MetqGBw60WM/edit#slide=id.g9ab13c55ac_6_135

**Comment by delisma** [comment]
Overview of the inventory of GCWeb design element
https://www.projectwallace.com/~delisma/gcweb/branding

Recommendations for streamlining GCWeb design principles
https://www.figma.com/file/8189dLvqRAFIpPMbO32hbU/Foundations?node-id=0%3A1

**Comment by ioanacontu** [comment]
Moved this back in the Backlog. There will be no time for it this sprint. Also, it's still early to tackle this and might end up lower on our list of first priorities. TBD
