### ISSUE TITLE
Build Design: Topic page template

### ISSUE THREAD

**Issue by adorayi** [cds-snc/design-gc-conception#430]
[Reference template](https://servicecanada.github.io/wet-boew-demos/topic-template-demo/templates/topic/topic-en.html)

## Definition of done : 

- [x] Comparison with official policy, if case for deviation follow decision process 
- [x] Handoff design guidance to content design 
- [x] Update requirement doc as needed 
- [x]  [Name for page templates doc](https://docs.google.com/document/d/1q4v397adKEHtWgDWUO3PG3jUl62D9RXMyThRASiHwEU/edit?usp=sharing) is updated
- [x] Templates are shared in ds-design-dev channel
- [x] Templates are reviewed by designers
- [x] EN template is marked **Ready for dev**
- [x] FR template is ready for merge

### Acceptance criteria

- [x] The template meets all [functional requirements](https://docs.google.com/document/d/1X4WYcSiEl0jOgG8gx3RdWBbTWYhnInbvfU2Bx7nwyHY/edit#heading=h.oc9qsbbbq0gi) specified in [requirements doc](https://docs.google.com/document/d/1X4WYcSiEl0jOgG8gx3RdWBbTWYhnInbvfU2Bx7nwyHY/edit?usp=sharing).

## Deliverables

- [x] [Topic page guidance (draft)](https://docs.google.com/document/d/1TGHfEmc39yTncKFhixqwsD8HyW46qz07Ghfnj5VxjKU/edit?usp=sharing)
- [x] Requirement doc updated with final component decisions
- [x] Figma files not merge to main ready for merge
- [x] [Update component decisions ard archive (should always be applicable)-](https://www.figma.com/design/4wF8Kr9o2sGTQjaOpY7qcZ/Component-archive-%2B-decision-record?node-id=2387-5816&t=Awmv02AnZYrQDbET-4)
- [x] [EN template in Figma](https://www.figma.com/design/7HNtNYzWNmcxjYtG8UlnBz/Internal-assets?node-id=5186-54631&t=5iScFg9m5kOY2Rhq-4)
- [x] [FR template in Figma](https://www.figma.com/design/7HNtNYzWNmcxjYtG8UlnBz/Internal-assets?node-id=5186-54632&t=5iScFg9m5kOY2Rhq-4)

## Dev impact
**Yes** - Needs HTML equivalent

**Comment by RavinaSamaroo** [comment]
The GC design system Figma has this template already that we can use: https://www.figma.com/design/TodbPq5LF1G6l1E3Kx2qPP/GC-Design-Library?node-id=824-10202&t=b67gOinRD51Cq95E-0

**Comment by realdylanzheng** [comment]
@adorayi Do we intend to include/replicate aspects of the template that utilize components we don't have? For example **section title**, **image**, **social media links** etc

**Comment by realdylanzheng** [comment]
@adorayi we may also need to do work to standardize how we present mock or placeholder content within a template. Canada.ca (DTO) uses Lorem ipsum in their template examples whereas GCweb uses a combination of placeholder notation and proto-content.

**Comment by adorayi** [comment]
Keep lorem ipsum for now
Re: section title, image, social media links etc. let's solve for them in Figma as sub components, we could do some research to see if these would be useful as full fledged components.

**Comment by ClementineHahn** [comment]
@realdylanzheng can you tell me if this breakdown of the card could work ?
@SmartMouthWords as design lead I would need your review also

**Comment by realdylanzheng** [comment]
@ClementineHahn "Update Figma version" contradicts "ready for merge" (but not merged), screenreader testing is more effectively conducted on a coded template

**Comment by realdylanzheng** [comment]
There are styling differences between the [reference template](https://servicecanada.github.io/wet-boew-demos/topic-template-demo/templates/topic/topic-en.html) and the template produced using GCDS components, that result in a unique look and feel. 
Some differences include:
- Link font size
- Link text weight
- p font size
- section background colour

**Comment by SmartMouthWords** [comment]
Flagging today DTO released an [update to the topic page:](https://us15.campaign-archive.com/?e=__test_email__&u=729a207773f7324e217a1d945&id=76e6915683#francais) design, code, and guidance.

**Comment by adorayi** [comment]
@nmakuch @SmartMouthWords for review
