### ISSUE TITLE
Explore using Writer.com 

### ISSUE THREAD

**Issue by SmartMouthWords** [cds-snc/design-gc-conception#432]
Looking into Writer.com LLM as a writing tool for the design system team to help improve the documentation process. Writer may be able to improve consistency and efficiency of component documentation. 

- [x] Meet with a Writer rep
- [x] Schedule demo 
- [x] Start trial
- [x] Document assessment and recommendations for subscription or not

**Comment by SmartMouthWords** [comment]
[Overview video](https://writer.com/)
[Notes from discussion with CDS security and policy folks](https://docs.google.com/document/d/1EKNA2kAR30ZQ7BuHzMTzdYKEPZUSzFWG3JBUjuJCc54/edit#heading=h.fznljgm5qxxu)
[Notes from chat with Writer sales rep](https://docs.google.com/document/d/18qGmw91frCEmFcHWpxFTf2o1bkdvV2E77dHBDifv7og/edit)

**Comment by SmartMouthWords** [comment]
Demo scheduled for 22-Jun-2023

**Comment by ClementineHahn** [comment]
Demo happened. @SmartMouthWords will write the findings and collect the questions from the team . So far feedback are good. Expectations is that it could speed up writing and review part for repeatable pieces . Currently on trial, if no blokcers or concerns, we can go ahead on procure this.

**Comment by ClementineHahn** [comment]
Stretch goal : review to share writer.com  to share to team within the context of our own delivery work.

**Comment by SmartMouthWords** [comment]
- Installed chrome plugin
In Writer: 
- Added writing style rules
- Added half a dozen snippets
- Added all component names and a few other terms from the site in French and English with accepted versions and terms to avoid 

Next steps to experiment with component page reviews to see how much time is saved

**Comment by ClementineHahn** [comment]
After discussing with @SmartMouthWords , Parking this card into backlog until access is restored and it makes its way into prioritized backlog again

**Comment by SmartMouthWords** [comment]
Tried out Writer.com and was able to:
- Add style and terms rules for GC Design System to Writer.com. 
- Add common guidance on elements like labels, link text, about text.   

On Thursday 12-Oct-2023 showed how Writer helps find and fix mistakes in a document, flags incorrect and use-with-caution terminology and proposes approved terms in line with our rationale for the change. Also showed how snippets can be pulled in by typing keywords to save time on writing from scratch or searching through component guidance for text to re-use.

**Comment by SmartMouthWords** [comment]
@adorayi to review for recommendation for team licence.

**Comment by SmartMouthWords** [comment]
@samburtonCDS suggested using the Writer initiative to try out a new Saas process. @adorayi and I to meet with Sam, Sharly, and Cheyanne to work through and document privacy & security considerations for using Writer.com, for record-keeping and future reference.
