### ISSUE TITLE
Review the publishing process

### ISSUE THREAD

**Issue by adorayi** [cds-snc/design-gc-conception#437]
**What** : Review the process and workflow for publishing content to prod website.
- Get familiar with the process and tools
- Suggests any improvements as needed

**context** : 

**Done when** :
- [ ] card templates are created and updated (to relevant check box only)
- [ ] workflow with columns are updated in Zen hub 
- [ ] Known accountability for steps in the workflow
- [x] Slack share back to teams to collect feedback
- [x] demo at next review

**Comment by ClementineHahn** [comment]
Discuss the possibility of clarify roles and resp for each step of the workflow and specifically the last part ending up to a release. 
Potnetial release manager role that could turn each sprint , we could materialize this with a card or something else. To be discussed with team

**Comment by ClementineHahn** [comment]
Dependencies on something being ready for actual release and doc+ refactor along the way
