### ISSUE TITLE
Content: Date modified component

### ISSUE THREAD

**Issue by adorayi** [cds-snc/design-gc-conception#440]
**Summary:** Documentation of component guidance in EN for the Date modified component on the Design System website.
Including use cases, how to use guidance, accessibility guidelines and more.

**Linked to:** #439 #391

**Acceptance Criteria:**

- [x] Component Kickoff
- [x] Component review
- [x] Sync with Dev and Design
- [x] Research and consulting other design libraries
- [x] Component ID (name, definition, example image 
- [x] Use case (when to use guidance & related components)  
- [x] How to use guidance 
- [x] Accessibility guidelines
- [x] Inclusive language
- [x] Descriptive text for images
- [x] Translation & Localization
- [x] Bilingual review – content design
- [x] Ensure consistency: ordering, terminology, high level voice/tone/style 
- [x] Final review

**Comment by anikbrazeau** [comment]
@dylanzheng94 Curious, is there an existing link to draft documentation/guidance for this component?

**Comment by anikbrazeau** [comment]
### Reviewing English draft 👀 
https://docs.google.com/document/d/1Nv82XW30c0O2vrTHI7Baa18rFlBv8k72qeOVMQzSqEM/edit

**Comment by SmartMouthWords** [comment]
Reviewed changes to draft and made some updates

**Comment by SmartMouthWords** [comment]
Finalized review and sent to translation

**Comment by ClementineHahn** [comment]
expected to come back from Translation during Sprint 6

**Comment by anikbrazeau** [comment]
# ✅ Final bilingual content review complete
> **EN**: https://docs.google.com/document/d/1Nv82XW30c0O2vrTHI7Baa18rFlBv8k72qeOVMQzSqEM/edit
> **FR**: https://docs.google.com/document/d/1hpEzaE57FSS5jcmEYP0tUko-E6C9bXY2oGDhpQEgpug/edit#heading=h.gjdgxs

# 🚀 Ready for dev
> @ethanWallace @melaniebmn @dylanzheng94 @ClementineHahn

**Comment by melaniebmn** [comment]
PR to add date-modified guidance to the documentation site:

https://github.com/cds-snc/gcds-docs/pull/174
