### ISSUE TITLE
Content: Search

### ISSUE THREAD

**Issue by adorayi** [cds-snc/design-gc-conception#450]
**Summary:** Documentation of component guidance in EN for the Search component on the Design System website.
Including use cases, how to use guidance, accessibility guidelines and more.

**Acceptance Criteria:**

- [x] Component Kickoff
- [x] Component review
- [x] Sync with Dev and Design
- [x] Research and consulting other design libraries
- [x] Component ID (name, definition, example image 
- [x] Use case (when to use guidance & related components)  
- [x] How to use guidance 
- [x] Accessibility guidelines
- [x] Inclusive language
- [x] Descriptive text for images
- [x] Translation & Localization
- [x] Bilingual review – content design
- [x] Ensure consistency: ordering, terminology, high level voice/tone/style 
- [x] Final review

**Comment by anikbrazeau** [comment]
https://docs.google.com/document/d/1pF0kBHhWHbIKkT7UI3baIqfee1OiLOQ7A8Ft_CdHRw4/edit

**Comment by anikbrazeau** [comment]
Dylan finalizing content — a few questions/comments to resolve before sending to translation next week.

**Comment by anikbrazeau** [comment]
# Sent to translation (August 29, 2023)
> https://docs.google.com/document/d/1pF0kBHhWHbIKkT7UI3baIqfee1OiLOQ7A8Ft_CdHRw4/edit

cc @nchoquet @dylanzheng94 @ClementineHahn

**Comment by anikbrazeau** [comment]
## Received from translation

### Doing a bilingual content review (cc @SmartMouthWords)

> **EN** https://docs.google.com/document/d/1pF0kBHhWHbIKkT7UI3baIqfee1OiLOQ7A8Ft_CdHRw4/edit
> **FR** https://docs.google.com/document/d/102aVLahaYPk_IYIR4XZc3LjZWad0_0frLrhOEdIJsaU/edit

**Comment by anikbrazeau** [comment]
## Revisiting based on need to sort out difference with Canada.ca guidance which would need to be documented

- Canada.ca site search box documentation: https://design.canada.ca/common-design-patterns/search-box.html
- Requirements: https://docs.google.com/document/d/1Z-FlOlbxxF8-t2LpyJQulIyG0kj2Y_MaRcudLP0n7tg/edit
- Kickoff: https://docs.google.com/document/d/1FobCGZDc2UAayIflAvbD0KMSyys1W-wvwVAqDi9POBU/edit#heading=h.x3k5wtsce0hl
- Dev/Design sync: https://docs.google.com/document/d/1ZshJZZ4apf-jAfwrTX512egTHKkbTWFdQpd_yHt8VW8/edit
- Documentation: https://app.zenhub.com/workspaces/design-system-6100624a19f4cf000e46e458/issues/gh/cds-snc/design-gc-conception/450

**Comment by anikbrazeau** [comment]
# ✅ Final bilingual content review complete

# 🚀 Ready for dev
>  - **EN**: https://docs.google.com/document/d/1pF0kBHhWHbIKkT7UI3baIqfee1OiLOQ7A8Ft_CdHRw4/edit
>  - **FR**: https://docs.google.com/document/d/102aVLahaYPk_IYIR4XZc3LjZWad0_0frLrhOEdIJsaU/edit

CC @ethanWallace @melaniebmn @dylanzheng94 @SmartMouthWords @ClementineHahn

**Comment by anikbrazeau** [comment]
SHIPPED!
