### ISSUE TITLE
Content updates to header/footer as we have now top nav ready 

### ISSUE THREAD

**Issue by ClementineHahn** [cds-snc/design-gc-conception#455]
https://design-system.alpha.canada.ca/en/components/header/
https://design-system.alpha.canada.ca/en/components/footer/

**Updates needed with new slot name:**

- [x] Figma library
- [x] Anatomy
- [x] Guidance

**Comment by SmartMouthWords** [comment]
Review existing header and footer website content to apply changes from the Top nav components.

**Comment by anikbrazeau** [comment]
@SmartMouthWords where's the latest source of truth -- should we base on Figma or recreate what's live on website?

**Comment by SmartMouthWords** [comment]
Will also need to update the Figma library with the new terminology. 
Update to anatomy and guidance to the new slot name.

**Comment by SmartMouthWords** [comment]
@melaniebmn will add links or screenshots to updated term and sections in English

**Comment by melaniebmn** [comment]
We decided to rename the `topnav` slot to `skip-to-nav`. Here are screenshots of the English guidance where it has been updated:

![Screenshot 2023-08-03 at 1.47.12 PM.png](https://images.zenhubusercontent.com/620163ddfc3b6d028ba2c1a7/37d00331-6f23-462e-be12-846172a91b2d)![Screenshot 2023-08-03 at 1.48.08 PM.png](https://images.zenhubusercontent.com/620163ddfc3b6d028ba2c1a7/461cb0f3-bfbe-4910-9bae-f7b6d3cf9f0b)

**Comment by anikbrazeau** [comment]
# Proposed updates in French
@melaniebmn @SmartMouthWords 

 ## Header anatomy 
- **EN**: The **skip-to-nav** slot includes the skip-to-content button to let a person bypass a cluster of navigation links and jump to the main page content.
- **FR**: L'emplacement **« skip-to-nav »** comprend le bouton « Passer au contenu » qui permet à une personne de sauter un ensemble de liens de navigation et ainsi passer au contenu de la page principale.

 ## Include the skip-to-content button

### Second bullet
- **EN**: Use the `skip-to-nav` slot to replace the default top navigation with the `skip-to-content` link.
- **FR**: Utilisez l'emplacement `skip-to-nav` pour remplacer la navigation supérieure par défaut par le lien `skip-to-content` « Passer au contenu ». 

### Third bullet
- **EN**: Pass a child element with the `slot="skip-to-nav"` attribute to place the element first in the header.
- **FR**: Passez un élément enfant avec l'attribut `slot="skip-to-nav"` pour placer l'élément en première position dans l'en-tête.

## Add optional element to your header

### Fourth bullet
- **EN**: Add a banner by passing a child element with the `slot="banner"` attribute. This will plaec the element across the top of the header under the `skip-to-nav` element.
- **FR**: Ajoutez une bannière en faisant passer un élément enfant avec l'attribut `slot=”banner”`. Cela placera l'élément en haut de l'en-tête sous l'élément `skip-to-nav`.

No updates needed to **Footer** component documentation.

**Comment by melaniebmn** [comment]
@anikbrazeau the text should be updated everywhere now. Can we close this issue?

**Comment by anikbrazeau** [comment]
COMPLETE!
