### ISSUE TITLE
Ensure header component is up to date in figma

### ISSUE THREAD

**Issue by adorayi** [cds-snc/design-gc-conception#457]
To Do:
- [x] Ensure header subcomponents fit into the new grid system (internal assets)
- [x] Make sure the mobile variants for the header subcomponents are up to date and fit in the new grid system. (internal assets)
- [x] Publish the changes so they can be accessed in the main file (internal assets).
- [x] Make sure the mobile variant for the main header is pulling in the new changes.
- [x] Make sure this components aligns properly with Footer component on large and small screens after changes.

**Comment by nmakuch** [comment]
Header + Footer Branch for review

https://www.figma.com/file/mh2maMG2NBtk41k1O1UGHV/branch/UunlAOOFqYCYbwG4G0ALcA/Canadian-Digital-Service%E2%80%A8---GC-Design-System?type=design&node-id=2043-5684&mode=design&t=n5723dHCNqcRmRVa-0

**Comment by nmakuch** [comment]
subcomponent work 
https://www.figma.com/file/7HNtNYzWNmcxjYtG8UlnBz/Internal-assets?type=design&node-id=301-5230&mode=design&t=0BBb2vxCOLIj0Bm3-0
