### ISSUE TITLE
Dev: Typography updates based on decisions from mandatory alignment project

### ISSUE THREAD

**Issue by adorayi** [cds-snc/design-gc-conception#460]
As a dev I want the tokens and dev packages reflecting the lates typo decisions . Therefore based on the decisions from the typography alignment discussions with DTO, changes should be applied in code for consistency.
Related to issue #1219

**Done when** 
- [x] changing the tokens to apply new typo specs 
- [x] updating calculations for line height and spacing 
- [x] identifies components that need manually updating out of header and footer changes (new padding) 

**Acceptance criteria**
- [x] reviewed by 1 dev
- [x] reviewed by 1 designer for design changes and ticket completion on header/footer changes 

** Out of scope **
- [x] #1274

**Comment by daine** [comment]
Done & has been released
