### ISSUE TITLE
Indexing content on the website for searching

### ISSUE THREAD

**Issue by adorayi** [cds-snc/design-gc-conception#464]
Spreadsheet started: 
https://docs.google.com/spreadsheets/d/1gdbLXUYSDffyYFrQFZFyZ7uI3jg49h728Zk4PwJ3jHI/edit?usp=sharing

Contains keywords for each page and URL.
Also contains recommended sections to exclude when using a tool like PageFind.

**Comment by anikbrazeau** [comment]
Duplicate of #471

**Comment by SmartMouthWords** [comment]
Possible way to proceed: 
- Running a web scraper to pull out all the headings and pages
- Farming the content from the definition, other names, and anatomy sections for keywords: https://docs.google.com/spreadsheets/d/1B57hJZHwxsleHVweisIkJOCKLNenJTCtZjx84KwyvoI/edit#gid=0
- Combining the two for an index
