### ISSUE TITLE
Publish: Search doc

### ISSUE THREAD

**Issue by dylanzheng94** [cds-snc/design-gc-conception#470]
_Ensure component has been distributed before publishing to the website._

**Comment by ClementineHahn** [comment]
@ethanWallace to give final review and ok to @SmartMouthWords on the content then go to publish

**Comment by ClementineHahn** [comment]
Guidance for component published and available here https://design-system.alpha.canada.ca/en/components/search/[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdkRNIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--ef0338fa1d88921b776a0cf21be3006853d0c04d/Screenshot%202023-09-22%20at%204.25.05%20PM.png)
