### ISSUE TITLE
Update components in "Coming soon" section

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/design-gc-conception#471]
# User story

As a user, I want to know what's being worked on and added to the GC Design System, so I can know what to expect and plan my work.

https://design-system.alpha.canada.ca/en/coming-soon/
https://docs.google.com/document/d/1skMpAKAd2fm9Oiv3flAG7HKEg9u0yH04p_Py5_hzlvY/edit

---

# Components

## Heading
   - [x] Text in EN
   - [x] Image / alt text in EN
   - [x] Text in FR

## Text
   - [x] Text in EN
   - [x] Image / alt text in EN
   - [x] Text in FR
 
## Search
   - [x] Text in EN
   - [x] Image / alt text in EN
   - [x] Text in FR
  
## Data table
   - [x] Text in EN
   - [x] Image / alt text in EN
   - [x] Text in FR
   
## Alert
   - [x] Text in EN
   - [x] Image / alt text in EN
   - [x] Text in FR
   
## Image
   - [x] Text in EN
   - [x] Image / alt text in EN
   - [x] Text in FR
   
## Visually hidden
   - [x] Text in EN
   - [x] Image / alt text in EN
   - [x] Text in FR

---

# Components already there
- Icon
- Grid
- Pagination

# Other components we might to consider adding:
- Banner
- Theme and topic menu
- Date selector
- Tabs
- Toggle

# Also potentially patterns.. ?

**Comment by anikbrazeau** [comment]
# Sent to translation (August 30, 2023)
> https://docs.google.com/document/d/1skMpAKAd2fm9Oiv3flAG7HKEg9u0yH04p_Py5_hzlvY/edit

cc @nchoquet @melaniebmn  @ClementineHahn

**Comment by anikbrazeau** [comment]
# ✅ Final bilingual content review complete

# 🚀 Ready for dev
>  - **EN**: https://docs.google.com/document/d/1skMpAKAd2fm9Oiv3flAG7HKEg9u0yH04p_Py5_hzlvY/edit
>  - **FR**: https://docs.google.com/document/d/16QO8GIZWRXtzRodnoDdPB69eupbOegcMEYitoYvyalI/edit

CC  @melaniebmn @SmartMouthWords @ClementineHahn

**Comment by anikbrazeau** [comment]
# ✅ Final bilingual content review complete

# 🚀 Ready for dev
>  - **EN**: https://docs.google.com/document/d/1skMpAKAd2fm9Oiv3flAG7HKEg9u0yH04p_Py5_hzlvY/edit
>  - **FR**: https://docs.google.com/document/d/16QO8GIZWRXtzRodnoDdPB69eupbOegcMEYitoYvyalI/edit

CC  @melaniebmn @SmartMouthWords @ClementineHahn

**Comment by melaniebmn** [comment]
The coming soon section has been updated.
