### ISSUE TITLE
Content - Theme and Topic Menu component

### ISSUE THREAD

**Issue by adorayi** [cds-snc/design-gc-conception#476]
**Summary:** Documentation of component guidance in EN for the Theme and Topic Menu component on the Design System website.
Including use cases, how to use guidance, accessibility guidelines and more.

**Acceptance Criteria:**

- [x] Component Kickoff
- [x] Component review
- [x] Sync with Dev and Design
- [x] Research and consulting other design libraries
- [x] Component ID (name, definition, example image 
- [x] Use case (when to use guidance & related components)  
- [x] How to use guidance 
- [x] Accessibility guidelines
- [x] Inclusive language
- [x] Descriptive text for images
- [x] Translation & Localization
- [x] Bilingual review – content design
- [x] Ensure consistency: ordering, terminology, high level voice/tone/style 
- [x] Final review

**Comment by anikbrazeau** [comment]
https://docs.google.com/document/d/1AmEBbirlyw6ZuhOHn-vOaNz1z72wZICdn_lWLXjEuKs/edit

**Comment by ClementineHahn** [comment]
Documentation started by @ethanWallace , @adorayi warns about the potential big scope of navigation, so lets reuse what's out there and keep it focused on the current use case

**Comment by anikbrazeau** [comment]
## Received from translation

Doing a bilingual content review (cc @SmartMouthWords)

> **EN** https://docs.google.com/document/d/1AmEBbirlyw6ZuhOHn-vOaNz1z72wZICdn_lWLXjEuKs/edit
> **FR** https://docs.google.com/document/d/1SMUN6YLd_FQXGU2JDw454LmueOGaE1TAC6hiBWMpScU/edit

**Comment by anikbrazeau** [comment]
## Update
- A few final tweaks to content for clarity on Monday with Ethan/Amy.
- Now, in final final French review with Nicholas. Expected to be ready to ship on Tuesday.

**Comment by SmartMouthWords** [comment]
Updated docs are ready for publishing. 
FR: [](https://docs.google.com/document/d/1SMUN6YLd_FQXGU2JDw454LmueOGaE1TAC6hiBWMpScU/edit)
EN: [](https://docs.google.com/document/d/1AmEBbirlyw6ZuhOHn-vOaNz1z72wZICdn_lWLXjEuKs/edit)
