### ISSUE TITLE
Update the Featured component to display "top nav" instead of Fieldset

### ISSUE THREAD

**Issue by ClementineHahn** [cds-snc/design-gc-conception#490]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcW9iIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--3c69900b27d261e99a2965c8b3788e9884e8c979/Screenshot%202023-08-18%20at%205.10.51%20PM.png)

**Comment by melaniebmn** [comment]
The featured component has been updated to "top nav".
