### ISSUE TITLE
Site only search

### ISSUE THREAD

**Issue by adorayi** [cds-snc/design-gc-conception#493]
Site only search Using a combination of 11ty serverless ondemand template builder and https://www.belter.io/eleventy-search/, we could build a search page. 11ty serverless allows us to create pages on demand so search result could be generated based on a query using Elasticlunr. 11ty serverless example  For this to work we would need to update the frontmatter for every component page to include extra details and make sure our page titles are unique(they could use some work).

- [ ] Update pages
- [ ] Design and info display of search results
- [ ] Implementation

**Comment by daine** [comment]
A few options for our search are the following:
- Elasticlunr (as indicated in the original ticket)
- Pagefind - another good solution to look into
