### ISSUE TITLE
Documenting releases and dev processes for future onbaording and baseline for iteration 

### ISSUE THREAD

**Issue by ClementineHahn** [cds-snc/design-gc-conception#497]
this is a time boxed activity. 
Main goal is to enable future Dev onabording , in this case , Daine on September 11th .

**Comment by ClementineHahn** [comment]
@melaniebmn @ethanWallace could add the link of the doc in this card ? 
Thank you !

**Comment by melaniebmn** [comment]
The new resources can be found here:

https://drive.google.com/drive/folders/1iVxqhXWV7azVhrepMeisZr5JCP4EjuUL

**Comment by melaniebmn** [comment]
The new resources can be found here:

https://drive.google.com/drive/folders/1iVxqhXWV7azVhrepMeisZr5JCP4EjuUL
