### ISSUE TITLE
Prep next phase of research based on last phase Conclusions

### ISSUE THREAD

**Issue by ClementineHahn** [cds-snc/design-gc-conception#501]
Done when : 

- Identify the next focus for fable
- Define more clearly research questions for  "what are barriers to adoption for DS in GC space " 
- Get draft on privacy/ consent forms for intended interview with PS before Sarah is on mat leave 🤞

**Comment by Lu-stack-art** [comment]
Draft round 2 testing-of Fable goals
Collect data (locate patterns) on accessibility and usability insights from multiple single assistive technology users 

Uncover barriers in your experience and understand their impact on assistive technology users

Observe distinctions between the first round of testing, and the second

Uncover what is bias and repetition, versus individual feedback 

Learn new user experience/feedback on new components applied in second round of testing

What methodologies will be used? 

Self guided guided tasks : 1 request (screen magnification)

Compatibility testing : 1 request (2 alt navigation, 1 screen reader, 2 screen magnification)

Prototype : 3 request (1 screen magnification, 1 alternative navigation)

Focus on documentation/DS webpage navigation, testing new components. 
*different from first round, apply similar structure with new content (find patterns on usability), as repetition is necessary to collect more accurate data on user experiences on the assistive techs applied

_In the same doc, describe the high priority components we want to tackle
This will be based on your discussion with dev/designers (narrowing in on which new components to test, and what medium level priorities we want to focus on this round_

Objectives : Round 2 with Fable testing is meant to re-test and find the patterns on assistive technologies that has been tested in the first round of testing. Purpose of repetition is to compare distinction between different users experience with our product, and collect more data. Testing more on new tools, and components applied on the webpage, along with testing the accessibility of our webpage navigation, and learn what needs to be iterated on.
