### ISSUE TITLE
Release notes page update

### ISSUE THREAD

**Issue by ClementineHahn** [cds-snc/design-gc-conception#502]
## Consider linking to Changelog instead of empty page for [Release notes](https://design-system.alpha.canada.ca/en/release-notes/)

![image](https://github.com/cds-snc/design-gc-conception/assets/38330843/f86604b1-825c-41a9-b5ce-7fa46cacf0a7)

**Comment by melaniebmn** [comment]
PR to make the change:
https://github.com/cds-snc/gcds-docs/pull/209
