### ISSUE TITLE
French translation: change log 

### ISSUE THREAD

**Issue by SmartMouthWords** [cds-snc/design-gc-conception#503]
**Acceptance Criteria:**

- [ ] Translation & Localization
- [ ] Bilingual review – content design
- [ ] Decide on layout of bilingual page content
- [ ] Publish to GitHub

**Comment by SmartMouthWords** [comment]
[Change log English content](https://github.com/cds-snc/gcds-components/blob/main/CHANGELOG.md)

**Comment by SmartMouthWords** [comment]
Discussed with Nicholas yesterday and he's working on it

**Comment by adorayi** [comment]
@SmartMouthWords @nchoquet  what is the status of this?

**Comment by daine** [comment]
@SmartMouthWords Will this issue help in terms of getting notified when the changelog is updated?
- #722

**Comment by adorayi** [comment]
Add to process change proposal @adorayi @ClementineHahn
