### ISSUE TITLE
Development of the Link component

### ISSUE THREAD

**Issue by adorayi** [cds-snc/design-gc-conception#506]
Develop on component branch, push to staging and push to prod when approved.

**Acceptance Criteria:**

- [x] Component kickoff
- [x] Sync with Design
- [x] [Requirements documentation](https://docs.google.com/document/d/1d717T3S6J3qhq58jXTQ5cBuPfJMp2WWftfaU_imu81A/edit#heading=h.a4c96ooxjacj)
- [x] Requirements doc: Consider edge cases
- [x] Requirements doc: Describe component properties
- [x] Review of requirements doc
- [x] Develop the component according to the requirements doc and design specs
- [x] Add component to storybook
- [x] [Write draft of dev guidance](https://docs.google.com/document/d/1hVmy8mPts5kMvM1Vz-nShS-zUXrvsvIN3wAdxMwVdaY/edit)
- [ ] Sync dev properties with Figma properties (design + dev) ([Figma component](https://www.figma.com/file/mh2maMG2NBtk41k1O1UGHV/Canadian-Digital-Service%E2%80%A8---GC-Design-System?type=design&node-id=2646-8407&mode=design&t=siG29FMc0Iz2Y24G-0))
- [ ] Handoff from draft dev guidance to documentation author/lead
- [ ] WCAG Goal can be completed using a screen reader.
- [x] WCAG Visual elements observe color contrast requirements.
- [x] WCAG Manual accessibility testing meets WCAG 2.1 AA requirements.
- [x] Provides equal service in French and English.
- [x] Comparison with official policy, documented reasons for deviation if any
- [ ] Final sync with Design
- [ ] [Policy review](https://www.figma.com/file/p0eiLxdme1g93sIuggjipR/Colour-%26-typography-differences-GCDS-vs.-Canada.ca?type=design&node-id=0-1&t=kkavFCQ74dMoZw6V-0)
- [ ] Code review
- [ ] After PR approval, merge component to staging
- [ ] Review from Design
- [ ] Review from Policy
- [ ] Note: reviews could be done on Storybook staging
- [ ] Push to prod

**Comment by samburtonCDS** [comment]
### Policy considerations

**MANDATORY COLOURS**
The Canada.ca design system specifies mandatory colours for link text, selected links, and visited links.

The GCDS team confirms the intention to comply with those mandatory colours [in the GCDS policy review](https://www.figma.com/file/p0eiLxdme1g93sIuggjipR/Colour-%26-typography-differences-GCDS-vs.-Canada.ca?type=design&node-id=0-1&mode=design&t=c493SYaBxiPTGsSH-0).

Mandatory colours are:
- default link: #2b4380
- selected link (on hover or focus): #0535d2
- visited link: #7834bc

There are no other mandatory elements related to this component in the Canada.ca design system.

**RECOMMENDATION: DOCUMENT DECISIONS**
I recommend that we proactively document significant design decisions (eg. why we use icons to identify with certain types of links and how we chose the images) so we can easily explain our recommendations to potential users.
- This may already be part of your workflow, in which case you can ignore this suggestion :) 
- If this would be a new and/or additional task, I’m happy to help!

**Resources from canada.ca design system that may be useful to review**

Overall, the canada.ca design system does not use or recommend icons to designate certain kinds of links.

- [Canada.ca style guide entry on **links**](https://design.canada.ca/style-guide/#toc11): research-based recommendations for when and how to use links. Contains guidance related to this component, such as "write email addresses in full, in lower case and as active links: (contact [helpdesk@canada.ca](https://design.canada.ca/style-guide/#wp7-2))"
- [Canada.ca style guide entry on **capitalization & punctuation**](https://design.canada.ca/style-guide/#wp4-1): Contains guidance related to this component, such as "Use lower case for a link in a sentence, unless the link contains a proper name."
- [Canada.ca blog: **3 steps to making links more effective**](https://blog.canada.ca/2021/07/20/effective-links): guidance on how to write effective links
- [Canada.ca blog: **a case for descriptive link text**](https://blog.canada.ca/2020/05/26/descriptive-link-text.html): results of an A/B test leading to recommendations about the most effective text for links
- The Canada.ca design system also contains several optional patterns and templates related to links: [download links pattern](https://design.canada.ca/common-design-patterns/download-links.html); [related links pattern](https://design.canada.ca/common-design-patterns/related-links.html); [in-page table of contents pattern;](https://design.canada.ca/common-design-patterns/in-page-toc.html) [index pages template](https://design.canada.ca/recommended-templates/pages-index.html); [services and information template](https://design.canada.ca/common-design-patterns/services-information.html);

**Comment by daine** [comment]
I have a [PR open here](https://github.com/cds-snc/gcds-components/pull/305)

At the moment, here's what the different links would look like:
<img width="713" alt="Screenshot 2023-10-19 at 10 26 20 AM" src="https://github.com/cds-snc/design-gc-conception/assets/916044/b20336c0-44b4-492f-a1e6-57707c98281c">
