### ISSUE TITLE
Connect GCDS metrics to the Platform client metrics

### ISSUE THREAD

**Issue by ClementineHahn** [cds-snc/design-gc-conception#514]
- [x] Site Traffic
- [ ] Server Logs
- [x] Code package downloads
- [x] CDN activity
- [ ] Figma analytics
- [ ] GitHub Dependents - how many repos across government are using the DS Front end?
 

Figma analytics is only for internal org users (CDS), however, perhaps the community file can provide some insight into external users.
What are server logs and what info will they provide?
What are Github dependents and what insight will they provide?

**Comment by brockhigg10** [comment]
Possibilities:

- Site Traffic
- Server Logs
- # times code packages downloaded
- Use of Figma (export?)
- GitHub Dependents - how many repos across government are using the DS Front end?

**Comment by adorayi** [comment]
@daine what are server logs and github dependents and what insights will they help us get?
Figma analytics will review another time.

**Comment by adorayi** [comment]
Github dependencies can be an epic on its own. It will show how many public repos are using GCDS packages.
