### ISSUE TITLE
Improve DS Support Process

### ISSUE THREAD

**Issue by adorayi** [cds-snc/design-gc-conception#516]

**Comment by brockhigg10** [comment]
In collaboration with CDS Platform Support team, define a support model for GCDS.

This should consider the users needs of:

- **Getting Help** with system features and tools of GCDS.
- **Submitting a Defect** when features behave unexpectedly or lack quality.
- Requesting a (Compliance?) Review emerging work to discern if a solution aligns or complies with standards. (even if our team doesn't do that)

This work should also produce:

- Messaging and training for Platform Support staff
- Service Level Agreement
- Definition of Support Channels (website, email, github, slack, etc.)
