### ISSUE TITLE
Create an initial draft for the proposed DS engagement strategy and gather initial feedback

### ISSUE THREAD

**Issue by ioanacontu** [cds-snc/design-gc-conception#52]
Draft document can be found here: 
https://docs.google.com/document/d/1qnxRpVYnhLgNABlX9l0EgacAT9CbExDJoRUOvve7o9w/edit#

**Comment by ioanacontu** [comment]
Structured based on 2 goals: 
1) to promote the product (design system)
2) support/educate the GC Digital community using the product

**Comment by ioanacontu** [comment]
Split into 3 docs based on 3 pillars: 
1) engagement plan
2) contribution model (depends on product and guidance) 
3) onboarding (depends on product and guidance)

**Comment by ioanacontu** [comment]
looking for feedback on it. Add comments in the docs.

**Comment by ioanacontu** [comment]
Should we include more around experimentation in the engagement plan?

**Comment by ioanacontu** [comment]
In progress.

**Comment by ioanacontu** [comment]
Depends on the vision and mission. @ioanacontu to have a look this week. 
A meeting to be organized - we'll "finalize" during that meeting. 
Looking for some action items.

**Comment by arianna-merritt** [comment]
**Next steps:**
- Laura, Peter and I have a 1-1 to tighten it up. 

- Also, having a 1-1 with Sam to chat about it

- Then we are going to book a group working session where anyone can join and we can all work through it.

**Comment by arianna-merritt** [comment]
@adeyfarah to set up a board/chart to help show what are the things in the engagement plan that can happen right away vs need more infos vs depend on a product item vs can happen later etc.

**Comment by mcman12** [comment]
@arianna-merritt moving this card to done as initial engagement is done.
Moving new checklist here: https://app.zenhub.com/workspaces/design-system-6100624a19f4cf000e46e458/issues/cds-snc/design-gc-conception/66
