### ISSUE TITLE
Design - v1 Data Table component

### ISSUE THREAD

**Issue by adorayi** [cds-snc/design-gc-conception#524]
**Summary:** Design of the Data Table component. 
Design on component branch and push to main Figma file when approved.

**Definition of done:**

- [x] Component Kickoff
- [x] Sync with Dev and Design
- [x] Research and consulting other design libraries
- [x] WCAG Goal can be completed using a screen reader.
- [x] WCAG Visual elements observe color contrast requirements.
- [ ] WCAG Manual accessibility testing meets WCAG 2.1 AA requirements.
- [x] Provides equal service in French and English.
- [x] Comparison with official policy, documented reasons for deviation if any
- [ ] Design review
- [x] [Policy review](https://www.figma.com/file/p0eiLxdme1g93sIuggjipR/Colour-%26-typography-differences-GCDS-vs.-Canada.ca?type=design&node-id=0-1&t=kkavFCQ74dMoZw6V-0)
- [x] Design - Different screen sizes
- [ ] Design - Short content / long content (text overflow etc.)
- [ ] Design - Error state (if applicable)
- [ ] Design - Empty state (if applicable)
- [ ] Component anatomy
- [ ] Handoff from draft dev guidance to documentation author/lead
- [ ] Update Figma version

**Acceptance Criteria**
- [x] The table supports sort by column
- [x] The table supports sort direction
- [x] The table supports filtering
- [ ]  The table supports column hiding
- [ ]  The table supports column reordering
- [ ]  The table supports batch actions via select
- [x] The table supports pagination

**Comment by adorayi** [comment]
https://design.canada.ca/common-design-patterns/tables.html

**Comment by ClementineHahn** [comment]
25% of the way through but there is still the 50% of the mobile to cover and the laptop part. So its gonna overlap next sprint
