### ISSUE TITLE
Initial discussion with SRE/Tech Ops

### ISSUE THREAD

**Issue by daine** [cds-snc/design-gc-conception#531]

**Comment by adorayi** [comment]
Initial discussion with the devs @ethanWallace @melaniebmn and Daine.
Discussion with Pat and SRE team.
- Goal: a decision on how to proceed, direction, tech etc.

**Comment by daine** [comment]
Met with Pat, Calvin along with Melanie, Ethan and David E
Going to proceed with using AWS Amplify with an API background next week
I'm going to need to write an ADR for the requirements and the decision as discussed

**Comment by daine** [comment]
Here is the ADR (architecture design record): https://docs.google.com/document/d/1Pv6stEuQyU_z3eYi4gqd8sbGKr9qQptZsPg9f3UiYkM/view
