### ISSUE TITLE
Content update of website: about GC Design System

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/design-gc-conception#544]

**Comment by SmartMouthWords** [comment]
Update about content to be more welcoming:
- intranet
- homepage
- about
- installation

**Comment by SmartMouthWords** [comment]
Two options for update of website content about GC Design System: 
[Figma mockups](https://www.figma.com/file/nfpEteHyEJ9dhJ2YvuvLeo/Documentation-site%2FComponent-Pages?type=design&node-id=11033%3A2281&mode=design&t=XultRhrXcT0q8keg-1 )

**Comment by SmartMouthWords** [comment]
The about content is ready to be published.

A couple notes:

- This update splits the About us and Contact us page into 2 pages, introducing a new page in the site architecture. The About us page is linked from the homepage hero and from the Contact us page. Many areas on the site currently point to the Contact page.

- The top nav menu items have changed order and "Foundations" is now called "Styles" – I didn't include the token overview page title change in the mockups but one of use will have to make that change too.       

- Changes are in pink text – Although the About us page is pretty well all net new. 

- The first couple pages are on the CDS intranet – I can take care of updating the WordPress.
