### ISSUE TITLE
Content: Heading component

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/design-gc-conception#545]
Including use cases, how to use guidance, accessibility guidelines and more.

**Acceptance Criteria:**

- [x] Component Kickoff
- [x] Component review
- [x] Sync with Dev and Design
- [x] Research and consulting other design libraries
- [x] Component ID (name, definition, example image 
- [x] Use case (when to use guidance & related components)  
- [x] How to use guidance 
- [x] Accessibility guidelines
- [x] Inclusive language
- [x] Descriptive text for images
- [x] Translation & Localization
- [x] Bilingual review – content design
- [x] Ensure consistency: ordering, terminology, high-level voice/tone/style 
- [x] Final review

**Comment by anikbrazeau** [comment]
# First English review done, made edits and left comments

https://docs.google.com/document/d/10gdv95JSvAwv02lIiQaYAuaA_-uoiGjyQXcMB1LBHUU/edit

**Comment by SmartMouthWords** [comment]
Reviewed, made comments and reworked some of the text. Added some content guidance. 

Did a walkthrough of changes with @nchoquet who'll review next.

**Comment by SmartMouthWords** [comment]
@nchoquet has reviewed and we've walked through the content earlier this week. Some async exchanges happening. Design and code guidance sections still need refinement. 
@melaniebmn is suggesting a possible new section. 
Planning to meet with @nmakuch and @melaniebmn next week to clarify some pieces and make some decisions.

**Comment by SmartMouthWords** [comment]
Reviewed and updated content yesterday and did another review this morning.

**Comment by SmartMouthWords** [comment]
[Heading draft ](https://docs.google.com/document/d/10gdv95JSvAwv02lIiQaYAuaA_-uoiGjyQXcMB1LBHUU/edit)ready for your review and translation @nchoquet

**Comment by SmartMouthWords** [comment]
Heading docs ready to be published! Adding [French version here ](https://docs.google.com/document/d/1XyIhrrEZNuEj9NjFIlfgnDaVvDE-uXIatAD28DftaV0/edit))for reference.

**Comment by melaniebmn** [comment]
Guidance added to documentation site in PR [#269](https://github.com/cds-snc/gcds-docs/pull/269).

**Comment by delisma** [comment]
DTO has a pull request in the GCWeb repository on GitHub. The pull request, numbered 2169, is related to updating the Heading component with the new H1 design. It should be released with the new version of GCWeb (v14.5). You can find more details about this pull request by visiting the following link: [GCWeb Pull Request #2169](https://github.com/wet-boew/GCWeb/pull/2169).

**Comment by delisma** [comment]
Also, DTO has a temporary guidance update about the new H1 style in Typography that is pending to be published. Access to the preview of this update is at the following link: [Temporary Guidance Update in Typography](https://deploy-preview-395--design-system-canada-ca.netlify.app/styles/typography).

DTO is interested in having a separate guidance for headings from typography, that pulls content from the GCDS Heading documentation. This would ensure consistency and alignment with the official guidelines.
