### ISSUE TITLE
Content: Text component

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/design-gc-conception#546]
Including use cases, how to use guidance, accessibility guidelines and more.

**Acceptance Criteria:**

- [x] Component Kickoff
- [x] Component review
- [x] Sync with Dev and Design
- [x] Research and consulting other design libraries
- [x] Component ID (name, definition, example image 
- [x] Use case (when to use guidance & related components)  
- [x] How to use guidance 
- [x] Accessibility guidelines
- [x] Inclusive language
- [x] Descriptive text for images
- [x] Translation & Localization
- [ ] Bilingual review – content design
- [ ] Ensure consistency: ordering, terminology, high-level voice/tone/style 
- [ ] Final review

**Comment by anikbrazeau** [comment]
## First English review done, made edits and left comments

https://docs.google.com/document/d/19mc3lGeW92Co9VdjnbV4g9U9kYh9P0_Lw5-s08nMDD8/edit

**Comment by SmartMouthWords** [comment]
Reviewed, made comments and reworked some of the text. Added some content guidance.

**Comment by SmartMouthWords** [comment]
Working on two guidance sections on what to include in text component content. Pulled in some content from error message component design guidance. Made a Slack post in #content-designers Slack channel to ask for contributions from the content design community of practice. https://gcdigital.slack.com/archives/CJGDB0TQV/p1699024935219149

**Comment by SmartMouthWords** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0tmQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--523c7bc8a276df4f37e2c05b461fcc287c19dcef/Content%20Design%20CoP%20question%202023-11-03%20at%2011.25.26%E2%80%AFAM.png)

**Comment by SmartMouthWords** [comment]
[Document](https://docs.google.com/document/d/19mc3lGeW92Co9VdjnbV4g9U9kYh9P0_Lw5-s08nMDD8/edit) ready for translation @nchoquet

**Comment by SmartMouthWords** [comment]
Translation's back. @CelesteCote doing the bilingual review.

**Comment by CelesteCote** [comment]
Reviewing now. And dropping the link to the French version here for handy reference: https://docs.google.com/document/d/1CXsORRPK7ELQoktblhpI_21Ubzdg4p_AEC8WkLwxdgg/edit

**Comment by CelesteCote** [comment]
Reviewing now. And dropping the link to the French version here for handy reference: https://docs.google.com/document/d/1CXsORRPK7ELQoktblhpI_21Ubzdg4p_AEC8WkLwxdgg/edit

**Comment by SmartMouthWords** [comment]
Reviewed and responded to comments on the English text

**Comment by melaniebmn** [comment]
Guidance added to documentation site in PR [#270](https://github.com/cds-snc/gcds-docs/pull/270).
