### ISSUE TITLE
Update card images for Get involved and Foundations pages

### ISSUE THREAD

**Issue by realdylanzheng** [cds-snc/design-gc-conception#552]
- Update card design
- Update thumbnail images where relevant

Value:

Cards on these pages are using the old Card design.
Dependency: Card v2 designs

**Comment by adorayi** [comment]
Updated component visuals in the component pages, need to update the coming soon and foundations pages with the new graphics.

**Comment by adorayi** [comment]
Cards on the coming soon are using the old preview images, not the same style as the component pages.
Create a generic placeholder image for the coming soon page, so we don't have to finalize the image.
