### ISSUE TITLE
Guidance principles - research and share-out

### ISSUE THREAD

**Issue by ioanacontu** [cds-snc/design-gc-conception#56]

**Comment by AmyMorrisGC** [comment]
Compiling research on principles guidance to help inform our approach.

**Comment by AmyMorrisGC** [comment]
Design Systems (Chapter 2), Alla Kholmatova 
book – free download of chapter 2 available 
Kholmatova introduces design principles as a foundation for any well-functioning system. 
Discusses variances in principles across companies. 
Highlights the qualities of effective design principles.
Offers guidance in defining principles.
Draws the link between design principles and patterns.
Creating Great Design Principles 6 Counter-Intuitive Tests, Jared Spool
article
Creating Effective Emergent Design Principles, Jared Spool 
talk
Spool draws the distinction between good and great principles.
Discusses the importance of principles and some of the shortfalls. 
Links the success of principles to testing for relevance through regular reviews, design critique, and workshops. 
Proposes 6 tests to evaluate principles against design work.
Designing a Design System (design principles from 10-20 minute mark) Jina Anne (Bolton) 
talk  
Design principles unite designers, developers, and product managers around a single goal. 
Driving design decisions with design principles  
Design Principles for the Web, Jeremy Keith
talk  
opening presentation from An Event Apart Online Together: Front-End Focus held online in August 2020. 
Keith also maintains a collection of principles from various sources.
Defining Principles to Drive Design Decisions, John Vogt 
blog post
Salesforce principles, example of of hierarchical model for design principles.

**Comment by AmyMorrisGC** [comment]
**Design Systems** (Chapter 2), Alla Kholmatova 
Free download 
[https://www.smashingmagazine.com/design-systems-book/](url)
- Kholmatova introduces design principles as a foundation for any well-functioning system 
- Discusses variances in principles across companies. 
- Highlights the qualities of effective design principles
- Offers guidance in defining principles.
- Draws the link between design principles and patterns

**Creating Great Design Principles 6 Counter-Intuitive Tests**, Jared Spool
Article
[https://articles.uie.com/creating-design-principles/](url)

**Creating Effective Emergent Design Principles**, Jared Spool 
Talk
[https://leaders.centercentre.com/posts/recording-creating-effective-emergent-design-principles-talk-ux-strategy-with-jared-spool](url)  
- Spool draws the distinction between good and great principles
- Discusses the importance of principles and some of the shortfalls 
- Links the success of principles to testing for relevance through regular reviews, design critique, and workshops 
- Proposes 6 tests to evaluate principles against

**Designing a Design System** (design principles from 10-20 minute mark) Jina Anne Bolton 
talk   
[https://vimeo.com/181329002](url)
- Design principles unite designers, developers, and product managers around a single goal. 
- Driving design decisions with design principles  

**Design Principles for the Web**, Jeremy Keith
Talk  
The opening presentation from An Event Apart Online Together: Front-End Focus held online in August 2020. 
[https://adactio.com/articles/17733 ](url)
Keith also maintains a collection of principles.
[https://principles.adactio.com/ ](url)

Defining Principles to Drive Design Decisions, John Vogt 
https://medium.com/salesforce-ux/defining-principles-to-drive-design-decisions-b647b68fb057
blog post
- Salesforce principles, example of of hierarchical model for design principles

**Comment by AmyMorrisGC** [comment]
**Potential next steps:**
1. identify dependencies to creating ds team principles
2. document how we want to use principles (in critiques/reviews, processes, etc.) – this would probably be a short proposal based on best practices in the research shared
3. co-design activity to identify principles
4. plan for how to share, adopt, test and iterate

**Comment by ioanacontu** [comment]
Depends on the vision and mission. Emergent design principles to be used. Start from what has already been surfaced.
