### ISSUE TITLE
Research and document differences between elements of GC DS, Canada.ca, BDM Design Systems

### ISSUE THREAD

**Issue by adorayi** [cds-snc/design-gc-conception#577]
Ravina and the BDM team have put together a comparison chart:
https://miro.com/app/board/uXjVPDtQwyo=/?moveToWidget=3458764538581166305&cot=14

- [x] Review and update using latest version of GC DS Figma Library
- [x] Document differences and missing elements
- [x] Provide rationale for differences if available
- [x] Review and present
- [x] Create action items and tickets to close the gap

**Comment by samburtonCDS** [comment]
@adorayi should this feed into the library audit? I'm planning to use Ravina's research in miro to inform that work
