### ISSUE TITLE
Draw the user journeys of the 2 main users

### ISSUE THREAD

**Issue by ioanacontu** [cds-snc/design-gc-conception#58]
Based on [this research](https://miro.com/app/board/o9J_lCm8BCw=/?fromRedirect=1), we've established 2 main types of users. Drawing the user journeys will help us identify assumptions, missing information etc.

**Comment by ioanacontu** [comment]
Started it. In the next couple of days we'll wrap up. Meeting Sam to sync on it.

**Comment by ioanacontu** [comment]
Pretty much done. Feedback from Sam. Done by the end of day. Share a link out. If a meeting is needed, we'll organize it next week.

**Comment by nmakuch** [comment]
First iteration of the User Journey Maps
https://www.figma.com/file/VUxfzUWHbMmOpasyNM6e5m/User-Journey-Maps?node-id=0%3A1
