### ISSUE TITLE
Reference implementation - Identify high level module to be developed

### ISSUE THREAD

**Issue by duboisp** [cds-snc/design-gc-conception#61]
Based on WET5 initial work/research/plan, identify high level module to be developed in order to have a front-end framework fully technology agnostic framework, flexible to fast change, easy to contribute/develop, conform to standard and leverage the resource description framework as the data layer.

reference:
* https://github.com/wet-boew/wet-boew-experimental
* https://github.com/wet-boew/gcweb-jekyll
* https://github.com/wet-boew/GCWeb/pull/1784
* https://wet-boew.github.io/wet-boew-documentation/research/2018-14-wet5-summary.html
* https://wet-boew.github.io/wet-boew-documentation/research/2020-32-wet-boew-5-year-plan.html

**Comment by ioanacontu** [comment]
The team would like to hear more about this task. TBD when Pierre is back. 
Questions: will we need front-end devs involved in this task? what does "module" mean.

**Comment by duboisp** [comment]
_Draft_

Goal: 
* Keep independent as much as possible the Data layer vs HTML vs CSS vs JS
* Be compatible with the extension of existing javascript implementation or be a reference for other framework when it's not possible.
* Make an environment favourable for non-technical contributor like doing quick prototyping, making editorial fix, developing with no or minimal setup...
* Maintain a high quality coding standard.
* Make it easy for author and developer to modify and adapt as per their needs.
* Be interoperable by following W3C Standard first and use vanilla JS

Module:
* Initialization of the reference implementation framework
* Load third party libraries on run time during development and production
* Testing framework that validate the interaction pattern and the user experience
* Architecture of the file system for the framework in development mode and in production mode
* Component templating system fully controllable through a data layer.
* Full page templating system, enhancing a barebone page with common site header and site footer
* RDF centralized data layer and reasoner
* Review, rewrite and reorder the CSS/SASS file compilation to allowing more a better/easier overriding mechanism of styled component.


Ongoing work:
* GCWeb jekyll: GCWeb theme implementation through a static content management system supported by Github pages
* Méli-mélo and thématique feature

**Comment by GormFrank** [comment]
@duboisp Should we add another "module" that would be:

- Update or remove third-party dependencies such as jQuery, Bootstrap 3 and Datatable
