### ISSUE TITLE
Start developing an experimental SSR package

### ISSUE THREAD

**Issue by adorayi** [cds-snc/design-gc-conception#620]
What is the change that we're proposing and/or doing?
Use a third party community solution, Method 1 - Stencil Wrapper with modifications, to allow the GCDS components to work in an SSR environment. 

Consequences

- What becomes easier or more difficult to do because of this change?
- Proposed solution patches the @stencil/core package that the components use to render, patch could potentially not work after any stenciljs update. 
- Lots of custom work involved to make this work

Checklist:

- [ ] Setup branch with project configured to our project
- [ ] Remove use of window in components (top-nav, side-nav, topic-menu)
- [ ] Change attributes to use camel case (buttonRole instead of button-role).
- [ ] Build in an exception for our 

non-shadow-dom components.

**Comment by daine** [comment]
Part of #613
