### ISSUE TITLE
Round up guidance documentation

### ISSUE THREAD

**Issue by SmartMouthWords** [cds-snc/design-gc-conception#63]

**Comment by AmyMorrisGC** [comment]
[https://docs.google.com/spreadsheets/d/15yakN-EZYfGKIA_dNAydW9z2S71gbmsRK3dg_hux0M4/edit#gid=0](url)

**Comment by AmyMorrisGC** [comment]
- [ ] product team input of existing guidance docs
- [ ] identify who's using each document what they're using it for
- [ ] identify potential duplicate, redundant, or outdated content
- [ ] gap analysis based on know user needs
- [ ] apply findings to inform proposed future state for guidance

**Comment by ioanacontu** [comment]
We can wrap up the round-up and in the net sprint we'll be doing analysis.
