### ISSUE TITLE
Canada.ca - Analytics and feedback

### ISSUE THREAD

**Issue by ioanacontu** [cds-snc/design-gc-conception#64]

**Comment by quidampepin** [comment]
Deck: https://docs.google.com/presentation/d/1H6AzQr5FXXimu6mF1k12j5UKYhX6zubfW04FIwjWfLc/edit?usp=sharing

Detailed analytics: https://docs.google.com/spreadsheets/d/1NoUCiZkXCRR1Oz_JD66uINGDePmGwz8GD3CmTtzinb0/edit?usp=sharing 

Detailed feedback: https://docs.google.com/spreadsheets/d/1ozDaJNsQcH-7bvz9Xmi7h21WDOAdHEJfdrR9Dwlj2P8/edit?usp=sharing
