### ISSUE TITLE
Design | Ensure footer component and subcomponents are up to date

### ISSUE THREAD

**Issue by dylanzheng94** [cds-snc/design-gc-conception#652]
To Do:
- [x] Make sure subcomponents for all 4 bands fit in the new grid system for desktop (internal assets)
- [x] Create Mobile variants for all 4 bands and make sure they fit in the new grid system for mobile (internal assets)
- [x] Publish changes so they can be accessed by main figma file (internal assets)
- [x] Set up mobile variants for the main footer components (main)
- [x] Make sure this component aligns properly with Footer component on large and small screens (main)

**Comment by nmakuch** [comment]
**Header + Footer Branch for review**
Footer work: 
https://www.figma.com/file/mh2maMG2NBtk41k1O1UGHV/branch/UunlAOOFqYCYbwG4G0ALcA/Canadian-Digital-Service%E2%80%A8---GC-Design-System?type=design&node-id=16355-3009&mode=design&t=n5723dHCNqcRmRVa-0

**Comment by nmakuch** [comment]
Subcomponent work
https://www.figma.com/file/7HNtNYzWNmcxjYtG8UlnBz/Internal-assets?type=design&node-id=301-5230&mode=design&t=0BBb2vxCOLIj0Bm3-0
