### ISSUE TITLE
Dev - labels/legends

### ISSUE THREAD

**Issue by RavinaSamaroo** [cds-snc/design-gc-conception#663]
Development of updates to the label and legend components. Full details [here](https://docs.google.com/document/d/12-jUh2iDUOmPt0qiN58Xco_uUJQsa5yNgUl7DrmrYis/edit). 

- [ ] 1. Changed label font from semibold to bold
- [ ] 2. Created variants for required, optional, and unspecified
    - (Note: ‘required’ and ‘optional’ text is different font weight)
    - (Note: ‘optional’ font is lighter grey (secondary font colour))
- [ ] 3. Component spans max 744px on desktop
- [ ] 4. Increased spacing between label and hint to 6px (spacing-100)
- [ ] 5. Changed font of hint text to lighter grey (secondary font colour)  
- [ ] 6. Created mobile variants using new mobile typography 
- [ ] 7. Changed error message to hug contents on desktop with a max width of 744px (rather than filling container)

**Comment by melaniebmn** [comment]
Closing this ticket as the label and input designs are currently being changed/worked on.
