### ISSUE TITLE
Decide on Figma file I.A.

### ISSUE THREAD

**Issue by dylanzheng94** [cds-snc/design-gc-conception#671]
[Decision record](https://docs.google.com/document/d/1_rVo7AJc4dUT54Z7nqghXMReyb7e1qJQIPMw91I4bVA/edit?usp=sharing)

- [x] Document decision record
- [x] Discuss options at dev/design sync

**Comment by ClementineHahn** [comment]
@dylanzheng94 could you add the link of the doc for decision record please ? Thank you
