### ISSUE TITLE
Conduct User Testing for Bilingual Information Architecture in Figma

### ISSUE THREAD

**Issue by Lu-stack-art** [cds-snc/design-gc-conception#677]
Objective: To gather user feedback and insights on our information architecture models for our bilingual (English and French) Figma file. The focus is on assessing usability, navigation, and user experience in both languages.

**Comment by ClementineHahn** [comment]
Unprioritized for now. Staying in the backlog when its going to be time to assess the new Information architecture the team will have landed on and deployed @dylanzheng94

**Comment by adorayi** [comment]
Test is done and results are in. Needs review to plan any action items.
