### ISSUE TITLE
Design tokens page contains images of text (related to no alt text #680)

### ISSUE THREAD

**Issue by adorayi** [cds-snc/design-gc-conception#692]

**Comment by SmartMouthWords** [comment]
Reviewed alt text updates from @ethanWallace 
- Added suggested changes in new column to the [sheet Ethan created](https://docs.google.com/spreadsheets/d/1FHBEau_Bep6C_FU2Duf58MbDUlY6v_5Bjm9kEGSplaA/edit#gid=0)
- Brought these to content critique 20-Feb-2024 and integrated feedback.

**Comment by ethanWallace** [comment]
Sent to translation

**Comment by adorayi** [comment]
Add relationship to other OCADU issue for publishing

**Comment by ethanWallace** [comment]
Will be published with https://github.com/cds-snc/design-gc-conception/issues/681
