### ISSUE TITLE
Development: Date input component

### ISSUE THREAD

**Issue by adorayi** [cds-snc/design-gc-conception#698]
**Summary:** Development of the date input component.
Develop on component branch, push to staging and push to prod when approved.

**Acceptance Criteria:**

- [x] Component kickoff
- [x] Sync with Design
- [x] Requirements documentation
- [x] Requirements doc: Consider edge cases
- [x] Requirements doc: Describe component properties
- [x] Review of requirements doc
- [ ] Develop the component according to the requirements doc and design specs
- [ ] Add component to storybook
- [ ] Write draft of dev guidance
- [ ] Sync dev properties with Figma properties (design + dev)
- [ ] Handoff from draft dev guidance to documentation author/lead
- [ ] WCAG Goal can be completed using a screen reader.
- [ ] WCAG Visual elements observe color contrast requirements.
- [ ] WCAG Manual accessibility testing meets WCAG 2.1 AA requirements.
- [ ] Provides equal service in French and English.
- [ ] Comparison with official policy, documented reasons for deviation if any
- [ ] Final sync with Design
- [ ] [Policy review](https://www.figma.com/file/p0eiLxdme1g93sIuggjipR/Colour-%26-typography-differences-GCDS-vs.-Canada.ca?type=design&node-id=0-1&t=kkavFCQ74dMoZw6V-0)
- [ ] Code review
- [ ] After PR approval, merge component to staging
- [ ] Review from Design
- [ ] Review from Policy
- [ ] Note: reviews could be done on Storybook staging
- [ ] Push to prod

**Comment by daine** [comment]
Requirements documentation:
- [ ] Requirements doc: Consider edge cases
- [ ] Requirements doc: Describe component properties
- [ ] Review of requirements doc

**Comment by daine** [comment]
Proposed definition of done:
- [ ] Develop the component as [required](https://docs.google.com/document/d/1LC0MNGiZBHDEJ-_rrlNFx8SKOpMII0cJaJ65UzF9d5A/edit#heading=h.cq5k9hz0s60m)
- [ ] Validator for dates exists
- [ ] Error states for invalid month, day or year show up appropriately
- [ ] Event handlers exist to handle events for the 2 or 3 inputs (year month day)
- [ ] The component exists in storybook
- [ ] Tests are written for good code coverage and are passing
- [ ] The component works in HTML, React, React with SSR, Angular, and Vue (?)

Proposed acceptance criteria:
- [ ] When the language is set to french, the component displays the date input in the french format
- [ ] The component follows the design in figma
- [ ] The component works in both desktop and mobile screens
- [ ] The component can be used in two formats, full and compact


Must be done before: 
- #699

**Comment by ethanWallace** [comment]
Development is going well. Things still left to do:
- [ ] Styling
- [ ] New tokens
- [ ] Property validation
- [ ] Form validation
- [ ] Storybook
- [ ] Unit tests
- [ ] Write code guidance for component
