### ISSUE TITLE
Development: Stepper v2

### ISSUE THREAD

**Issue by adorayi** [cds-snc/design-gc-conception#701]
**Summary:** Development of the stepper component.
Develop on component branch, push to staging and push to prod when approved.

**Acceptance Criteria:**

**Comment by adorayi** [comment]
Need a list of changes to the stepper v1.

**Comment by daine** [comment]
- [ ] Website documentation, anatomy, one paragraph for heading and design section
- [ ] Design has new styles for mobile
- [ ] https://github.com/cds-snc/design-gc-conception/issues/933

**Comment by ClementineHahn** [comment]
Waiting to have the "error message" back form translation and then should unblock the final review

**Comment by ethanWallace** [comment]
Received translation, now in final review

**Comment by ethanWallace** [comment]
Will need updated guidance published on documentation site before the component can be published

**Comment by ethanWallace** [comment]
Has passed reviews from dev. Will merge and publish once the new guidance is ready to publish.

**Comment by ethanWallace** [comment]
Passed dev review, have a meeting on Monday to review coded component with designers.

Will need the breaking change messaging to be released and new guidance ready to published before merging/publishing.

**Comment by ethanWallace** [comment]
Release messaging will need to be released and guidance ready to publish before publishing this component.
