### ISSUE TITLE
Add link to contribution content on GIthub contribution guidelines

### ISSUE THREAD

**Issue by brockhigg10** [cds-snc/design-gc-conception#709]
- [x] Update "Next Priorities" contribution form
- [x] Get new Contribution Guidelines Translated
- [x] Publish new Contribution Guidelines on Github

**Comment by daine** [comment]
If it helps, here is a list of our github repositories where we can update the CONTRIBUTING.md:

_source: https://github.com/cds-snc/gcds-components/wiki_

The following are our developer repositories

https://github.com/cds-snc/gcds-docs - Documentation website
https://github.com/cds-snc/gcds-components - Design System Components
https://github.com/cds-snc/gcds-tokens - Design Tokens
https://github.com/cds-snc/gcds-utility - Utility Framework

This repository contains our infrastructure as code terraform files and configuration

https://github.com/cds-snc/gcds-terraform

**Comment by daine** [comment]
@brockhigg10 New template: https://github.com/cds-snc/gcds-components/issues/new/choose
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVd3QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0e2d45fbd57a7607ca0c90e2f74da1850cdbe2c6/Screenshot%202024-05-02%20at%2011.41.47%E2%80%AFAM.png" alt="Screenshot 2024-05-02 at 11.41.47 AM.png" />

<img width="1077" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVN3QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--08442083c411a8ad4a69aa70a2d2eb8dd1b0a9a0/Screenshot%202024-05-02%20at%2011.41.52%E2%80%AFAM.png" alt="Screenshot 2024-05-02 at 11.41.52 AM.png" />

**Comment by daine** [comment]
Updated the dropdown for next priorities: https://github.com/cds-snc/gcds-components/pull/521

**Comment by adorayi** [comment]
We may want to add some details to the dropdown to provide more context (other names, links etc)

**Comment by adorayi** [comment]
Decision: Add FR inline, translations received 5/13.

**Comment by melaniebmn** [comment]
[FR translations](https://docs.google.com/document/d/1nqGUV0p8PLAj63qW7O2V5qJfo0hChfKdQUtjieoJhB0/edit)

**Comment by daine** [comment]
Here is the PR to add the FR translations to all three issue templates including the contribution template
