### ISSUE TITLE
Update documentation for form elements

### ISSUE THREAD

**Issue by ethanWallace** [cds-snc/design-gc-conception#712]
Update documentation for form elements with new changes from form-associated work.

- [x] New mandatory `name` attribute
- [x] `gcds-radio-group` rework
- [x] translation

**Comment by ethanWallace** [comment]
https://docs.google.com/document/d/1GRYr_Fx1MvkFubVi2Odh7W6P1GFqmXip0p4P6lpwk70/edit?usp=sharing
https://docs.google.com/document/d/1FHZ_XsYWSgzQM1WuyHAYYmI6URGKG092SAE9Oa_gjAY/edit?usp=sharing

**Comment by daine** [comment]
@ethanWallace I can help update the docs site to include the new mandatory name attribute

**Comment by ethanWallace** [comment]
A new document has been created for all required documentation updates for SSR package release https://docs.google.com/document/d/1C659l9bttZOdV386WlYGFbKJa-ZpaE1HeyNrJhTaDP4/edit

**Comment by SmartMouthWords** [comment]
Reviewed, made some edits, and added a few questions https://docs.google.com/document/d/1C659l9bttZOdV386WlYGFbKJa-ZpaE1HeyNrJhTaDP4/edit

**Comment by daine** [comment]
@SmartMouthWords Thanks Amy! Should we send this off to translation now so we can add it to our docs site? @ethanWallace TIA

**Comment by SmartMouthWords** [comment]
[French](https://docs.google.com/document/d/19O8BtrzLl9dR86Gw9ukjdn-H48sHBkH1isS3v60spsQ/edit) came in last week and sent for posting online.

**Comment by daine** [comment]
PR ready for review: https://github.com/cds-snc/gcds-docs/pull/318

**Comment by adorayi** [comment]
Need a review from @SmartMouthWords if possible
Also translation needed.

**Comment by ClementineHahn** [comment]
Blocked by Release messaging that should happen first  Ticket #819 and they are waiting for translation back
