### ISSUE TITLE
EN content review before sending for translation

### ISSUE THREAD

**Issue by adorayi** [cds-snc/design-gc-conception#715]
Checklist for poster review:

- [ ] Match all names and terms to website and code
- [ ] Add definition and other names
- [ ] Add descriptions where placeholder text exists
- [ ] Match in-component content with that in the code
- [ ] Need roles description when applicable
- [ ] Need states description when applicable
- [ ] Need type description when applicable
- [ ] Anatomy needs to match website
- [ ] Add anatomy descriptions?

**Comment by SmartMouthWords** [comment]
Checklist for poster

**Comment by SmartMouthWords** [comment]
This work is all captured in the following card: https://app.zenhub.com/workspaces/design-system-6100624a19f4cf000e46e458/issues/gh/cds-snc/design-gc-conception/672
