### ISSUE TITLE
Add global background tokens to documentation site

### ISSUE THREAD

**Issue by melaniebmn** [cds-snc/design-gc-conception#731]
Add new global background tokens to our documentation site to help inform users about them.

**Comment by melaniebmn** [comment]
Note: need a final review from the design team before I can start coding this.

**Comment by ClementineHahn** [comment]
Currently drafting the "purpose" of it, will wait for translation

**Comment by melaniebmn** [comment]
The English version is done and sent to translation today for the French content.

**Comment by melaniebmn** [comment]
English content is done, the translation request was sent on April 30th, 2024
