### ISSUE TITLE
Audit icons references in existing component content on doc site / assets in figma

### ISSUE THREAD

**Issue by adorayi** [cds-snc/design-gc-conception#732]
References - both images and text
Review anatomy images, definitions and descriptions of all relevant components in the Figma library and the website.

Add checklist of components below:

- [x] Alert
- [x] Breadcrumbs
- [x] Date Input (using select component)
- [x] File uploader
- [x] Header (using search, top navigation, breadcrumb components)
- [x] Link
- [x] Mobile navigation (figma only)
- [x] Pagination
- [x] Search
- [x] Select
- [x] Side navigation
- [x] Top navigation
- [x] Theme and topic menu

If there is time:
- [x] Even check components that don't have icons on docsite

**Comment by adriannelee** [comment]
Auditing where we're referencing icons on the docs site.

**Comment by nmakuch** [comment]
Finalized spreadsheet
[Component audit](https://docs.google.com/spreadsheets/d/1TJnIWldJOADHrhJYar87XtdQuri-nifRxO4foRiesho/edit#gid=0)

**Comment by adorayi** [comment]
Amazing work @nmakuch, what follow up tasks are needed from this audit? I'm thinking:
- Update anatomy images ([947](https://app.zenhub.com/workspaces/design-system-6100624a19f4cf000e46e458/issues/gh/cds-snc/design-gc-conception/947))
- Update icons in components that use old icons?
- Update icons in documentation?
