### ISSUE TITLE
Date input component requirements

### ISSUE THREAD

**Issue by daine** [cds-snc/design-gc-conception#751]
Requirements documentation for development and implementation of the new Date Input component

- [x] Requirements doc: Consider edge cases
- [x] Requirements doc: Describe component properties
- [x] Review of requirements doc

Related to #698

**Comment by daine** [comment]
[Here is the Requirements doc](https://docs.google.com/document/d/1LC0MNGiZBHDEJ-_rrlNFx8SKOpMII0cJaJ65UzF9d5A/edit).

Review needed from design, product and development

**Comment by daine** [comment]
Almost done -- just needing french translations for the Anatomy image as well as the error states design.

**Comment by adorayi** [comment]
@SmartMouthWords to review
