### ISSUE TITLE
Update CDN installation instructions on website

### ISSUE THREAD

**Issue by daine** [cds-snc/design-gc-conception#753]
As a user, I want to use a specific version of the gcds packages so that my application does not get any breaking changes.

Here is the file that needs to be updated
https://github.com/cds-snc/gcds-docs/blob/1e1106ac8dc6a5ed853d594307380d4093c07a08/src/_includes/partials/installation/step-2-cdn.njk#L13-L15

As of March 5, 2024, the `latest` tag points to version `0.19.1`
https://www.npmjs.com/package/@cdssnc/gcds-components?activeTab=versions

**Comment by daine** [comment]
@melaniebmn if time permits, you can automate this to get the version from here: https://github.com/cds-snc/gcds-components/blob/main/lerna.json

I see the estimate is a 1 so maybe it can be on another ticket

**Comment by melaniebmn** [comment]
Sent the updated text in [this](https://www.figma.com/design/nfpEteHyEJ9dhJ2YvuvLeo/Documentation-site%2FComponent-Pages?node-id=14606-3324&t=uECy89afqx7DLRt4-0) Figma file to translation.
