### ISSUE TITLE
Grid component’s tag attribute “could” cause issues

### ISSUE THREAD

**Issue by Lu-stack-art** [cds-snc/design-gc-conception#757]
When using `gcds-grid`, the `tag` property can accept any HTML element. This can cause issues if a developer uses an element that deosn't make sense to render as a grid container.

To do:

- [x] Limit allowed values for `tag` property
- [x] Add disclaimer about tag use to documentation site
- [x] Translation

**Comment by melaniebmn** [comment]
PR for limiting the allowed values:

https://github.com/cds-snc/gcds-components/pull/470
