### ISSUE TITLE
Breadcrumbs navigation label repeating on Breadcrumbs component page

### ISSUE THREAD

**Issue by Lu-stack-art** [cds-snc/design-gc-conception#761]
When viewing the landamarks of the page, several landmarks are labelled Breadcrumbs. Breadcrumbs from the header, the bradcrumb component example, the tabs on the documentation page and the breadcrumb example in the code builder.

- [x] Update tabs navigation to hav a different label
- [x] Translation

**Comment by melaniebmn** [comment]
Note: We will not be able to remove the breadcrumbs landmark from the code builder. The only way to remove it would be to change the component itself which doesn't make sense OR to hide the code builder for the breadcrumbs completely for screen reader users which is also not a great option.

Changes will be added in [PR #303](https://github.com/cds-snc/gcds-docs/pull/303)
