### ISSUE TITLE
Top-nav and side-nav: Update nav-group and nav-link names to be unique

### ISSUE THREAD

**Issue by Lu-stack-art** [cds-snc/design-gc-conception#763]
On the top-nav and side-nav pages, the component examples use text that labels each nav component with what it is ("Nav Link"). This can cause a confusing experience for people using AT. Change nav-link and nav-group lables to be unique.

- [x] Update labels on website
- [x] Update labels in storybook

**Comment by melaniebmn** [comment]
Website fixed in [PR #302](https://github.com/cds-snc/gcds-docs/pull/302)
