### ISSUE TITLE
Ensure good error logging on the contact us submission API function

### ISSUE THREAD

**Issue by daine** [cds-snc/design-gc-conception#768]
## 📇 User story

As a developer, I want to add better error logging on the contact us submission API lambda function, so that I am able to debug with higher confidence when something goes wrong.

This ticket is an action item of [this incident doc](https://docs.google.com/document/d/1lAryEOgMVmPm-TmipBw_zarf805WTWFgLWe_w89ysBE/edit)

**Comment by adorayi** [comment]
Is anyone reviewing this @daine?
