### ISSUE TITLE
EN content on FR page

### ISSUE THREAD

**Issue by adorayi** [cds-snc/design-gc-conception#769]
https://systeme-design.alpha.canada.ca/fr/composants/champ-de-saisie/

<img width="913" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdzdTQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e033b7bbab533f7cf7c525f93d29011b9cea3ba3/Screenshot%202024-03-11%20at%204.01.55%E2%80%AFPM.png" alt="Screenshot 2024-03-11 at 4.01.55 PM.png" />

**Comment by daine** [comment]
^ [lines of code to ](https://github.com/cds-snc/gcds-docs/blob/cd0fd58cdb98fcce563da89f5f898ca48ea12397/src/fr/composants/champ-de-saisie/case-dusage.md?plain=1#L43-L65)fix this -- just needs the FR translation

**Comment by SmartMouthWords** [comment]
It looks like this was never translated. I'll send the text to @EliseKa

**Comment by EliseKa** [comment]
Translations are ready, flagged in pink in this [Figma file (FR input frame)](https://www.figma.com/file/nfpEteHyEJ9dhJ2YvuvLeo/Documentation-site%2FComponent-Pages?type=design&node-id=12226-17251&mode=design&t=4rvDkS7Nhrzjz687-4)

**Comment by daine** [comment]
Code is merged and deployed to production
