### ISSUE TITLE
Look into CloudFront signed URLs for our CDN

### ISSUE THREAD

**Issue by daine** [cds-snc/design-gc-conception#779]
## 📇 User story

As a developer, I want to ensure that the external third party CDN URLs I'm using have signed URLs, so that I am extra confident in the security and authenticity of the code provided.

Using Signed URLs gives us control over who is using our CDNs and how long we can give them access to it. We may need to touch base with SRE (Cheyenne and Chang)

## ✅ Definition of Done
- [ ] I have done due diligence of looking into the benefits of using a signed URL
- [ ] I have looked into whether or not it is an appropriate security measure we should utilize

## 📜 Acceptance criteria
- [ ] Decide to proceed with using Signed URLs for our CDN

## 📝 More info
https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-signed-urls.html

This issue is tied closely and should be worked with #778

**Comment by melaniebmn** [comment]
To do:
Discuss if this is really needed.

**Comment by melaniebmn** [comment]
Comment from Cheyenne to consider: "I was thinking we could look into a way to add it as an optional piece to our SRE terraform modules for teams if they'd like to use it! It can be a bit of overkill BUT if the lift isn't too big a little bit of overkill can't hurt all the time"

**Comment by melaniebmn** [comment]
Closing this ticket because we have decided with Cheyenne that this is not needed for our design system at this point.
