### ISSUE TITLE
Create a privacy notice for the GCDS website

### ISSUE THREAD

**Issue by samburtonCDS** [cds-snc/design-gc-conception#786]

**Comment by samburtonCDS** [comment]
Create a privacy statement for the GCDS website, to cover collection of information through feedback from & email newsletter [draft here](https://docs.google.com/document/d/1dMlZNWSvmip-46DWnn58BrTpk1hiYOFC2RtJ0-eZ0LU/edit#heading=h.ol1g61vav7xc)

**Comment by samburtonCDS** [comment]
Sent to translation

**Comment by samburtonCDS** [comment]
French translation [here](https://docs.google.com/document/d/152Z_H683zjFaLg1D7bbUsfr49fY_g1Z_BCr9Lmrzev0/edit#heading=h.gjdgxs)

**Comment by samburtonCDS** [comment]
In response to @melaniebmn's question about what needs to be included in the GCDS documentation site footer: 

I agree with Sarah's assessment that the GCDS site is a standard page, not a transactional or campaign page. As a result, we should be following the Canada.ca design system requirement that [the global footer on all GC standard pages must include 2 mandatory elements](https://design.canada.ca/common-design-patterns/site-footer.html):

1. [The sub-footer band](https://design.canada.ca/common-design-patterns/site-footer-sub.html) with the Canada watermark, which is what you're talking about above. So yes, we need to keep that with all the links and just change the "privacy" link to our new page
2. [The main band](https://design.canada.ca/common-design-patterns/site-footer-main.html), which we don't currently have on the GCDS site... but IMO we should add it in order to meet the same requirements GCDS is helping other GC teams meet

So my advice is that we keep all the links in the sub-footer band, and also add the main band.

**Comment by melaniebmn** [comment]
New privacy page + footer update has been added in [PR #316](https://github.com/cds-snc/gcds-docs/pull/316).
