### ISSUE TITLE
Discovery discussions with security team to plan next steps.

### ISSUE THREAD

**Issue by adorayi** [cds-snc/design-gc-conception#789]
Discussion to identify next steps. Outcomes:

- [x] Direction and options
- [x] Immediate next steps
- [ ] Rough estimate and scope

**Comment by melaniebmn** [comment]
I talked to Cheyenne and we agreed on the following:

- For #777 we'll try to implement this ourselves and will get a PR review from the security team.
- For #778 we'll try to implement this ourselves first, but we might need help from the security team.
- #779 might not be useful to implement after all. We will do more research and have another discussion with the security team before making a call.
