### ISSUE TITLE
Update Input Component

### ISSUE THREAD

**Issue by realdylanzheng** [cds-snc/design-gc-conception#801]
As a designer and library maintainer, I want to reduce the number of variants by leveraging nest properties, so that bilingual component updates are more efficient, leading to a more robust design.

As a user, 
I want to input and edit my input without a character restriction, 
to reduce the worry of my input being cutoff or truncated.

### Design
- [x] Increase input width

### Code
- [x] Increase input width calculation (2x)
- [x] Remove maxLength

### Content
- [ ] Add content explaining the different input sizes

**Comment by melaniebmn** [comment]
Input changes added in [PR #536](https://github.com/cds-snc/gcds-components/pull/536)
