### ISSUE TITLE
French poster for Date input is missing

### ISSUE THREAD

**Issue by adorayi** [cds-snc/design-gc-conception#805]

**Comment by realdylanzheng** [comment]
Screen reader only poster review is blocked by the actual creation of the screen reader Figma "component" and poster

**Comment by adorayi** [comment]
Date input poster in EN is finished

**Comment by nmakuch** [comment]
French poster back from translation and I reviewed autolayouts and formatting 
https://www.figma.com/file/7HNtNYzWNmcxjYtG8UlnBz/Internal-assets?type=design&node-id=1195-1069&mode=design&t=zK5D7kh8ilSAeDE5-0
