### ISSUE TITLE
Align Alert design to Canada.ca's Contextual Alert

### ISSUE THREAD

**Issue by adorayi** [cds-snc/design-gc-conception#809]
[Canada.ca's Contextual Alert](https://design.canada.ca/common-design-patterns/contextual-alerts)

Design - Align alert background color (remove) to Canada.ca style in Figma

## Acceptance criteria

- [x] Designer can change the type of alert
- [x] Designer can set/modify the heading
- [x] Designer can set/modify the message
- [x] Designer has component options for desktop and mobile
- [x] User can clearly identify the type of alert

## Done when

- [x] EN component is published
- [x] EN poster is published 
- [x] Component properties are added to the properties spreadsheet for translation
- [x] FR component is published
- [x] FR poster is published
- [x] Component is marked 'Ready for dev' 

## Deliverables

- [x] EN component page (Figma)
- [x] FR component page (Figma)

**Comment by adorayi** [comment]
Need a decision on the close button which appears to be floating without the background.
@realdylanzheng @RavinaSamaroo  do we have any suggestions from the Design team on this?

**Comment by realdylanzheng** [comment]
@adorayi @RavinaSamaroo  this ticket some what of a redesign as new variants will be required (especially if we retain the dismiss functionality)
Also flagging if we don't have an ticket to remove background on error message that we should do that as well

**Comment by adorayi** [comment]
The checklist has an item for "Form field error alert background", is this sufficient or is this too big for one ticket and can be split out?

**Comment by realdylanzheng** [comment]
@adorayi Too big for one ticket, best to split it out - I can create the ticket
