### ISSUE TITLE
Development - Align alert and error message background color (remove) to Canada.ca style in code

### ISSUE THREAD

**Issue by adorayi** [cds-snc/design-gc-conception#810]
- [x] Context alert background
- [x] Form field error alert background

[Error message (Figma)](https://www.figma.com/design/mh2maMG2NBtk41k1O1UGHV/GC-Design-System?node-id=1649-4784)

**Comment by adorayi** [comment]
@melaniebmn can you confirm both items in the checklist here are done?

**Comment by melaniebmn** [comment]
@adorayi as far as I'm aware neither of those items has been worked on by any dev since the ticket is still set to blocked.

**Comment by melaniebmn** [comment]
Error message design updated in this [PR](https://github.com/cds-snc/gcds-components/pull/592).

**Comment by adorayi** [comment]
This will be done during the development of the Notice component.
