### ISSUE TITLE
Dev - Details component

### ISSUE THREAD

**Issue by melaniebmn** [cds-snc/design-gc-conception#814]
Make the following design updates:

- Updated link text using text underline rather than a vector line (based on updated link component)
- Fixed spacing so that expanded text is right aligned with link text
- Decreased large spacing between caret icon and text and between link and expander below it  
- Set width of component to 748px (8 columns) following max text container width guideline
- Changed ‘additional info’ text colour from primary to secondary
- Added mobile variants with width of 290px

**Comment by melaniebmn** [comment]
Currently blocked by missing design.

**Comment by ClementineHahn** [comment]
@adorayi to create card to capture the design work missing here

**Comment by melaniebmn** [comment]
Work is in PR review
