### ISSUE TITLE
Breaking Change Release Messaging

### ISSUE THREAD

**Issue by brockhigg10** [cds-snc/design-gc-conception#819]
https://docs.google.com/document/d/14Br8H6VuoPgXBzPUfhbhGY3scXZcW4kBSUms8bDIg2k/edit?usp=sharing

**Comment by SmartMouthWords** [comment]
Finished review of V0.21.0 content. This should be ready for translation now

I took a look at the V0.22.0 section this morning. Couple questions and suggestions there now.

**Comment by daine** [comment]
This has been sent to the translation team and Nick has confirmed they have started on it will be done soon

**Comment by brockhigg10** [comment]
[French version](https://docs.google.com/document/d/1jLJ5g7yJPNz2GIzTES9l93jlX7bYROm1fSd3xBpVWgY/edit?usp=sharing) of release content
