### ISSUE TITLE
System architecture mapping

### ISSUE THREAD

**Issue by JoshBeveridge** [cds-snc/design-gc-conception#82]
### Purpose
In light of the product roadmap work, we wanted to create a proposal for the system architecture, its pieces, and how they interact with one another.

### Outcomes
The final map should be a living document that contains a technical architecture, along with all questions and answers we produce during its course so that we can accurately document our architectural decisions in the open. It touches on the following infrastructure pieces from the "Now" section of the roadmap:
- design tokens
- tech agnosticism
- modularity
- installation

### Scope
This architecture does NOT touch on the system's documentation or guidance in any way, shape, or form. It is strictly the technical pieces behind the system itself.

### Links
Draft document: https://www.figma.com/file/jAJfmGA9tRfT3IdLUiTfYC/Technical-Product-Map-Design-System

### Estimated Effort
- [ ] XS: 1 to 2 hours
- [ ] S: half a day
- [x] M: 1-2 day (ongoing)
- [ ] L: 1 week
- [ ] XL: Move to an epic

**Comment by mcman12** [comment]
Pierre to review and look at semantic versioning

**Comment by duboisp** [comment]
I did provided some comment over the Figma schema
