### ISSUE TITLE
A new package called `gcds-components-vue`

### ISSUE THREAD

**Issue by daine** [cds-snc/design-gc-conception#823]
## 📇 User story

As a developer, I want to ensure that GCDS components has a package available for Vue, so that I am confident that it will work for Vue projects.

## ✅ Definition of Done
- [x] A stencil output target for Vue
- [x] Supports two-way binding for form elements
- [x] Handles events and propagates correctly

## 📜 Acceptance criteria
- [ ] A published npm package `gcds-components-vue`

## 📝 More info
This is related to 
- https://github.com/cds-snc/gcds-components/issues/497

Work that is moved into a separate ticket:
- #908
- #909

**Comment by ethanWallace** [comment]
Sent readme off to translation

**Comment by adorayi** [comment]
Link components work with the router: should be split off and done in coordination with other link research being done currently.

**Comment by daine** [comment]
While we don't have unit tests yet, we do have this super [small example app](https://github.com/cds-snc/gcds-examples/pull/4) we can test against. Let's update that PR to include the new package and get it merged in if possible. Thank you!
