### ISSUE TITLE
Consistent component events

### ISSUE THREAD

**Issue by ethanWallace** [cds-snc/design-gc-conception#826]
## User story
As a developer, I want GCDS components to have consistent behaviour to HTML events and provide relevant information to the event happening.

## Acceptance criteria
- [x] Emitted events contain relevant values for the event in details
- [x] Events behave similar to default HTML events (are fully cancellable)

**Comment by adorayi** [comment]
@ClementineHahn  this will be published by next week, should we let the website team know?
