### ISSUE TITLE
Refactor/simplify Radio component

### ISSUE THREAD

**Issue by realdylanzheng** [cds-snc/design-gc-conception#852]
As a designer...
I want the Radio component to use subcomponents in the same way as other form components...
so it's more predictable and understandable. 

## Acceptance criteria

- [x] User can edit Label text using nested properties
- [x] User can set error state
- [x] User can't reach state of invalid combination of properties

## Done when

- [x] EN component is merged into main & published
- [x] EN poster is updated
- [x] FR component is updated & published
- [x] FR poster is updated

**Comment by RavinaSamaroo** [comment]
@SmartMouthWords to approve content changes before updating internal assets in EN and FR.
(left is original; right is new version)

 <img width="1700" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNFdmQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8c3b5cedffb7621a47201c3e21e7481bab608f3c/image.png" alt="image.png" />

**Comment by adorayi** [comment]
Looks good @RavinaSamaroo we can close this.
