### ISSUE TITLE
Refactor/simplify Checkbox component

### ISSUE THREAD

**Issue by realdylanzheng** [cds-snc/design-gc-conception#853]
As a designer...
I want the Checkbox component to use subcomponents in the same way as other form components...
so it's more predictable and understandable. 

## Acceptance criteria

- [x] User can edit Label text using nested properties
- [x] User can set error state
- [x] Distinct error state for Checkbox group with a single option
- [x] User can't reach state of invalid combination of properties

## Done when

- [x] EN Component is merged into main & published
- [x] EN poster is updated
- [x] FR component is updated & published
- [x] FR poster is updated

**Comment by ClementineHahn** [comment]
still in progress.

**Comment by RavinaSamaroo** [comment]
@SmartMouthWords to approve content changes. 

Original > New
<img width="1842" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGlmQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--282d0638f18b64e6a138b61e7dc599d666149c6e/image.png" alt="image.png" />

**Comment by adorayi** [comment]
Looks good @RavinaSamaroo we can close this.
