### ISSUE TITLE
Create Legend component

### ISSUE THREAD

**Issue by realdylanzheng** [cds-snc/design-gc-conception#857]
As a designer...
I want components that use a legend in code to also use a legend in the design...
So during design-dev hand-offs it's clear how that component is intended to be constructed.

## Examples
- Fieldset need Legend
- Radios need Legend
- Checkboxes need Legend

## Acceptance critera

- [x] Legend has "label", hint, and required indicator
- [x] Designer can edit/modify legend, hint, and required indicator using properties
- [x] Legend has a normal and large size

## Done when

- [x] EN Component is merged into main
- [x] EN Properties are translated to FR
- [x] FR Component is merged into main

**Comment by mcman12** [comment]
@nmakuch mention the french is good to go
