### ISSUE TITLE
Design for example app

### ISSUE THREAD

**Issue by daine** [cds-snc/design-gc-conception#858]
## 📇 User story
As a Design System developer, I want to have a design for an example app, so that I can implement it.

As a developer using the GC Design System, I want to have an example app so I can view ways to implement the code in my work

## ✅ Definition of Done / Outcomes
- [ ]  A design exists in figma
- [ ] The design uses most of our components
- [ ] The design must have accessibility considerations
- [ ] The design reimagines the holidays app https://canada-holidays.ca/
- [ ] Policy has reviewed the legislative and policy considerations of the design

## 📜 Acceptance criteria
- [ ] The design has a similar look and feel to a professional website 
- [ ] The design does not cause any confusion to a user that it is an official government website
- [ ] The design can be easily implemented by a developer using the GC Design System component repository for the first time

## 📝 More info
This was brought up in dev design sync.
This will be part of our onboarding process (onboarding people and teams to the Design System)

**Comment by adorayi** [comment]
Duplicate
