### ISSUE TITLE
Create poster for Screenreader-only component

### ISSUE THREAD

**Issue by adorayi** [cds-snc/design-gc-conception#860]
Create a Figma poster for the Screenreader only component.
As this component doesn't have most of the visual elements of other components, the Figma poster will be different and likely contain very few elements.

## Acceptance criteria

- [x] Poster displays an example of the screenreader-only component (if applicable)
- [x] Poster explains (Figma) use instructions for the component (if applicable)

## Done when

- [x] EN poster is translated
- [x] EN poster is published
- [x] GC Design System is updated with EN poster
- [x] FR poster is published
- [x] System de Design GC is updated with FR poster

## Deliverables
- [EN poster](https://www.figma.com/design/mh2maMG2NBtk41k1O1UGHV/GC-Design-System?node-id=23194-121&t=kLqLSMWRTrKiVuFV-4)
- [FR poster](https://www.figma.com/design/o4SguSZdar2CCFzSkWNrmB/Syst%C3%A8me-de-design-GC?node-id=870-137&t=nFMzjSNBA2CkUrXx-4)

**Comment by mcman12** [comment]
suggest pushing it to next sprint to have all the work done in 1 sprint

**Comment by SmartMouthWords** [comment]
https://www.figma.com/file/7HNtNYzWNmcxjYtG8UlnBz/Internal-assets?type=design&node-id=1782%3A21156&mode=design&t=fiDEtpuScPBXGpAp-1

**Comment by SmartMouthWords** [comment]
Revised content for screenreader-only poster. Because component in Figma library will work differently than in the code, recommend including the "Designing [component] in Figma, like we've used for the container and link component to give specific instructions on use.

**Comment by realdylanzheng** [comment]
Status: reviewed by designers, in translation
