### ISSUE TITLE
Design - Remove Error Message background fill in Figma to align with Canada.ca style

### ISSUE THREAD

**Issue by adorayi** [cds-snc/design-gc-conception#861]
[Canada.ca's Contextual Alert](https://design.canada.ca/common-design-patterns/contextual-alerts)

## Acceptance criteria
- [x] Error message component background is transparent
- [x] Error message text is prefixed with an icon
- [x] Error message text font weight is bold
- [x] Error message text is red-700 (#A62A1E)
- [x] Error message can be set/modified

## Done when

- [x] EN component is published
- [x] FR component is published
- [x] All EN components that use error are updated and published
- [x] All FR components that use error are updated and published
- [x] All EN posters with error state are updated and published
- [x] All FR posters with error state are updated and published
- [x] Figma file is linked in corresponding dev ticket
- [x] Component history Figma file is updated with previous version and rationale (EN only)

## Deliverables

- [x] [Figma | EN component](https://www.figma.com/design/mh2maMG2NBtk41k1O1UGHV/GC-Design-System?node-id=1649-4784)
- [x] [Figma | FR component](https://www.figma.com/design/o4SguSZdar2CCFzSkWNrmB/Syst%C3%A8me-de-design-GC?node-id=48-7032)

**Comment by adorayi** [comment]
cc @melaniebmn to confirm before closing.

**Comment by melaniebmn** [comment]
@adorayi there is no matching dev ticket (as far as I know) for removing the error message background.

**Comment by adorayi** [comment]
Corresponding dev ticket linked as a dependency @melaniebmn

**Comment by SmartMouthWords** [comment]
There's a small discrepancy between the new error message anatomy and the anatomies of other components. When an icon is part of a component, it is labeled and described in each anatomy. Some examples: 
<img width="764" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXdaQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ba33fc64c6897d4640c3b7898529fc2320dfdfe7/Screenshot%202024-07-29%20at%204.45.19%E2%80%AFPM.png" alt="Screenshot 2024-07-29 at 4.45.19 PM.png" />
 <img width="867" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTBaQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f4b7c40ff7383e2ae5254a192aca184525b7ecfe/Screenshot%202024-07-29%20at%204.45.58%E2%80%AFPM.png" alt="Screenshot 2024-07-29 at 4.45.58 PM.png" />

**Comment by melaniebmn** [comment]
Note for future workflow alterations: alt text needed to be updated because the preview + anatomy images were changed.

**Comment by realdylanzheng** [comment]
@SmartMouthWords [Updated error message anatomy (Figma)](https://www.figma.com/design/7HNtNYzWNmcxjYtG8UlnBz/Internal-assets?node-id=15-7367&t=Ubrxenj9TaGNezjG-4) for your review. Thanks

**Comment by realdylanzheng** [comment]
@melaniebmn Which ticket should alt text, preview image, and anatomy image work be defined in: Content, Design, or Dev?

**Comment by melaniebmn** [comment]
@realdylanzheng I don't think that is my call to make but to me, it would make sense in all 3: The design team needs to update the preview + anatomy images, the content team needs to write the new alt text description, and the dev team needs to implement the new images + alt text.

@adorayi @ClementineHahn tagging you both as this seems workflow-related.
