### ISSUE TITLE
Figma library: radio group update 

### ISSUE THREAD

**Issue by SmartMouthWords** [cds-snc/design-gc-conception#864]
Update language in Figma library to align with [component name change ](https://docs.google.com/document/d/1to4YtsVbo3lQruvbjiBpYAz0Ky0K4O4WV4sBT4IxsZ4/edit#heading=h.rw0hvyg22v9d) and [latest documentation update](https://docs.google.com/document/d/1C659l9bttZOdV386WlYGFbKJa-ZpaE1HeyNrJhTaDP4/edit)

**Comment by SmartMouthWords** [comment]
Change name, other names, replace references to the radio component with "radio group" and "groupe de boutons radio"
- [ ] English
- [ ] French

**Comment by adorayi** [comment]
Duplicate of 879
