### ISSUE TITLE
Create Fieldset

### ISSUE THREAD

**Issue by realdylanzheng** [cds-snc/design-gc-conception#865]
As a designer...
I would like to have [Fieldset component](https://www.figma.com/file/mh2maMG2NBtk41k1O1UGHV/GC-Design-System?type=design&node-id=7718-7405&mode=design&t=aLY1FBkXjnLWGiXT-4) in Figma...
so that I don't need to create my own. 

## Acceptance criteria

- [x] Designer can set/modify Legend text
- [x] Designer can configure the number of fields (1 - 10)
- [x] Designer can set form fields in the field slots
- [x] Has mobile variant (won't do, Figma limitation)

## Done when

- [x] EN component is published
- [x] EN library is updated with poster
- [x] FR component is published
- [x] FR library is updated with poster
- [x] Any component leveraging Fieldset is updated

## Value
Help designers become more efficient when working with components that use a fieldset

## Deliverables

- [x] EN Fieldset (Figma)
- [x] FR Fieldset (Figma)

**Comment by adriannelee** [comment]
Got through the EN, will work on the FR today
