### ISSUE TITLE
Create variables for all existing tokens and styles

### ISSUE THREAD

**Issue by adorayi** [cds-snc/design-gc-conception#872]
## Acceptance criteria

- [x] Has variable collection: Base
- [x] Has variable collection: Colours (incl. Semantic and Component-level colours)
- [x] <s>Has variable collection: Viewport</s>
- [x] Put our existing base and global tokens into Base, Colours, and Viewport collections
- [x] Each variable has defined scope
- [x] Set tokens for notice colours (new base colours)

## Done when
- [ ] EN library is published
- [x] EN tokens are exported via Variable Pro and imported by the FR library (use 2 of 10 free trials)
- [ ] FR library is published (needs translation)

**Comment by ClementineHahn** [comment]
Currenlty in progress, determining next steps with design and dev today

**Comment by realdylanzheng** [comment]
[Propose solution and plan](https://docs.google.com/document/d/1GiCKcN1Dh1SuMxy87EnEWNvWzwAQCQc119cwQBaMr8I/edit?usp=sharing)

**Comment by daine** [comment]
Here's an example of a figma variable export [figma_var_export.json](https://github.com/user-attachments/files/16274017/figma_var_export.json)

**Comment by realdylanzheng** [comment]
[Dev review | Slack thread](https://gcdigital.slack.com/archives/C05CRB7Q9NE/p1721946416237059?thread_ts=1721793349.867479&cid=C05CRB7Q9NE)
Final edits pending

**Comment by realdylanzheng** [comment]
@melaniebmn [Final edits](https://www.figma.com/design/mh2maMG2NBtk41k1O1UGHV/GC-Design-System?node-id=4-1006&t=CVaABP9nX5RyS2aX-0) have been made as per [your review](https://gcdigital.slack.com/archives/C05CRB7Q9NE/p1721946416237059?thread_ts=1721793349.867479&cid=C05CRB7Q9NE). This ticket will be moved to Done.
