### ISSUE TITLE
Set scope for all variables

### ISSUE THREAD

**Issue by adorayi** [cds-snc/design-gc-conception#873]
This applies to number variables (only?)

<img width="742" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBek9mQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3d6d4f94d87c4c95764a0a9ace2509ebfac2d4e3/image.png" alt="image.png" />

Acceptance criteria:
- Each number type variable in Figma EN library has the appropriate number scoping
- Each number type variable in Figma FR library has the appropriate number scoping

**Comment by realdylanzheng** [comment]
@adorayi can we close this issue since this work is already scoped as part of #872
