### ISSUE TITLE
Design: Update components that have been integrated with the link component

### ISSUE THREAD

**Issue by adorayi** [cds-snc/design-gc-conception#874]
gcds-link was integrated into the following components, ensure the updates have been made in Figma for the following components to maintain consistency:

- [x] gcds-breadcrumbs
- [x] gcds-card (won't do)
- [x] gcds-footer (won't do)
- [x] gcds-lang-toggle

**Comment by realdylanzheng** [comment]
@adorayi 

- Won't do card because card headline is it's own text property
- Won't do footer because the those links are styled differently than our standard links

**Comment by adorayi** [comment]
cc @melaniebmn for confirmation before closing.

**Comment by melaniebmn** [comment]
Hey @realdylanzheng wanted to check in on why we can't use the link component in the footer. It uses the same colour and other styles that we are currently using for the footer from what I can tell.

**Comment by melaniebmn** [comment]
Looking at the link component in Figma - it seems we are missing the "light" variant for the Figma component but it is present for the coded component. Can we update the Figma component to include this as well?

https://cds-snc.github.io/gcds-components/?path=/docs/components-link--overview#variants

@adorayi tagging you for visibility

**Comment by realdylanzheng** [comment]
@melaniebmn Good question regarding the light link variant. I wasn't part of the initial planning for the component, but there are a few differences of the light link (for footer) from our standard links:
- Colour (not blue)
- Interaction (underline only appears on hover)
which might suggest why the designers didn't want to offer the footer or light link for "normal" use and it is treated like a subcomponent unique to the footer.
