### ISSUE TITLE
Design: Update components that have been integrated with the heading component

### ISSUE THREAD

**Issue by adorayi** [cds-snc/design-gc-conception#876]
gcds-heading was integrated into the following components, ensure the updates have been made in Figma for the following components to maintain consistency:

## Acceptance criteria

- [x] Component name is **Heading**
- [x] Heading has a text property
- [x] gcds-error-summary (won't do)
- [x] gcds-stepper (won't do)
- [x] Check other references to Heading in Figma

## Done when

- [x] EN component is published
- [x] FR component is published
- [x] EN poster is updated
- [x] FR poster is updated

**Comment by realdylanzheng** [comment]
@adorayi 
- Heading component won't be applied to Error Summary because we don't want designers to change the heading level
- Heading component won't be applied to Stepper because the heading has it's own text property (Step title)
- Instead components that use the Heading will leverage the Heading text style

**Comment by adorayi** [comment]
cc @melaniebmn for confirmation before closing.

**Comment by melaniebmn** [comment]
Hey @realdylanzheng would you mind explaining (for my understanding) why it is a problem to have the nested property heading level exposed with the error summary and why you decided against using the heading component here? The purpose of using the heading, text, and link components within our components was to 1) ensure consistency and 2) help users understand our heading component and its heading levels. It should be easier for users to understand how we want them to use the heading component and its different heading levels when they can see how we use it within our components. For example, selecting the error summary heading would show that we are using the heading component using the H2 heading level. The new notice component also seems to not be using the heading component.

**Comment by adorayi** [comment]
@realdylanzheng need a response on this one.

**Comment by realdylanzheng** [comment]
@melaniebmn let's meet and I'll share screen it's easier to understand that way.
