### ISSUE TITLE
Modify the Figma home page to be compliant with Canada.ca guidelines

### ISSUE THREAD

**Issue by adorayi** [cds-snc/design-gc-conception#877]
Changes to be made:

- [ ] Colors, backgrounds
- [ ] FIP elements
- [ ] Typography

<img width="995" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOTZrQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6f96380decad3c50471c43b1e284890fd6353b98/image.png" alt="image.png" />

**Comment by adorayi** [comment]
@SmartMouthWords can you add any other changes that need to be made?

**Comment by SmartMouthWords** [comment]
We'll need both languages. We have the French content.
