### ISSUE TITLE
testing concept of bilingual figma

### ISSUE THREAD

**Issue by adorayi** [cds-snc/design-gc-conception#878]
- Follow-up to survey conducted by figma users, on concept of bilingual figma
- Structure a research plan/interview questions for participants on how they would navigate, and apply bilingual figma 
- Focus on findability 
- Is it cumbersome to have 2 pages (En & FR) figma library, or is it resourceful 
- Is it easier to have files in one place
- Learn about the benefits of having simultaneous EN & FR content

**Comment by adriannelee** [comment]
Reviewed today and provided some feedback

**Comment by Lu-stack-art** [comment]
test
