### ISSUE TITLE
Explore limiting edit access for Figma library

### ISSUE THREAD

**Issue by realdylanzheng** [cds-snc/design-gc-conception#884]
As a design system maintainer...
I would like to minimize risk of unintended changes and unapproved intentional edits to our main components and posters...
to ensure the integrity and consistency of the design system.

**Comment by adorayi** [comment]
An exploration, to check if we lock access, can users still make changes; also how do we communicate these changes to users. Work with @brockhigg10

**Comment by realdylanzheng** [comment]
@adorayi 
- Reviewed permissions on EN & FR libraries - Anyone with link can view
- Reviewed collaborators and permissions are appropriate

No communication to users are necessary

**Comment by adorayi** [comment]
Can you point me to a list of our "collaborators" and how is this managed?
So all the comments we have so far are from collaborators?
