### ISSUE TITLE
Dev: Documentation for token usage

### ISSUE THREAD

**Issue by adorayi** [cds-snc/design-gc-conception#889]
Document how devs can use our tokens in their code.
Make sure to cover these things:

- [ ] How to install
- [ ] How to use
- [ ] Downloaded package structure

**Comment by melaniebmn** [comment]
@daine @adorayi I think we can close this ticket. We recently added documentation for token usage to the [token readme](https://github.com/cds-snc/gcds-tokens/blob/main/README.md).

**Comment by melaniebmn** [comment]
Talked to Daine - she agreed it can be closed so closing this issue.
