### ISSUE TITLE
Alpha documentation site research: Awareness and onboarding for small teams 

### ISSUE THREAD

**Issue by samsadasivan** [cds-snc/design-gc-conception#89]
**TODO**
- [x] Share research questions for small teams with Catalina 
- [x] Review questions and feedback 

**Outcomes**
- By gathering qualitative data around the current state of the entry points and the awareness channels, users can be onboarded in more than one location so that they get a high-level understanding of what is mandatory at each touchpoint. 

**Deliverables**
- TBD

**Out of scope**
- Insights from large teams (web teams with 3+ people, set CMS)

**Comment by adeyfarah** [comment]
Laura reviewing this week/ Catalina to meet with Sam post Laura's review

**Comment by adeyfarah** [comment]
Find the alpha documnetation site (link) and send to team

**Comment by ioanacontu** [comment]
@CatalinaPerez123 - to add the link. Team to review and ask for clarifications if needed.

**Comment by CatalinaPerez123** [comment]
https://docs.google.com/document/d/1a0yNRb42JHF29MqAcSYDGJTO4bMWmY9pt10Isft1uXY/edit?usp=sharing
