### ISSUE TITLE
Cards - level 2 updates

### ISSUE THREAD

**Issue by RavinaSamaroo** [cds-snc/design-gc-conception#893]
- [x] Look into different styling of tags - creating a tag component
- [x] Add Canada.ca label component to cards
- [x] Remove link styling from standard cards as the entire card is clickable
- [x] Modernize styling of cards - drop shadows + remove border
- [x] Assess removing action cards (that have buttons) as it may be confusing and misused having a link and a button within the card
- [x] Change focus style to focus on the whole card as opposed to just the title of the card
- [x] Update documentation
- [x] Update FR

**Comment by RavinaSamaroo** [comment]
Content changes to poster ready for review @MatildePerrusclet @adorayi. Highlighted changes in red text. https://www.figma.com/design/7HNtNYzWNmcxjYtG8UlnBz/branch/mmrtUgnxevbXRAN5dg7Tmc/Internal-assets?node-id=1-4764&t=DK9GbDtz0KIxoFTv-0

**Comment by adriannelee** [comment]
Matilde has reviewed this. Ravina will make more changes and send to translation. Started on the guidance also. Will start on the documentation to wrap up the card.

Worked with Élise on the FR, now published.

**Comment by RavinaSamaroo** [comment]
Link to updated guidance: https://docs.google.com/document/d/12ESkEF2pafMN-XoUWznvkOB2EyBxasOxvyVxTMZAZsY/edit

Link to component: https://www.figma.com/design/mh2maMG2NBtk41k1O1UGHV/GC-Design-System?node-id=5757-12701&t=81VpcickndVK9TAB-0
