### ISSUE TITLE
PLANNING - Developer onboarding test

### ISSUE THREAD

**Issue by adriannelee** [cds-snc/design-gc-conception#894]
One of our (draft) OKRs for 2024/25 is to gather baseline metrics. One of those metrics is onboarding friction for developers. Developer onboarding is also something we don't have recent data on and there have been changes since the last research activity (2022/05 Prototype testing). 

## Done when
- [x] [Research plan](https://docs.google.com/document/d/1k5yJ7hOIPaYk0oTuOEDg2mC_losrHV6FgFXOcWs1TVc/edit#heading=h.kuet5xy8d04s) outlines the questions we want to answer and the approach we want to take
- [x] The research design will measure the baseline (what we have right now)
- [x] The research design will help us understand the criticality of the usability issues.
- [x] Plan is reviewed by @adorayi 
- [x] Plan is reviewed by @samburtonCDS 
- [x] [Privacy statement](https://docs.google.com/document/d/1gochXRGKQbdfwBOXUGEAYhPNDNm8DKW51d0wf4ZIGA4/edit#heading=h.k99xncfdmaa2) is drafted
- [x] Privacy statement is reviewed by @samburtonCDS 
- [x] Privacy statement is translated
- [x] Recruitment materials are drafted
- [x] Recruitment materials are translated
- [x] [Facilitation guide](https://docs.google.com/document/d/14zDvYjfKeGs-tQUXgtPubjPBnU9WQsH8iMn5JyjQr9U/edit) is drafted
- [x] Facilitation guide is translated
- [x] Translated guide is reviewed by @ClementineHahn (FR facilitator)

**Comment by adriannelee** [comment]
Started working on this yesterday, organizing the research questions we have. Will continue working on this today.

**Comment by adriannelee** [comment]
Finished drafting the research plan for the dev onboarding test, shared with Sam B for her review. 

Will prep the privacy statement & facilitation guide for the dev onboarding test today.

**Comment by adorayi** [comment]
https://docs.google.com/document/d/1k5yJ7hOIPaYk0oTuOEDg2mC_losrHV6FgFXOcWs1TVc/edit#heading=h.kuet5xy8d04s

**Comment by adriannelee** [comment]
Drafted recruitment materials today (invites & screener questions), ready for review. 

Sent the facilitation guide, recruitment materials and privacy statement to translation today.

**Comment by adriannelee** [comment]
Feedback on the facilitation guide from Clémentine was incorporated today.

**Comment by adriannelee** [comment]
Just waiting on translations to send out the invites

**Comment by adriannelee** [comment]
Doing today:

- Prep the notetaking template
- Review research plan for compensating participants

**Comment by adriannelee** [comment]
Sam will create another privacy statement for participants who will be compensated on Monday

Yesterday:
- Prepped some materials to be able to compensate participants

Today:
- Prepped the notetaker template
- Do some recruitment via CDS developers
