### ISSUE TITLE
Point Figma links on FR pages to FR library

### ISSUE THREAD

**Issue by realdylanzheng** [cds-snc/design-gc-conception#897]
As a user...
I want all links to Figma on FR pages to point to [Système de design GC](https://www.figma.com/file/o4SguSZdar2CCFzSkWNrmB/Syst%C3%A8me-de-design-GC?type=design&t=NAS6ReTVGQjCbUlX-6).

## Acceptance criteria

- [x] All Figma links point navigate to Système de design GC

## Done when

- [x] Pages merged and "published"

**Comment by melaniebmn** [comment]
Added in [PR #341](https://github.com/cds-snc/gcds-docs/pull/341)
