### ISSUE TITLE
Revert changes to Error Summary

### ISSUE THREAD

**Issue by realdylanzheng** [cds-snc/design-gc-conception#899]
## Acceptance criteria

- [x] Links are red with our regular focus state for links
- [x] Border is red
- [x] Focus does not focus border 
- [x] Remove focus text colour from heading when component is in focus

## Done when

- [x] Revision is merged

**Comment by realdylanzheng** [comment]
[Revert rational](https://docs.google.com/document/d/185seVPLzZr11b9lGjBieZolLp3XOk8Uedu4Pef7ucBA/edit?usp=sharing)

**Comment by melaniebmn** [comment]
Error summary style changes reverted in [PR #519](https://github.com/cds-snc/gcds-components/pull/519)
