### ISSUE TITLE
Design: Create mobile variants of icons

### ISSUE THREAD

**Issue by adorayi** [cds-snc/design-gc-conception#901]
### Context

Our icon component was created before we had a mobile font scale in place so we are missing mobile variants in all sizes for our icon component. 

Since the icons should be used with their corresponding font sizes, these could be used incorrectly when using a desktop icon with a mobile font size.

### To do

- [x] Create keyline grid for mobile font scale (*H1-H6, body text, caption*)
- [x] Scale each icon to the new grid sizes
- [x] Create mobile component with new icons
- [x] Replace broken desktop icon instances in figma with updated component
- [x] Replace mobile icon instances with updated component
- [x] Make sure subcomponents are using updated icon component
- [x] Make sure anatomy images are using the new icon component
- [x] Publish changes in EN/FR
- [x] Create new font file/package
- [x] Hand-off to devs

**Comment by nmakuch** [comment]
[gcds-icons_v1.2.zip](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3NkQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e39757856a3913b92a90a5c39d74431b466d3aa1/gcds-icons_v1.2.zip)

**Comment by nmakuch** [comment]
Had to update the font package again due to a small issue in the chevrons that I noticed
[gcds_icons_v1.4.zip](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjBqQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a115ab5618c0b109200634a62e926e142323b0c5/gcds_icons_v1.4.zip)
