### ISSUE TITLE
Tests passing (Vue component package)

### ISSUE THREAD

**Issue by daine** [cds-snc/design-gc-conception#909]
## 📇 User story

As a developer, I want to ensure that the GCDS Vue package is functioning as it should and have ways to inform us if it is not.

## ✅ Definition of Done
- [ ] E2E tests for multiple components in Vue

## 📜 Acceptance criteria
- [ ] Tests passing

## 📝 More info
This is related to 
- https://github.com/cds-snc/gcds-components/issues/497

Work that is moved into a separate ticket:
- #908
- #909

**Comment by ethanWallace** [comment]
Setup a [branch](https://github.com/cds-snc/gcds-components/tree/chore/vue-package-tests) that has a basic component test on `gcds-input` using cypress. Will need to build out more and figure out way to do E@E tests

**Comment by ethanWallace** [comment]
Awaiting PR review
