### ISSUE TITLE
Design: Change our current monospace font choice to a Google Fonts supported monospace font

### ISSUE THREAD

**Issue by melaniebmn** [cds-snc/design-gc-conception#910]
We are currently using "Menlo" as our recommended monospace font, which Google Fonts doesn't support. We use Google Fonts for our other 2 fonts (Lato & Noto sans). Let's replace "Menlo" with a font that Google Font supports to have all 3 fonts coming from the same place. 

## Acceptance criteria

- [x] Regular mono text style is Noto Sans Mono
- [x] Mobile mono text style is Noto Sans Mono

## Done when

- [x] Font style is published

**Comment by realdylanzheng** [comment]
[Decision record: Monospace font](https://docs.google.com/document/d/1ABC0FbRtUlaHNbBwriORndZ0aXfJTrO9ZmefN35CMD8/edit?usp=sharing)
