### ISSUE TITLE
Dev: Change our current monospace font choice to a Google Fonts supported monospace font

### ISSUE THREAD

**Issue by melaniebmn** [cds-snc/design-gc-conception#911]
We are currently using "Menlo" as our recommended monospace font, which Google Fonts doesn't support. We use Google Fonts for our other 2 fonts (Lato & Noto sans). 

- [x] Let's replace "Menlo" with a font that Google Font supports to have all 3 fonts coming from the same place. 
- [x] Do we need to update installation instructions where the font awesome is referenced?

## Value
Users will not have to download more font packages when setting up

**Comment by melaniebmn** [comment]
Currently blocked by: 
https://app.zenhub.com/workspaces/design-system-6100624a19f4cf000e46e458/issues/gh/cds-snc/design-gc-conception/910

**Comment by realdylanzheng** [comment]
[Decision record: Monospace font](https://docs.google.com/document/d/1ABC0FbRtUlaHNbBwriORndZ0aXfJTrO9ZmefN35CMD8/edit?usp=sharing)

**Comment by melaniebmn** [comment]
@adorayi we currently don't reference the fonts in our installation instructions. It would be worth reconsidering mentioning them there for a future update on our installation instructions.

**Comment by adorayi** [comment]
I've added a ticket placeholder for the font reference in installation.
