### ISSUE TITLE
Development: properties feedback from contact form

### ISSUE THREAD

**Issue by adorayi** [cds-snc/design-gc-conception#913]
- The documentation lists “imgSrc”, “imgAlt” and “titleElement” as valid properties. That does seem to be the case for “Angular, Vue” code. If using the code generation widget, we notice that these properties’ names are “img-src”, “img-alt” and “title-element” respectively. However, for the “React” code portion, the property names are different. Should there be 2 “property tables” to properly reflect the valid options for each coding framework. Or maybe, the property names should be the same regardless of technology. Regardless, the property table should mention the difference, if there is one.
- 
## Value
Consistency, might be a bug in Storybook

**Comment by ethanWallace** [comment]
The properties in the event & properties tables do not match the format we use on other components, can be [seen here](https://cds-snc.github.io/gcds-components/?path=/docs/components-card--events-properties)
