### ISSUE TITLE
testing OCADU updates with Fable

### ISSUE THREAD

**Issue by Lu-stack-art** [cds-snc/design-gc-conception#919]

**Comment by Lu-stack-art** [comment]
test

**Comment by samburtonCDS** [comment]
@Lu-stack-art When you say "fable policy statement" do you mean the privacy notice for this research activity? A policy statement would be something different, so wanted to clarify! Either way, happy to review once it's ready.

**Comment by ClementineHahn** [comment]
Card is still in progress but should be done by end of sprint, currenlty updating research plan for dev as a result and creating new tasks
