### ISSUE TITLE
Duplicate emitted events from angular components

### ISSUE THREAD

**Issue by ethanWallace** [cds-snc/design-gc-conception#926]
# Summary

Based on feedback, the newest `outputs` update to the angular package is causing events to be emitted twice.

## Acceptance criteria 

- [x] Investigate events in angular components
- [x] Determine a plan to fix the events to only emit once.
- [x] Fix the issue and test

**Comment by adorayi** [comment]
@ethanWallace  please add more details to this card description.

**Comment by ethanWallace** [comment]
Duplicate events are emitted since the angular component uses the new `@Outputs` events and still has the old `rxjs` events from Stencil's implementation. To stop duplicate events, we will need to remove the `rxjs` event listeners.

**Comment by adorayi** [comment]
@ethanWallace do we need to open a new ticket for the work to remove rxjs event listeners?

**Comment by ethanWallace** [comment]
@abdul That work was completed in this PR https://github.com/cds-snc/gcds-components/pull/566
