### ISSUE TITLE
Support formatting text in the Card description (Bold, italics etc)

### ISSUE THREAD

**Issue by adorayi** [cds-snc/design-gc-conception#927]
Consider adding text styling options in the Card component from client feedback.

- I thought I would use the card component to imitate the article listing we use here: https://www.noslangues-ourlanguages.gc.ca/en/blogue-blog-index (image, title, date, short summary and a few buttons). When attempting to use tags in the “description”, such as  the string “” is displayed. Should there be support for basic styling within the “description” property (strong, i, cite, etc.)? Or maybe the “description” property is fine as is, the card might just be missing a slot that can handle HTML, like the “footer”.

## Value
Additional functionality for the Card

**Comment by adorayi** [comment]
The new updates to the Card component with changing the description to a slot will cover this.

**Comment by adorayi** [comment]
@ethanWallace is this issue to be resolved as a "Won't do"? I don't think it is possible to enter rich text in the card after version 2 update right?

**Comment by ethanWallace** [comment]
@adorayi The newest version of the card made this possible by adding a new slot
