### ISSUE TITLE
Setup Styles page on the FR library

### ISSUE THREAD

**Issue by adorayi** [cds-snc/design-gc-conception#931]

**Comment by adriannelee** [comment]
Looking for review from Matilde or Élise when Nick is Done

**Comment by nmakuch** [comment]
Currently getting Matilde to translate some terms before finalizing this

**Comment by nmakuch** [comment]
yep we can close 👍🏽

**Comment by nmakuch** [comment]
https://www.figma.com/design/o4SguSZdar2CCFzSkWNrmB/Syst%C3%A8me-de-design-GC?node-id=2290-8&t=Bwf3zCtOab3Hph2R-0
