### ISSUE TITLE
Design: Add new notice colours to tokens

### ISSUE THREAD

**Issue by RavinaSamaroo** [cds-snc/design-gc-conception#932]
3 new colours were used in the notices component that did not previously exist in our DS. These colours need to be added to our collection of tokens, but we need to determine what value to give them on the colour scale (e.g., orange 700).

New colors were introduced that meet AAA level compliance; note that current colors meet AA level compliance.

## Dev impact
**Yes** - Need to add to gcds-tokens

**Comment by ClementineHahn** [comment]
@realdylanzheng to work on this today to uncblock @ethanWallace on #

**Comment by realdylanzheng** [comment]
It was determine with the PM the Notice component will not pursue AAA compliance. 
The Notice component will meet WCAG 2.1 AA standards as noted on the [GCDS website](https://design-system.alpha.canada.ca/en/styles/colour/). 
As the GCDS component equivalent to Canada.ca's Contextual Alert, the Notice component will use the same colours from the Contextual Alert to retain familiarity.
The 3 colours to be introduced to the GC Design System are: 

- #269ABC (blue)
- #EE7100 (orange)
- #278400 (green)

**Comment by realdylanzheng** [comment]
Visit the [Figma library](https://www.figma.com/design/mh2maMG2NBtk41k1O1UGHV/GC-Design-System?node-id=4-1006&t=W7NDo7mDqMl2fRbc-0) **Local variables** to view the colours within the Base collection.
