### ISSUE TITLE
Gather Decision log and future process

### ISSUE THREAD

**Issue by mcman12** [cds-snc/design-gc-conception#94]
**TODO**
- [ ] 

**Outcomes**
- Ensure we have decision logs in one place
- Figure out format and process to update moving forward

**Deliverables**
- 

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [ ] S: half a day
- [ ] M: 1-2 day
- [ ] L: 1 week
- [ ] XL: Move to an epic

**Out of scope**
-

**Comment by adeyfarah** [comment]
Adey to update tomorrow afternoon

**Comment by adeyfarah** [comment]
Previous decision template (double check with Amy)

**Comment by mcman12** [comment]
moving to #97
