### ISSUE TITLE
Development - Card V2

### ISSUE THREAD

**Issue by RavinaSamaroo** [cds-snc/design-gc-conception#948]
## Acceptance Criteria
- [x] An updated card component is available for use as a web component
- [x] A component with the same name and functionality exists in Vue
- [x] A component with the same name and functionality exists in React
- [x] A component with the same name and functionality exists in Angular

## Definition of Done
- [x] Unit tests are updated or added to match the new design and functionality, and are passing
- [ ] All npm packages are released and published

## Blockers
- [x] Requirements documentation needs to be finalized before work for this one starts. Work has been started in this existing document for the [Card implementation and requirements](https://docs.google.com/document/d/13y5OWeCeh8Ii85es_1OIw14yQyrgI1TiU1-x8WbLNBw/edit) 
  - [x] https://github.com/cds-snc/design-gc-conception/issues/959
- [x] We need a versioning plan on how to release v2 vs v1 (could be a bigger product discussion, devs can come up with proposals)

### More info
Development of [new card](https://www.figma.com/design/mh2maMG2NBtk41k1O1UGHV/GC-Design-System?node-id=5757-12701&t=81VpcickndVK9TAB-0) updates: 

<img width="491" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2xFQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f6f2a4074ea1ef42f0a25f91374c73dd4aeaf21a/image.png" alt="image.png" />

**Comment by ClementineHahn** [comment]
Ethan starts working on it needs to be groomed with Abdul when he comes back

**Comment by ethanWallace** [comment]
In final dev review

**Comment by ethanWallace** [comment]
Passed dev review, have a meeting on Monday to review coded component with designers.

Will need the breaking change messaging to be released and new guidance ready to published before merging/publishing.

**Comment by ethanWallace** [comment]
Release messaging will need to be released and guidance ready to publish before publishing this component.
