### ISSUE TITLE
ANALYZE Developer onboarding research

### ISSUE THREAD

**Issue by adriannelee** [cds-snc/design-gc-conception#949]
## Analysis

- [x] Tag the notes
- [x] Group tags and notes into overarching themes, where applicable
- [x] Describe the themes and how they answer the research questions
- [x] Produce insights based on the themes & tags

## Presentation
- [x] Presentation is made to team

**Comment by adriannelee** [comment]
Presentation today!

**Comment by ClementineHahn** [comment]
Good to wrap by end of sprint
