### ISSUE TITLE
Design - prototype of Dental website for CDS case study

### ISSUE THREAD

**Issue by adorayi** [cds-snc/design-gc-conception#952]
The Platform team did a demo to the Minister last week, creating a story that showed how Platform tools could be used to build out a project.
The feedback was good and the Minister has requested to take it to the next level, by applying it to a real world example: Dental benefits.

The ask is to use GC Design System to:
1. Create a prototype of the Dental website pages
2. Share the prototype (I can use Figma prototype function to link the pages together once done)
3. Report back on the time/effort and challenges

See https://www.canada.ca/en/services/benefits/dental/dental-care-plan.html

Screenshots of the pages to prototype attached here as well: Dental

I have started a table Dental Prototyping Exercise identifying components that are missing from GCDS so we can report back for transparency. For the purpose of this exercise, we can swap with other components or work around them (all components in Figma can be used, even if not published on the website or code yet)

**Comment by nmakuch** [comment]
Will be working out of this file:
[Canadian Dental Care Plan Application - Prototype](https://www.figma.com/design/NJu8jPtAthftrs6v1LptZH/Canadian-Dental-Care-Plan---Prototype?node-id=0-1&t=xgc9lslO03ZaIsRM-0)

**Comment by nmakuch** [comment]
Prototype link
https://www.figma.com/proto/NJu8jPtAthftrs6v1LptZH/Canadian-Dental-Care-Plan---Prototype?node-id=12-869&t=MQI6geeTE5bLKWnw-0&scaling=min-zoom&content-scaling=fixed&page-id=3%3A525&starting-point-node-id=12%3A869&hide-ui=1
