### ISSUE TITLE
Plan Metrics Workshop :  aligning on impact story telling and analytics set up 

### ISSUE THREAD

**Issue by ClementineHahn** [cds-snc/design-gc-conception#954]
In the context of discussion with Growth, product and research, we need to tackle 2 workshops before July to help set base into our understanding and tracking of product metrics. 

To that effect we need to plan and run potentially 2 workshops :

1 led by Jen on the storytelling and impact alignement. What are the metrics we're looking to surface, what rationale does it help us to construct 

~~1 more "practical" on how refine current metrics with analytics. Setting up baseline measurement and whatever board help us surface/track it consistently with the workshop 1 on the storytelling~~

A [document](https://docs.google.com/document/d/1YaAGq9VaUuSDKtMAgM8sE7bJTXYJJbo85TGEStUPORc/edit) to organize the ideas and a spreadsheet to understand the _how_ to collecting each metric. Get feedback from team async for both.

**Comment by daine** [comment]
Related to:
- #922 
- #962

**Comment by adriannelee** [comment]
Shared with the team
