### ISSUE TITLE
Success metrics

### ISSUE THREAD

**Issue by mcman12** [cds-snc/design-gc-conception#96]
**TODO**
- [ ] tbd

**Outcomes**
- Establish immediate success indicators (how we measure the success of our MVP).

**Deliverables**
- List of key results (KRs) for the MVP

**Estimated Effort**
- [ ] XS: 1 to 2 hours
- [ ] S: half a day
- [ ] M: 1-2 day
- [ ] L: 1 week
- [ ] XL: Move to an epic

**Out of scope**
-

**Comment by adeyfarah** [comment]
Ioana to add description / time estimate
