### ISSUE TITLE
Content: Notice component documentation

### ISSUE THREAD

**Issue by realdylanzheng** [cds-snc/design-gc-conception#963]
As a designer or developer...
I want guidance for the Notice component...
So I can understand when and where it should be used.

## Acceptance criteria

- [x] Documentation follows the documentation template
- [x] Documentation describes the differences between Notices and Alerts
- [x] Has [thumbnail image](https://www.figma.com/design/7HNtNYzWNmcxjYtG8UlnBz/Internal-assets?node-id=4902-4539&t=TmGwDd8ZgcPsCSmd-4) 
- [x] Proofread and Writer.com is run on content
- [x] Translation 
- [x] Bilingual review

## Done when

- [x] Done when content has been created 
- [x] Done when design has been reviewed
- [x] Done when images have alt text
- [x] Done when content is ready in English and French

**Comment by adorayi** [comment]
New documentation recommended, but review old draft: https://docs.google.com/document/d/1OWtLThCcHF1y3o2VgqF8Wt2LtU6kTkUMppYpcjZ8XRI/edit

Review contextual alert documentation.

**Comment by adorayi** [comment]
@MatildePerrusclet for review
@ethanWallace for review

**Comment by MatildePerrusclet** [comment]
Done reviewing @adorayi @ethanWallace.
Main concern is that there's already guidance regarding the date input order for the GC, it's YYYY-MM-DD for both languages. 

Ref:
"Choose a date input order to reduce error
In English, generally use month-day-year and in French day-month-year."

Here are the links: 
https://design.canada.ca/style-guide/#wp4-7 
https://www.google.com/url?q=https://www.tbs-sct.canada.ca/pol/doc-eng.aspx?id%3D17284&sa=D&source=docs&ust=1724682711256927&usg=AOvVaw1zuNHNTQeWvIusL-GuHbpU

**Comment by ethanWallace** [comment]
@MatildePerrusclet I assume the above comment was meant[ for this ticket](https://app.zenhub.com/workspaces/design-system-6100624a19f4cf000e46e458/issues/gh/cds-snc/design-gc-conception/699)?

**Comment by MatildePerrusclet** [comment]
Yes thank you @ethanWallace :)

**Comment by MatildePerrusclet** [comment]
Reviewed and reformatted [content is in this document](https://docs.google.com/document/d/1eO2vfaVbe9RQpOZhBCRfIk1f-IyzE9nXkKc0HhVj8RM/edit?usp=sharing), using the component documentation template. It's ready for feedback @adorayi @ethanWallace

**Comment by adorayi** [comment]
@MatildePerrusclet this is ready for review.
https://docs.google.com/document/d/1O0yY_VwkXWV2uQ3EPKovzTx6-VFdRaoHRiNuiLXvjJ0/edit?usp=sharing

**Comment by adorayi** [comment]
New content to be added after analysis of content from DTO. @MatildePerrusclet to action.

**Comment by ClementineHahn** [comment]
Still in review with @SmartMouthWords

**Comment by SmartMouthWords** [comment]
@ethanWallace confirmed change to allow different heading levels is in. 

Last steps needed to be able to send to translation: 
-  @realdylanzheng to provide updated anatomy image with Notice example
- @ethanWallace Confirm if you're good using the same text we used for card headings
- @MatildePerrusclet to accept changes. If needed flag issues to @SmartMouthWords and we can meet

**Comment by realdylanzheng** [comment]
@SmartMouthWords [Anatomy image](https://docs.google.com/document/d/1O0yY_VwkXWV2uQ3EPKovzTx6-VFdRaoHRiNuiLXvjJ0/edit?tab=t.0#heading=h.jdc5w03kb818) has been updated

**Comment by ClementineHahn** [comment]
WAiting an answer frrom Simon / translation on this

**Comment by daine** [comment]
This is currently in content review from being back from translation. We're waiting for the content to be finalized before starting work on updating the documentation.

**Comment by SmartMouthWords** [comment]
Bilingual review complete. 
[French version](https://docs.google.com/document/d/1eAGs6Yjw3vhvXcIA4wrqgQK0YXYuvQ_FCMFQI6SIs_8/edit?tab=t.0)
[English version ](https://docs.google.com/document/d/1O0yY_VwkXWV2uQ3EPKovzTx6-VFdRaoHRiNuiLXvjJ0/edit?tab=t.0)

**Comment by daine** [comment]
https://github.com/cds-snc/design-gc-conception/issues/1217#issuecomment-2517709016
_Copied Amy's comment from the other ticket:_
**Text for the notice on the component overview page**
EN: "A short, prominent message that’s part of the page content."
FR: "Un message court et bien visible qui fait partie du contenu de la page."

**Comment by ClementineHahn** [comment]
All content ready and done in this ticket will be actioned in 
- documentation website update here : https://app.zenhub.com/workspaces/design-system-6100624a19f4cf000e46e458/issues/gh/cds-snc/design-gc-conception/1287
- publishing #1217

**Comment by SmartMouthWords** [comment]
Alt text:  
"A blue vertical line truncated at the top by a blue circle, representing the guide line and icon, sits to the left of a stack of three thick grey lines. The top dark grey line represents the heading and the other two represent the lines of text."
French:
"Une ligne bleue verticale tronquée par un cercle bleu, représentant la ligne guide et l’icône, se situe à gauche de deux épaisses lignes grises pâle alignées sous une ligne grise foncée représentant un titres et des lignes de texte."
