### ISSUE TITLE
StencilJS Patched Package as a dependency

### ISSUE THREAD

**Issue by daine** [cds-snc/design-gc-conception#971]
## 📇 User story
- As a developer using gcds components, I want the react ssr package to use the correct patched package of stencil js as its dependency so that I do not encounter any issues or errors 

## ✅ Definition of Done / Outcomes
- [x] Components package uses a patched version of stencilJS
- [x] Patched version contains the exact patch we have / we're using

## 📜 Acceptance criteria
- [x] Tests (automated or manual) are passing for the react-ssr package
- [x] Tested with an example app (https://github.com/cds-snc/gcds-examples)

## 📝 More info

Related to 
- #951

**Comment by adorayi** [comment]
is this done? @ethanWallace @daine 
I see it in the "Done" pipeline, yet the latest comment and the checklist suggests otherwise.

**Comment by ethanWallace** [comment]
@adorayi Yes this is done
