### ISSUE TITLE
Ensure consistent library file structure between EN and FR Figma libraries

### ISSUE THREAD

**Issue by realdylanzheng** [cds-snc/design-gc-conception#973]
To ensure bilingual equity, the EN and FR Figma libraries should have identical file structures and pages.

## Acceptance criteria:

- [x] Ensure EN and FR Figma libraries are a 1:1 match in terms of pages (move miscellaneous pages to internal assets or archive)

**Comment by adorayi** [comment]
Review is completed, multiple new tickets opened as a result.
