### ISSUE TITLE
typo on doc website - side nav component page

### ISSUE THREAD

**Issue by ClementineHahn** [cds-snc/design-gc-conception#979]
### Context:
A ticket came in through support , ticket #17872 , flagging a typo on our doc website .

### Task:
Update the text content on [this page](https://design-system.alpha.canada.ca/en/components/side-navigation/) to match the expected wording that should be :
" Also called: sidebar menu, lefthand nav, vertical navigation."

### Definition of done:
New wording is displayed on te doc website and freshdesk ticket is closed

**Comment by ClementineHahn** [comment]
#Context : 
A ticket came in through support , ticket [#17872](https://cds-snc.freshdesk.com/a/tickets/17872) , flagging a typo on our doc website  . 

# Task: 
Update the text content on [this page](https://design-system.alpha.canada.ca/en/components/side-navigation/) to match the expected wording that should be : 
" Also called: sidebar menu, lefthand nav, vertical navigation." 

# Definition of done : 
New wording is displayed on te doc website and freshdesk ticket is closed

**Comment by daine** [comment]
Fixed by: https://github.com/cds-snc/gcds-docs/pull/372
