### ISSUE TITLE
[PLANNING] Conduct market research

### ISSUE THREAD

**Issue by adriannelee** [cds-snc/design-gc-conception#981]
Understand from designers and developers across the GC their contexts of work, work tools, levels of seniority, ways of working

Example questions:
a) if they have ever used GC Design System?
b) if they plan to use GC Design System?
c) what design system (if any) they currently use for their work?

### Done when

- [x] Research plan is drafted
- [x] Research plan is reviewed by @adorayi @brockhigg10 and Jeana
- [x] Draft of survey questions is completed
- [x] Draft of survey questions finalized
- [x] Survey questions are submitted to translation
- [x] Privacy statement is drafted
- [x] Privacy statement reviewed by Nisa 
- [x] Privacy statement is submitted to translation
- [x] Analysis plan is drafted
- [x] Analysis plan finalized
- [x] Calculate "Total population" for *this* survey
- [x] List of invitees created
- [x] Invite drafted
- [x] Invite submitted to translation

**Comment by ClementineHahn** [comment]
list of invitees still in progress as review of the research plan and questions

**Comment by adriannelee** [comment]
Invite and privacy statement are back from translation

**Comment by adriannelee** [comment]
Removed "Calculate "Total addressable market"" from the to-do's because GEDS is inaccurate and we need some more data about its accuracy before we can calculate the addressable market.
