### ISSUE TITLE
Update 'coming soon' card design

### ISSUE THREAD

**Issue by RavinaSamaroo** [cds-snc/design-gc-conception#985]
Can't use the card component on the 'Get involved' page anymore because we are removing the functionality to use cards without links. Need a new design for this:

Acceptance criteria:
Design should have a way to show the following information for coming soon items
- [x] item name
- [x] item description

Done when:
- [x] a proposal for the new design has been shared, reviewed and accepted by the team

<img width="720" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVdQQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d3ab075f3cc689db5c09f13ee98eacdbd0c5a474/image.png" alt="image.png" />

**Comment by realdylanzheng** [comment]
Here's a [concept design](https://www.figma.com/proto/oAcr0FE65QkIZN1ae1ltbB/Playground-(internal)?node-id=106-1201&t=ZY41S79NfbjAzxkL-1&scaling=min-zoom&content-scaling=fixed&page-id=106%3A1200)

**Comment by SmartMouthWords** [comment]
Reviewed concept design and proposed some changes in the file.

**Comment by adorayi** [comment]
@realdylanzheng I think the latest version in the file is good to go if we remove the status. The expected release is enough information. Can you make that quick change so this can move forward?

**Comment by realdylanzheng** [comment]
@adorayi @melaniebmn [Get involved page (open in Figma)](https://www.figma.com/design/oAcr0FE65QkIZN1ae1ltbB/Playground-(internal)?node-id=231-2234&t=vypSt58af5Z1X2Ym-4) has been marked ready for dev. Thanks

**Comment by brockhigg10** [comment]
Sorry, just saw this card.  A couple of questions:

- My understanding is Icon and Standard Page Template are close to completion.  We have them listed in the "Contribute to our next priorities" section.  Are we actually accepting contributions for these by the time this is published? If the answer is no, I recommend they go in "Coming Soon"
- Are we no longer wanting Data Table, Image and Tag in the "Contribute to next priorities" section?
- Do we want to add Date Input into coming soon?
